#!/bin/bash
# Parameter
# 1. Directory in dem sich das Modell (die .dmd sowie das Verzeichnis) befindet. Mit abschliessendem /
#	es wird in IMDIR IMDIR/IM und IMDIR/gitHub/IM gesucht
# 2. optional Modellname (nur falls es mehr als 1 .dmd Datei hat)
IMDIR=$(dirname "$0")/
python3 ~/PycharmProjects/IM_db/fillDB.py "$IMDIR"
