#!/bin/bash
BASEDIR="$(dirname "$0")"
PARAMFILE="IM_GEBERIT.params"
SourceDIR="/Users/stb/Documents/Projekte/FYAYC_intern/gitHub/pythonWork/pythonSource/WebReport"
python3 "$SourceDIR/listmapping.py" "$BASEDIR/$PARAMFILE" 
