#!/bin/bash
PARAMFILE="$(dirname "$0")/IM_GEBERIT.params"
SourceDIR="/Users/stb/Documents/Projekte/FYAYC_intern/gitHub/pythonWork/pythonSource/WebReport"
python3 "$SourceDIR/webfillallin1.py" "$PARAMFILE" en
