#!/bin/bash

# Verifies that all github action scripts in .github/workflows/ are in parsable YAML format.
#
# Called by "git push" after it has checked the remote status,
# but before anything has been pushed.
# If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local element> <local sha1> <remote element> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

#remote="$1"
#url="$2"

python -c "\
import yaml
import glob

for script in glob.glob('.github/workflows/*.yaml', recursive=False):
    try:
        yaml.safe_load(open(script))
    except Exception as e:
        print(\"Unable to parse {script}\".format(script=script), e)
        exit(-1)

exit(0)
"

