channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipython
  - deprecated
  - requests-oauthlib
  - requests
  - openpyxl
  - lxml
  - tqdm
  - colorama
  - jsonschema
  - matplotlib
  - pandas
  - markdown
  - invoke
  - nbconvert
  - nbstripout
  - papermill
