name: base
#channels:
#  - conda-forge
#  - defaults
dependencies:
  - python=3.8
  - ipython
  - deprecated
  - requests-oauthlib
  - nbstripout
  - papermill
  - openpyxl
  - lxml
  - tqdm
  - colorama
  - jsonschema
  - matplotlib
