name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - ipython
  - deprecated
  - requests-oauthlib
  - nbconvert
  - nbstripout
  - papermill
  - openpyxl
  - lxml
  - tqdm
  - colorama
  - jsonschema
  - matplotlib
  - requests
  - pandas
