name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - nbstripout
  - papermill
  - openpyxl
  - lxml
  - colorama
  - deprecated
  - jsonschema
  - requests-oauthlib
