[pytest]
markers =
    integration: integration testcases requiring refmodels (deselect with '-m "not integration"')
    nocoverage: exclude this test in the coverage run

addopts = --ignore=target/ --ignore=_sokrates/ --ignore=notebooks/Sandbox/ --ignore=lib/ --ignore=unittest-tmp-dir --basetemp=unittest-tmp-dir

log_cli = 1
log_cli_level = WARNING
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S