[pytest]
markers =
    integration: integration testcases requiring refmodels (deselect with '-m "not integration"')

addopts = --ignore=target/ --ignore=_sokrates/ --ignore=notebooks/Sandbox/ --ignore=lib/ --basetemp=unittest-tmp-dir
