#!/bin/bash
#Autor: stb 
#MYDIR: Verzeichnis in meiner Umgebung für die gemeinsamen Dateien des Modelers
#		Der Pfad für das Standardverzeichnis für Systemtypen im ODM zeigt dorthin.
#		Inhalt: das aktuell verwendete Verzeichnis "Konfiguration"
#		Das Konfigurationsverzeichnis des akutell zu startenden Modells (IM-Verzeichnis des Mandanten) wird nach MYDIR kopiert
#		und nach dem Aussteigen aus dem Modeler wieder zurück ins IM-Verzeichnis des Mandanten
#BASEDIR: 	Basisverzeichnis in dem sich das Verezeichnis IM befindet, in dem sich das Modell befindet.
#			In diesem Verzeichnis muss sich auch setModellname.sh stehen, das den IMNAME definiert.
#			Default: Verzeichnis, in dem sich das ODM-Script das gestartet wurde steht
#IMNAME:	wird als Name der Startdatei gesetzt
#ODMVERSION: Version des Oracle Data Modelers (ist im Verzeichnisname der Installation enthalten.)
BASEDIR=$(dirname "$0") 
IMNAME=`basename "$0"`
#Alternative für SOURCE IMNAME=""
echo "*******************"
echo Modell: $IMNAME
echo "*******************"
source "/Users/stb/Documents/Projekte/setVersion.sh"
cp  -v "$BASEDIR/IM/Konfiguration"/* "$MYDIR/Konfiguration/"
/Applications/OracleDataModeler$ODMVERSION.app/Contents/Resources/datamodeler/datamodeler/bin/datamodeler "$BASEDIR/IM/$IMNAME.dmd"
cp  -v "$MYDIR/Konfiguration/"* "$BASEDIR/IM/Konfiguration/"
exit 0