confluence:
  apiurl: 'https://foryouandyourteam.com'
  space: '~bue'
  rootpage: 'foryouandyourcustomers internal IM'

credentials:
  username: bue
  password: 'OB7P,aXLAEZ9%bBzYyV+x`'

verify_ssl: true
