#!/bin/bash
#Autor: stb 
#MYDIR: Verzeichnis in meiner Umgebung für die gemeinsamen Dateien des Modelers
#		Der Pfad für das Standardverzeichnis für Systemtypen im ODM zeigt dorthin.
#		Inhalt: das aktuell verwendete Verzeichnis "Konfiguration"
#		Das Konfigurationsverzeichnis des akutell zu startenden Modells (IM-Verzeichnis des Mandanten) wird nach MYDIR kopiert
#		und nach dem Aussteigen aus dem Modeler wieder zurück ins IM-Verzeichnis des Mandanten
#BASEDIR: 	Basisverzeichnis in dem sich das Verezeichnis IM befindet, in dem sich das Modell befindet.
#			In diesem Verzeichnis muss sich auch setModellname.sh stehen, das den IMNAME definiert.
#			Default: Verzeichnis, in dem sich das ODM-Script das gestartet wurde steht
#IMNAME:	wird als Name der Startdatei gesetzt
#ODMVERSION: Version des Oracle Data Modelers (ist im Verzeichnisname der Installation enthalten.)
lc=`ps -eaf | grep "Oracle Data Modeler" | wc -l`
if [ $lc -ge "2" ]; then
	echo "***********************************************"
	echo "Oracle Data Modeler läuft bereits."
	echo "***********************************************"
	exit 1
fi
BASEDIR="$HOME/Documents/Projekte/FYAYC_intern"
IMNAME=IM_TrainingServices
LANGUAGE=DE
IMDIR=$BASEDIR/gitHub/TrainingServices/IM
MYDIR=$HOME"/Documents/DataModeler"
echo "*******************"
echo Modell: $IMNAME 
echo BASEDIR $BASEDIR
echo KonfigurationDir $MYDIR
echo IM-Name $IMNAME
echo Modeler Language $LANGUAGE
if [ "$LANGUAGE" == "EN" ] ; then
	cp -v "$MYDIR/Software/productconfig/ENdatamodeler.conf" "/Applications/OracleDataModeler.app/Contents/Resources/datamodeler/datamodeler/bin/datamodeler.conf"
elif [ "$LANGUAGE" == "DE" ] ; then
	cp -v "$MYDIR/Software/productconfig/DEdatamodeler.conf" "/Applications/OracleDataModeler.app/Contents/Resources/datamodeler/datamodeler/bin/datamodeler.conf"
else
	cp -v "$MYDIR/Software/productconfig/datamodeler.conf" "/Applications/OracleDataModeler.app/Contents/Resources/datamodeler/datamodeler/bin/datamodeler.conf"
fi
	
rsync -av --delete "$IMDIR/Konfiguration/" "$MYDIR/Konfiguration"
/Applications/OracleDataModeler.app/Contents/Resources/datamodeler/datamodeler/bin/datamodeler "$IMDIR/$IMNAME.dmd"
rsync -av --delete "$MYDIR/Konfiguration/" "$IMDIR/Konfiguration"
exit 0