import json
import unittest
from pathlib import Path

import pytest
import logging

from INTERFACES.UI import std2simpleui


class MyTestCase(unittest.TestCase):
    @pytest.fixture(autouse=True)
    def inject_fixtures(self, caplog, tmp_path, capsys):
        self.caplog = caplog
        self.capsys = capsys
        self.temppath = Path(tmp_path)

    def setUp(self) -> None:
        self.debugpath = (Path.home() / "Downloads") if (Path.home() / "Downloads").exists() else self.temppath

    def dumpjson(self, filepath: Path, jsonstruct):
        with open(filepath, 'w') as outfile:
            json.dump(jsonstruct, outfile, indent=2)
        return

    def _create_uijson(self,inpath,outpath):
        with open(inpath) as infile:
            injson = json.load(infile)

        self.caplog.clear()
        self.caplog.set_level(logging.INFO)
        ui = std2simpleui.UiSimple(stdmodel=injson)
        uijson = ui.generate_uijson(diagname="Visualsierung Astronomie",
                                         lang=None)
        print ('\n'.join(m for m in self.caplog.messages))
        self.dumpjson(outpath, uijson)

        return uijson

    def test_simpleui(self):
        """
         with astronomie standard json
            create a simple ui json and write it to the debug directory

        """
        infilepath = Path(__file__).parent / "testfiles" / "astronomie-standard.json"
        outfilepath = self.debugpath / f"{infilepath.stem}-ui.json"
        uijson=self._create_uijson(inpath=infilepath,
                                   outpath=outfilepath)
        print('\n', outfilepath, " written")
        #self.assertTrue(len(uijson.get("elements").get("categories"))>0)
        #self.assertTrue(len(uijson.get("elements").get("entities"))>0)
        #self.assertTrue(len(uijson.get("elements").get("relationships"))>0)

        return

    def test_updateui(self):
        """
        generate a simple ui from astronomy
        update the generated file
        """
        #first create a ui file on temp
        infilepath = Path(__file__).parent / "testfiles" / "astronomie-standard.json"
        outfilepath = self.temppath / f"{infilepath.stem}-ui.json"
        injson=self._create_uijson(inpath=infilepath,
                                   outpath=outfilepath)

        # read file generated by test_astro_diagram
        with open(outfilepath) as updfile:
            updjson = json.load(updfile)

        # remove an entity a category and a relationship
        # entities=updjson.get("elements").get("entities")
        # categories=updjson.get("elements").get("categories")
        # relationships=updjson.get("elements").get("relationships")
        # del entities[2]
        # del categories[1]
        # del relationships[0]
        self.caplog.clear()
        self.caplog.set_level(logging.INFO)

        newuijson = std2simpleui.UiSimple(stdmodel=injson,
                                          destjson=updjson).update_uijson(diagname="Visualsierung Astronomie",
                                    lang=None)

        print ('\n'.join(m for m in self.caplog.messages))

        updoutfile=self.debugpath / f"{outfilepath.stem}-ui_upd.json"
        self.dumpjson(updoutfile, newuijson)
        print('\n', updoutfile, " written")

        # self.assert...

        return

if __name__ == '__main__':
    unittest.main()
