confluence:
  apiurl: 'https://foryouandyourteam.com'
  space: '~bue'
  rootpage : 'Meta Information Information Model (MIIM) Sandbox'
  username: bue
  password: '***'

# datasource
json: testdata/IM-sample.json

# translations to publish
# first language listed here is not placed in a language subfolder
# and titles will not be suffixed
languages:
  - 'de'
  - 'en'

# output structure
content:
  entities:
    title: Entitäten
    template: entity.templ.html
    labels:
      - entity
      - IM
      - generated

  attributes:
    title: Attribute
    template: attribute.templ.html
    labels:
      - attribute
      - IM
      - generated
