-- Generiert von Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   am/um:        2021-11-01 16:24:21 MEZ
--   Site:      SQL Server 2012
--   Typ:      SQL Server 2012



CREATE TABLE ARCS 
    (
     ARCS_ID NUMERIC (28) NOT NULL , 
     ARCS_NAME VARCHAR (60) NOT NULL , 
     ARCS_ENTI_ID NUMERIC (10) NOT NULL , 
     ARCS_UC VARCHAR (30) NOT NULL , 
     ARCS_DC DATETIME (8) NOT NULL , 
     ARCS_UM VARCHAR (30) , 
     ARCS_DM DATETIME (8) 
    )
GO

ALTER TABLE ARCS ADD CONSTRAINT ARCS_PK PRIMARY KEY CLUSTERED (ARCS_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ARCS ADD CONSTRAINT ARCS_UK UNIQUE NONCLUSTERED (ARCS_ENTI_ID, ARCS_NAME)
GO

CREATE TABLE ATTRIBUTES 
    (
     ATTR_ID NUMERIC (28) NOT NULL , 
     ATTR_TECH_NAME VARCHAR (60) NOT NULL , 
     ATTR_DISPL_NAME VARCHAR (100) , 
     ATTR_DISPL_SEQ NUMERIC (5) , 
     ATTR_DESCR VARCHAR (4000) , 
     ATTR_TOOLTIP VARCHAR (4000) , 
     ATTR_IS_MANDATORY VARCHAR (5) NOT NULL , 
     ATTR_IS_DESCRIPTIVE VARCHAR (5) NOT NULL , 
     ATTR_IS_REPEATED VARCHAR (5) NOT NULL , 
     ATTR_IS_TRANSLATED VARCHAR (5) NOT NULL , 
     ATTR_IS_HISTORICISED VARCHAR (5) NOT NULL , 
     ATTR_IS_ENCRYPTED VARCHAR (5) NOT NULL , 
     ATTR_ENTI_ID NUMERIC (10) NOT NULL , 
     ATTR_DOMA_ID NUMERIC (10) NOT NULL , 
     ATTR_UC VARCHAR (30) NOT NULL , 
     ATTR_DC DATETIME NOT NULL , 
     ATTR_UM VARCHAR (30) , 
     ATTR_DM DATETIME 
    )
GO

ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_PK PRIMARY KEY CLUSTERED (ATTR_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTR_UK UNIQUE NONCLUSTERED (ATTR_TECH_NAME, ATTR_ENTI_ID)
GO
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTR_UK2 UNIQUE NONCLUSTERED (ATTR_DISPL_NAME, ATTR_ENTI_ID)
GO

CREATE TABLE BUSINESS_RULES 
    (
     BURU_ID NUMERIC (10) NOT NULL , 
     BURU_NAME VARCHAR (60) NOT NULL , 
     BURU_RULE VARCHAR (4000) NOT NULL , 
     BURU_DESCR VARCHAR (4000) , 
     BURU_IMPACT VARCHAR (4000) , 
     BURU_TYPE VARCHAR (10) NOT NULL , 
     BURU_LEVEL VARCHAR (4) NOT NULL , 
     BURU_ERRORMSG VARCHAR (4000) , 
     BURU_UC VARCHAR (30) NOT NULL , 
     BURU_DC DATETIME NOT NULL , 
     BURU_UM VARCHAR (30) , 
     BURU_DM DATETIME 
    )
GO 


ALTER TABLE BUSINESS_RULES 
    ADD 
    CHECK ( BURU_TYPE IN ('CALC', 'CHECK', 'TRIGGER') ) 
GO


ALTER TABLE BUSINESS_RULES 
    ADD CONSTRAINT CK__BUSINESS___BURU___1387E197 
    CHECK ( [BURU_LEVEL]='TUPL' OR [BURU_LEVEL]='ENTI' OR [BURU_LEVEL]='DB' OR [BURU_LEVEL]='ATTR' ) 
GO

ALTER TABLE BUSINESS_RULES ADD CONSTRAINT BUSINESS_RULES_PK PRIMARY KEY CLUSTERED (BURU_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE BUSINESS_RULES ADD CONSTRAINT BUSINESS_RULES_BURU_NAME_UN UNIQUE NONCLUSTERED (BURU_NAME)
GO

CREATE TABLE BUSINESSRULE_ELEMENTS 
    (
     BURE_ID NUMERIC (28) NOT NULL , 
     BURE_BURU_ID NUMERIC (28) NOT NULL , 
     BURE_MODE_ID NUMERIC (28) NOT NULL , 
     BURE_WRITEABLE VARCHAR (5) NOT NULL , 
     BURE_ROLE VARCHAR (4) , 
     BURE_UC VARCHAR (30) NOT NULL , 
     BURE_DC DATETIME (8) NOT NULL , 
     BURE_UM VARCHAR (30) , 
     BURE_DM DATETIME (8) 
    )
GO 


ALTER TABLE BUSINESSRULE_ELEMENTS 
    ADD CONSTRAINT CK__BUSINESSR__BURE___10216507 
    CHECK ( [BURE_WRITEABLE]='TRUE' OR [BURE_WRITEABLE]='FALSE' ) 
GO

ALTER TABLE BUSINESSRULE_ELEMENTS 
    ADD CONSTRAINT CK__BUSINESSR__BURE___10216507 
    CHECK ( BURE_ROLE IN ('AFCT', 'REF') ) 
GO

ALTER TABLE BUSINESSRULE_ELEMENTS ADD CONSTRAINT BURE_PK PRIMARY KEY CLUSTERED (BURE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE BUSINESSRULE_ELEMENTS ADD CONSTRAINT BURE_UK UNIQUE NONCLUSTERED (BURE_MODE_ID, BURE_BURU_ID)
GO

CREATE TABLE COLU_ATTR_MAP 
    (
     coam_id INTEGER NOT NULL , 
     coam_seq INTEGER NOT NULL , 
     coam_direction VARCHAR (7) NOT NULL , 
     coam_colu_id NUMERIC (10) NOT NULL , 
     coam_attr_id NUMERIC (10) NOT NULL , 
     coam_transf_rule VARCHAR (4000) , 
     coam_triggertype VARCHAR (10) , 
     coam_triggerperiod INTEGER 
    )
GO 


ALTER TABLE COLU_ATTR_MAP 
    ADD CONSTRAINT seq_chk 
    CHECK ( coam_seq > 0 ) 
GO


ALTER TABLE COLU_ATTR_MAP 
    ADD CONSTRAINT CK__COLU_ATTR__coam___13F1F5EB 
    CHECK ( [coam_direction]='OUTBOUND' OR [coam_direction]='INBOUND' ) 
GO


ALTER TABLE COLU_ATTR_MAP 
    ADD CONSTRAINT CK__COLU_ATTR__coam___14E61A24 
    CHECK ( [coam_triggertype]='ZPKT' OR [coam_triggertype]='PERIODE' OR [coam_triggertype]='MANUELL' ) 
GO

ALTER TABLE COLU_ATTR_MAP ADD CONSTRAINT colu_attr_map_PK PRIMARY KEY CLUSTERED (coam_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE COLU_ATTR_MAP ADD CONSTRAINT coam_un UNIQUE NONCLUSTERED (coam_direction, coam_colu_id, coam_attr_id, coam_seq)
GO

CREATE TABLE COLUMNS 
    (
     COLU_ID NUMERIC (28) NOT NULL , 
     COLU_COLUMN_NAME VARCHAR (60) NOT NULL , 
     COLU_MANDATORY VARCHAR (5) NOT NULL , 
     COLU_FORMAT VARCHAR (4000) , 
     COLU_DESCR VARCHAR (4000) , 
     COLU_EXT_SYSTEM_ID VARCHAR (100) , 
     COLU_TYPE_STRING VARCHAR (10) NOT NULL , 
     COLU_READ VARCHAR (5) NOT NULL DEFAULT 'TRUE' , 
     COLU_UPDATE VARCHAR (5) NOT NULL DEFAULT 'FALSE' , 
     COLU_TABL_ID NUMERIC (10) NOT NULL , 
     COLU_DOMA_ID NUMERIC (10) NOT NULL , 
     COLU_UC VARCHAR (30) NOT NULL , 
     COLU_DC DATETIME (8) NOT NULL , 
     COLU_UM VARCHAR (30) , 
     COLU_DM DATETIME (8) 
    )
GO 


ALTER TABLE COLUMNS 
    ADD 
    CHECK ( COLU_MANDATORY IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE COLUMNS 
    ADD 
    CHECK ( COLU_READ IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE COLUMNS 
    ADD 
    CHECK ( COLU_UPDATE IN ('FALSE', 'TRUE') ) 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'ID / Code der Attributbdefinition in einer Standardsoftware' , 'USER' , 'dbo' , 'TABLE' , 'COLUMNS' , 'COLUMN' , 'COLU_EXT_SYSTEM_ID' 
GO

ALTER TABLE COLUMNS ADD CONSTRAINT COLUMNS_PK PRIMARY KEY CLUSTERED (COLU_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE COLUMNS ADD CONSTRAINT COLU_UK UNIQUE NONCLUSTERED (COLU_TABL_ID, COLU_COLUMN_NAME)
GO

CREATE TABLE DATATYPES 
    (
     DATY_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     DATY_NAME VARCHAR (60) NOT NULL , 
     DATY_BASETYPE VARCHAR (60) NOT NULL , 
     DATY_UC VARCHAR (30) NOT NULL , 
     DATY_DC DATETIME (8) NOT NULL , 
     DATY_UM VARCHAR (30) , 
     DATY_DM DATETIME (8) 
    )
GO 


ALTER TABLE DATATYPES 
    ADD CONSTRAINT DATY_BASETYPE_CK 
    CHECK ( [DATY_BASETYPE]='STRING' OR [DATY_BASETYPE]='NUMERIC' OR [DATY_BASETYPE]='DATETIME' OR [DATY_BASETYPE]='BINARY' ) 
GO

ALTER TABLE DATATYPES ADD CONSTRAINT DATY_PK PRIMARY KEY CLUSTERED (DATY_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DATATYPES ADD CONSTRAINT DATY_UN UNIQUE NONCLUSTERED (DATY_NAME)
GO

CREATE TABLE DEFAULT_VALUES 
    (
     DEVA_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     DEVA_DOMA_ID NUMERIC (10) NOT NULL , 
     DEVA_VALUE VARCHAR (100) NOT NULL , 
     DEVA_SORT_ORDER NUMERIC (3) , 
     DEVA_DISPL VARCHAR (max) , 
     DEVA_DESCR VARCHAR (max) , 
     DEVA_UC VARCHAR (30) NOT NULL , 
     DEVA_DC DATETIME (8) NOT NULL , 
     DEVA_UM VARCHAR (30) , 
     DEVA_DM DATETIME (8) 
    )
GO

ALTER TABLE DEFAULT_VALUES ADD CONSTRAINT DEVA_PK PRIMARY KEY CLUSTERED (DEVA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DEFAULT_VALUES ADD CONSTRAINT DEVA_VGWT_UK UNIQUE NONCLUSTERED (DEVA_DOMA_ID, DEVA_VALUE)
GO

CREATE TABLE DIAGRAMS 
    (
     DIAG_ID NUMERIC (10) NOT NULL , 
     DIAG_NAME VARCHAR (60) NOT NULL , 
     DIAG_LEGENDY NUMERIC (8) , 
     DIAG_LEGENDX NUMERIC (8) , 
     DIAG_DIAT_ID NUMERIC (10) NOT NULL , 
     DIAG_UC VARCHAR (30) NOT NULL , 
     DIAG_DC DATETIME (8) NOT NULL , 
     DIAG_UM VARCHAR (30) , 
     DIAG_DM DATETIME (8) 
    )
GO

ALTER TABLE DIAGRAMS ADD CONSTRAINT DIAGRAMS_PK PRIMARY KEY CLUSTERED (DIAG_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DIAGRAMS ADD CONSTRAINT DIAG_UN UNIQUE NONCLUSTERED (DIAG_NAME)
GO

CREATE TABLE DIAGRAMTYPES 
    (
     DIAT_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     DIAT_NAME VARCHAR (100) NOT NULL , 
     DIAT_UC VARCHAR (30) NOT NULL , 
     DIAT_DC DATETIME (8) NOT NULL , 
     DIAT_UM VARCHAR (30) , 
     DIAT_DM DATETIME (8) 
    )
GO

ALTER TABLE DIAGRAMTYPES ADD CONSTRAINT DIAT_PK PRIMARY KEY CLUSTERED (DIAT_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DIAGRAMTYPES ADD CONSTRAINT DIAT__UN UNIQUE NONCLUSTERED (DIAT_NAME)
GO

CREATE TABLE DOCUMENTS 
    (
     DOCU_ID NUMERIC (28) NOT NULL , 
     DOCU_NAME VARCHAR (60) NOT NULL , 
     DOCU_REFERENCE VARCHAR (500) , 
     DOCU_CONTENT IMAGE , 
     DOCU_STFO_ID NUMERIC (10) , 
     DOCU_DOCU_ID NUMERIC (10) 
    )
GO

ALTER TABLE DOCUMENTS ADD CONSTRAINT DOCUMENTS_PK PRIMARY KEY CLUSTERED (DOCU_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DOCUMENTS ADD CONSTRAINT DOCUMENTS_DOCU_ID_UN UNIQUE NONCLUSTERED (DOCU_ID)
GO
ALTER TABLE DOCUMENTS ADD CONSTRAINT DOCU_UK UNIQUE NONCLUSTERED (DOCU_NAME)
GO

CREATE TABLE DOMAINGROUP_MEMBERS 
    (
     DGRM_ID NUMERIC (28) NOT NULL , 
     DGRM_NAME VARCHAR (60) NOT NULL , 
     DGRM_DESCR VARCHAR (4000) , 
     DGRM_IS_MANDATORY VARCHAR (5) NOT NULL , 
     DGRM_DOMA_ID_GROUP NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     DGRM_DOMA_ID_MEMBER NUMERIC (10) NOT NULL , 
     DGRM_UC VARCHAR (30) NOT NULL , 
     DGRM_DC DATETIME (8) NOT NULL , 
     DGRM_UM VARCHAR (30) , 
     DGRM_DM DATETIME (8) 
    )
GO 


ALTER TABLE DOMAINGROUP_MEMBERS 
    ADD CONSTRAINT CK__DOMAINGRO__DGRM___29E1370A 
    CHECK ( [DGRM_IS_MANDATORY]='TRUE' OR [DGRM_IS_MANDATORY]='FALSE' ) 
GO

ALTER TABLE DOMAINGROUP_MEMBERS ADD CONSTRAINT DGRM_PK PRIMARY KEY CLUSTERED (DGRM_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DOMAINGROUP_MEMBERS ADD CONSTRAINT DGRM_DOMA_UK UNIQUE NONCLUSTERED (DGRM_DOMA_ID_GROUP, DGRM_NAME)
GO

CREATE TABLE DOMAINS 
    (
     DOMA_ID NUMERIC (28) NOT NULL , 
     DOMA_NAME VARCHAR (60) NOT NULL , 
     DOMA_DESCR VARCHAR (4000) , 
     DOMA_TYPE VARCHAR (4) NOT NULL , 
     DOMA_ORIGIN VARCHAR (6) NOT NULL , 
     DOMA_INTF_ID NUMERIC (10) , 
     DOMA_DATY_ID NUMERIC (10) , 
     DOMA_DAT_MINVALUE DATETIME , 
     DOMA_DAT_MAXVALUE DATETIME , 
     DOMA_DAT_GRANULARITY VARCHAR (15) NOT NULL , 
     DOMA_TXT_MAXLNG NUMERIC (6) NOT NULL , 
     DOMA_TXT_SYNTAXRULE VARCHAR (4000) , 
     DOMA_NUM_MAXVALUE NUMERIC (28) , 
     DOMA_NUM_MINVALUE NUMERIC (28) , 
     DOMA_NUM_TOTAL_DIGITS NUMERIC (2) NOT NULL , 
     DOMA_NUM_FRACT_DIGITS NUMERIC (2) NOT NULL , 
     DOMA_NUM_ROUND_VALUE NUMERIC (7,3) DEFAULT 1 , 
     DOMA_NUM_PHYU_ID NUMERIC (10) , 
     DOMA_BIN_CONTENTTYPE VARCHAR (30) NOT NULL , 
     DOMA_BIN_STFO_ID NUMERIC (10) , 
     DOMA_UC VARCHAR (30) NOT NULL , 
     DOMA_DC DATETIME (8) NOT NULL , 
     DOMA_UM VARCHAR (30) , 
     DOMA_DM DATETIME (8) 
    )
GO 


ALTER TABLE DOMAINS 
    ADD CONSTRAINT CK__DOMAINS__DOMA_TY__2DB1C7EE 
    CHECK ( [DOMA_TYPE]='TXT' OR [DOMA_TYPE]='NUM' OR [DOMA_TYPE]='LOV' OR [DOMA_TYPE]='GRP' OR [DOMA_TYPE]='DAT' OR [DOMA_TYPE]='BIN' ) 
GO


ALTER TABLE DOMAINS 
    ADD CONSTRAINT CK__DOMAINS__DOMA_OR__2EA5EC27 
    CHECK ( [DOMA_ORIGIN]='DOM' OR [DOMA_ORIGIN]='DER' ) 
GO

ALTER TABLE DOMAINS ADD CONSTRAINT DOMAINS_PK PRIMARY KEY CLUSTERED (DOMA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_UK UNIQUE NONCLUSTERED (DOMA_NAME)
GO

ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_ExDep1 CHECK ( [DOMA_TYPE]<>'BIN' OR [DOMA_BIN_CONTENTTYPE] IS NOT NULL AND [DOMA_NUM_FRACT_DIGITS] IS NULL AND [DOMA_NUM_MAXVALUE] IS NULL AND [DOMA_NUM_MINVALUE] IS NULL AND [DOMA_NUM_PHYU_ID] IS NULL AND [DOMA_NUM_ROUND_VALUE] IS NULL AND [DOMA_NUM_TOTAL_DIGITS] IS NULL AND [DOMA_DAT_GRANULARITY] IS NULL AND [DOMA_DAT_MAXVALUE] IS NULL AND [DOMA_DAT_MINVALUE] IS NULL AND [DOMA_TXT_SYNTAXRULE] IS NULL AND [DOMA_TXT_MAXLNG] IS NULL ) 
GO


ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_ExDep2 CHECK ( [DOMA_TYPE]<>'DAT' OR [DOMA_BIN_CONTENTTYPE] IS NULL AND [DOMA_BIN_STFO_ID] IS NULL AND [DOMA_NUM_FRACT_DIGITS] IS NULL AND [DOMA_NUM_MAXVALUE] IS NULL AND [DOMA_NUM_MINVALUE] IS NULL AND [DOMA_NUM_PHYU_ID] IS NULL AND [DOMA_NUM_ROUND_VALUE] IS NULL AND [DOMA_NUM_TOTAL_DIGITS] IS NULL AND [DOMA_DAT_GRANULARITY] IS NOT NULL AND [DOMA_TXT_SYNTAXRULE] IS NULL AND [DOMA_TXT_MAXLNG] IS NULL ) 
GO


ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_ExDep3 CHECK ( [DOMA_TYPE]<>'GRP' OR [DOMA_BIN_CONTENTTYPE] IS NULL AND [DOMA_BIN_STFO_ID] IS NULL AND [DOMA_NUM_FRACT_DIGITS] IS NULL AND [DOMA_NUM_MAXVALUE] IS NULL AND [DOMA_NUM_MINVALUE] IS NULL AND [DOMA_NUM_PHYU_ID] IS NULL AND [DOMA_NUM_ROUND_VALUE] IS NULL AND [DOMA_NUM_TOTAL_DIGITS] IS NULL AND [DOMA_DAT_GRANULARITY] IS NULL AND [DOMA_DAT_MAXVALUE] IS NULL AND [DOMA_DAT_MINVALUE] IS NULL AND [DOMA_TXT_SYNTAXRULE] IS NULL AND [DOMA_TXT_MAXLNG] IS NULL ) 
GO


ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_ExDep4 CHECK ( [DOMA_TYPE]<>'LOV' OR [DOMA_BIN_CONTENTTYPE] IS NULL AND [DOMA_BIN_STFO_ID] IS NULL AND [DOMA_NUM_FRACT_DIGITS] IS NULL AND [DOMA_NUM_MAXVALUE] IS NULL AND [DOMA_NUM_MINVALUE] IS NULL AND [DOMA_NUM_PHYU_ID] IS NULL AND [DOMA_NUM_ROUND_VALUE] IS NULL AND [DOMA_NUM_TOTAL_DIGITS] IS NULL AND [DOMA_DAT_GRANULARITY] IS NULL AND [DOMA_DAT_MAXVALUE] IS NULL AND [DOMA_DAT_MINVALUE] IS NULL AND [DOMA_TXT_SYNTAXRULE] IS NULL AND [DOMA_TXT_MAXLNG] IS NULL ) 
GO


ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_ExDep5 CHECK ( [DOMA_TYPE]<>'NUM' OR [DOMA_BIN_CONTENTTYPE] IS NULL AND [DOMA_BIN_STFO_ID] IS NULL AND [DOMA_NUM_FRACT_DIGITS] IS NOT NULL AND [DOMA_NUM_TOTAL_DIGITS] IS NOT NULL AND [DOMA_DAT_GRANULARITY] IS NULL AND [DOMA_DAT_MAXVALUE] IS NULL AND [DOMA_DAT_MINVALUE] IS NULL AND [DOMA_TXT_SYNTAXRULE] IS NULL AND [DOMA_TXT_MAXLNG] IS NULL ) 
GO


ALTER TABLE DOMAINS ADD CONSTRAINT DOMA_ExDep6 CHECK ( [DOMA_TYPE]<>'TXT' OR [DOMA_BIN_CONTENTTYPE] IS NULL AND [DOMA_BIN_STFO_ID] IS NULL AND [DOMA_NUM_FRACT_DIGITS] IS NULL AND [DOMA_NUM_MAXVALUE] IS NULL AND [DOMA_NUM_MINVALUE] IS NULL AND [DOMA_NUM_PHYU_ID] IS NULL AND [DOMA_NUM_ROUND_VALUE] IS NULL AND [DOMA_NUM_TOTAL_DIGITS] IS NULL AND [DOMA_DAT_GRANULARITY] IS NULL AND [DOMA_DAT_MAXVALUE] IS NULL AND [DOMA_DAT_MINVALUE] IS NULL ) 
GO

CREATE TABLE ELEMENT_UI 
    (
     ELUI_ID NUMERIC (10) NOT NULL , 
     ELUI_MELT_ID NUMERIC (28) , 
     ELUI_ENCA_ID NUMERIC (10) , 
     ELUI_WIDTH NUMERIC (4) , 
     ELUI_HEIGHT NUMERIC (4) , 
     ELUI_OPACITY NUMERIC (3) DEFAULT (100) , 
     ELUI_COLOR VARCHAR (6) DEFAULT '000000' , 
     ELUI_MARGINWIDTH NUMERIC (3,1) DEFAULT (1) , 
     ELUI_MARGINOPACITY NUMERIC (3) DEFAULT (100) , 
     ELUI_MARGINCOLOR VARCHAR (6) DEFAULT '000000' , 
     ELUI_FONTSIZE NUMERIC (3) , 
     ELUI_FONTCOLOR VARCHAR (6) DEFAULT '000000' 
    )
GO 


ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___3CF40B7E 
    CHECK ( [ELUI_OPACITY]>=(0) AND [ELUI_OPACITY]<=(100) ) 
GO


ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___3EDC53F0 
    CHECK ( datalength({column}) = 6 ) 
GO


ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___41B8C09B 
    CHECK ( [ELUI_MARGINOPACITY]>=(0) AND [ELUI_MARGINOPACITY]<=(100) ) 
GO


ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___43A1090D 
    CHECK ( datalength({column}) = 6 ) 
GO


ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___44952D46 
    CHECK ( [ELUI_FONTSIZE]>=(1) AND [ELUI_FONTSIZE]<=(999) ) 
GO


ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___467D75B8 
    CHECK ( datalength({column}) = 6 ) 
GO
ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT FKArc_3 CHECK ( 
        (  (ELUI_MELT_ID IS NOT NULL) AND 
         (ELUI_ENCA_ID IS NULL) ) OR 
        (  (ELUI_ENCA_ID IS NOT NULL) AND 
         (ELUI_MELT_ID IS NULL) )  ) 
;



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Darstellung des Randes um das Element' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENT_UI' , 'COLUMN' , 'ELUI_WIDTH' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Darstellung des Randes um das Element' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENT_UI' , 'COLUMN' , 'ELUI_HEIGHT' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Darstellung des Randes um das Element' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENT_UI' , 'COLUMN' , 'ELUI_MARGINWIDTH' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Schriftgrösse des Elementsnamens' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENT_UI' , 'COLUMN' , 'ELUI_FONTSIZE' 
GO

ALTER TABLE ELEMENT_UI ADD CONSTRAINT ELUI_PK PRIMARY KEY CLUSTERED (ELUI_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ELEMENT_UI ADD CONSTRAINT ELUI_UK_melt UNIQUE NONCLUSTERED (ELUI_MELT_ID)
GO
ALTER TABLE ELEMENT_UI ADD CONSTRAINT ELUI_UK_ENCA UNIQUE NONCLUSTERED (ELUI_ENCA_ID)
GO

CREATE TABLE ELEMENTREPS 
    (
     ELER_ID NUMERIC (10) NOT NULL , 
     ELER_MODE_ID NUMERIC (10) NOT NULL , 
     ELER_DIAG_ID NUMERIC (10) NOT NULL , 
     ELER_INDEX NUMERIC (4) NOT NULL DEFAULT (0) , 
     ELER_POSITION_X NUMERIC (6) , 
     ELER_POSITION_Y NUMERIC (6) , 
     ELER_WIDTH NUMERIC (4) NOT NULL , 
     ELER_HEIGHT NUMERIC (4) NOT NULL , 
     ELER_OPACITY NUMERIC (3) DEFAULT (100) , 
     ELER_COLOR VARCHAR (6) NOT NULL DEFAULT '000000' , 
     ELER_MARGINWIDTH NUMERIC (3,1) DEFAULT (1) , 
     ELER_MARGINOPACITY NUMERIC (3) DEFAULT (100) , 
     ELER_MARGINCOLOR VARCHAR (6) DEFAULT '000000' , 
     ELER_FONTSIZE NUMERIC (3) , 
     ELER_FONTCOLOR VARCHAR (6) DEFAULT '000000' , 
     ELER_UC VARCHAR (30) NOT NULL , 
     ELER_DC DATETIME (8) NOT NULL , 
     ELER_UM VARCHAR (30) , 
     ELER_DM DATETIME (8) 
    )
GO 


ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___3CF40B7E 
    CHECK ( [ELER_OPACITY]>=(0) AND [ELER_OPACITY]<=(100) ) 
GO


ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___3EDC53F0 
    CHECK ( datalength([ELER_COLOR])=(6) ) 
GO


ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___41B8C09B 
    CHECK ( [ELER_MARGINOPACITY]>=(0) AND [ELER_MARGINOPACITY]<=(100) ) 
GO


ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___43A1090D 
    CHECK ( datalength([ELER_MARGINCOLOR])=(6) ) 
GO


ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___44952D46 
    CHECK ( [ELER_FONTSIZE]>=(1) AND [ELER_FONTSIZE]<=(999) ) 
GO


ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT CK__ELEMENTRE__ELER___467D75B8 
    CHECK ( datalength([ELER_FONTCOLOR])=(6) ) 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert einer Darstellung eines Elementtyps' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENTREPS' , 'COLUMN' , 'ELER_POSITION_X' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert einer Darstellung eines Elementtyps' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENTREPS' , 'COLUMN' , 'ELER_POSITION_Y' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Darstellung des Randes um das Element' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENTREPS' , 'COLUMN' , 'ELER_WIDTH' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Darstellung des Randes um das Element' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENTREPS' , 'COLUMN' , 'ELER_HEIGHT' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Darstellung des Randes um das Element' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENTREPS' , 'COLUMN' , 'ELER_MARGINWIDTH' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Vorgabewert der Schriftgrösse des Elementsnamens' , 'USER' , 'dbo' , 'TABLE' , 'ELEMENTREPS' , 'COLUMN' , 'ELER_FONTSIZE' 
GO

ALTER TABLE ELEMENTREPS ADD CONSTRAINT ELER_Elemendarstellung_PK PRIMARY KEY CLUSTERED (ELER_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ELEMENTREPS ADD CONSTRAINT ELER__UN UNIQUE NONCLUSTERED (ELER_MODE_ID, ELER_DIAG_ID, ELER_INDEX)
GO

CREATE TABLE ENTITIES 
    (
     ENTI_ID NUMERIC (28) NOT NULL , 
     ENTI_NAME VARCHAR (60) NOT NULL , 
     ENTI_ENCA_ID NUMERIC (10) , 
     ENTI_UNDERLAY_ENTI_ID NUMERIC (10),
     ENTI_DESCR VARCHAR (4000) , 
     ENTI_SHORTNAME VARCHAR (60) , 
     ENTI_PREFIX VARCHAR (60) , 
     ENTI_TOOLTIP VARCHAR (4000) , 
     ENTI_EXP_TUPLECNT VARCHAR (100) , 
     ENTI_UC VARCHAR (30) NOT NULL , 
     ENTI_DC DATETIME (8) NOT NULL , 
     ENTI_UM VARCHAR (30) , 
     ENTI_DM DATETIME 
    )
GO

ALTER TABLE ENTITIES ADD CONSTRAINT ENTITIES_PK PRIMARY KEY CLUSTERED (ENTI_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ENTITIES ADD CONSTRAINT ENTI_NAME_UK UNIQUE NONCLUSTERED (ENTI_NAME)
GO

CREATE TABLE ENTITY_CATEGORIES 
    (
     ENCA_ID NUMERIC (10) NOT NULL , 
     ENCA_NAME VARCHAR (60) NOT NULL , 
     ENCA_UC VARCHAR (30) NOT NULL , 
     ENCA_DC DATETIME NOT NULL , 
     ENCA_UM VARCHAR (30) , 
     ENCA_DM DATETIME 
    )
GO

ALTER TABLE ENTITY_CATEGORIES ADD CONSTRAINT ENCA_PK PRIMARY KEY CLUSTERED (ENCA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ENTITY_CATEGORIES ADD CONSTRAINT ENCA_UK UNIQUE NONCLUSTERED (ENCA_NAME)
GO

CREATE TABLE EXAMPLE 
    (
     EXPL_ID NUMERIC (28) NOT NULL , 
     EXPL_VALUE VARCHAR (4000) NOT NULL , 
     EXPL_ENTI_ID NUMERIC (10) , 
     EXPL_ATTR_ID NUMERIC (10) , 
     EXPL_UC VARCHAR (30) NOT NULL , 
     EXPL_DC DATETIME NOT NULL , 
     EXPL_UM VARCHAR (30) , 
     EXPL_DM DATETIME 
    )
GO 
ALTER TABLE EXAMPLE 
    ADD CONSTRAINT FKArc_8 CHECK ( 
        (  (EXPL_ENTI_ID IS NOT NULL) AND 
         (EXPL_ATTR_ID IS NULL) ) OR 
        (  (EXPL_ATTR_ID IS NOT NULL) AND 
         (EXPL_ENTI_ID IS NULL) )  ) 
;

ALTER TABLE EXAMPLE ADD CONSTRAINT EXAMPLE_PK PRIMARY KEY CLUSTERED (EXPL_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE EXAMPLE ADD CONSTRAINT EXPL_ENTI_UK UNIQUE NONCLUSTERED (EXPL_VALUE, EXPL_ENTI_ID)
GO
ALTER TABLE EXAMPLE ADD CONSTRAINT EXPL_ATTR_UK UNIQUE NONCLUSTERED (EXPL_VALUE, EXPL_ATTR_ID)
GO

CREATE TABLE EXTERNAL_REFS 
    (
     EXTR_ID NUMERIC (10) NOT NULL , 
     EXTR_SOURCE_NAME VARCHAR (60) NOT NULL , 
     EXTR_SOURCE_ID VARCHAR (100) NOT NULL , 
     EXTR_MODE_ID NUMERIC (10) NOT NULL , 
     EXTR_LAST_UPDATE DATETIME NOT NULL 
    )
GO

ALTER TABLE EXTERNAL_REFS ADD CONSTRAINT EXTR_PK PRIMARY KEY CLUSTERED (EXTR_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE EXTERNAL_REFS ADD CONSTRAINT EXTR_UK UNIQUE NONCLUSTERED (EXTR_SOURCE_NAME, EXTR_MODE_ID)
GO
ALTER TABLE EXTERNAL_REFS ADD CONSTRAINT Extr_UK_id UNIQUE NONCLUSTERED (EXTR_SOURCE_NAME, EXTR_SOURCE_ID)
GO

CREATE TABLE INTERFACES 
    (
     INTF_ID NUMERIC (28) NOT NULL , 
     INTF_NAME VARCHAR (60) NOT NULL , 
     INTF_DESCR VARCHAR (4000) , 
     INTF_UC VARCHAR (30) NOT NULL , 
     INTF_DC DATETIME (8) NOT NULL , 
     INTF_UM VARCHAR (30) , 
     INTF_DM DATETIME (8) 
    )
GO

ALTER TABLE INTERFACES ADD CONSTRAINT INTF_PK PRIMARY KEY CLUSTERED (INTF_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE INTERFACES ADD CONSTRAINT SCHN_UN UNIQUE NONCLUSTERED (INTF_NAME)
GO

CREATE TABLE KEY_ELEMENTS 
    (
     KELE_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     KELE_KEYS_ID NUMERIC (28) NOT NULL , 
     KELE_ATTR_ID NUMERIC (10) , 
     KELE_RELA_ID NUMERIC (10) , 
     KELE_UC VARCHAR (30) NOT NULL , 
     KELE_DC DATETIME (8) NOT NULL , 
     KELE_UM VARCHAR (30) , 
     KELE_DM DATETIME (8) 
    )
GO 
ALTER TABLE KEY_ELEMENTS 
    ADD CONSTRAINT FKArc_7 CHECK ( 
        (  (KELE_RELA_ID IS NOT NULL) AND 
         (KELE_ATTR_ID IS NULL) ) OR 
        (  (KELE_ATTR_ID IS NOT NULL) AND 
         (KELE_RELA_ID IS NULL) )  ) 
;

ALTER TABLE KEY_ELEMENTS ADD CONSTRAINT KELE_PK PRIMARY KEY CLUSTERED (KELE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE KEY_ELEMENTS ADD CONSTRAINT KELE_KEYS_UK UNIQUE NONCLUSTERED (KELE_KEYS_ID, KELE_ATTR_ID)
GO
ALTER TABLE KEY_ELEMENTS ADD CONSTRAINT KELE_RELA_UK UNIQUE NONCLUSTERED (KELE_KEYS_ID, KELE_RELA_ID)
GO

ALTER TABLE KEY_ELEMENTS ADD CONSTRAINT FKArc_8 CHECK ( [KELE_RELA_ID] IS NOT NULL AND [KELE_ATTR_ID] IS NULL OR [KELE_ATTR_ID] IS NOT NULL AND [KELE_RELA_ID] IS NULL ) 
GO

CREATE TABLE KEYS 
    (
     KEYS_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     KEYS_ENTI_ID NUMERIC (10) NOT NULL , 
     KEYS_NAME VARCHAR (100) NOT NULL , 
     KEYS_UC VARCHAR (30) NOT NULL , 
     KEYS_DC DATETIME NOT NULL , 
     KEYS_UM VARCHAR (30) , 
     KEYS_DM DATETIME 
    )
GO

ALTER TABLE KEYS ADD CONSTRAINT KEYS_PK PRIMARY KEY CLUSTERED (KEYS_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE KEYS ADD CONSTRAINT KEYS_UK UNIQUE NONCLUSTERED (KEYS_ENTI_ID, KEYS_NAME)
GO

CREATE TABLE LANG_TEXTS 
    (
     LGTX_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     LGTX_ATTRNAME VARCHAR (60) NOT NULL , 
     LGTX_TEXT VARCHAR (4000) , 
     LGTX_LANG_ID NUMERIC (10) NOT NULL , 
     LGTX_MODE_ID NUMERIC (10) NOT NULL , 
     LGTX_UC VARCHAR (30) NOT NULL , 
     LGTX_DC DATETIME (8) NOT NULL , 
     LGTX_UM VARCHAR (30) , 
     LGTX_DM DATETIME (8) 
    )
GO

ALTER TABLE LANG_TEXTS ADD CONSTRAINT LGTX_PK PRIMARY KEY CLUSTERED (LGTX_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE LANG_TEXTS ADD CONSTRAINT LGTX_UK UNIQUE NONCLUSTERED (LGTX_LANG_ID, LGTX_MODE_ID, LGTX_ATTRNAME)
GO

CREATE TABLE LANGUAGES 
    (
     LANG_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     LANG_ISO_NAME VARCHAR (60) , 
     LANG_ISO_CODE2 CHAR (2) NOT NULL , 
     LANG_ISO_CODE3 CHAR (3) NOT NULL , 
     LANG_IS_TEXT_LANG VARCHAR (5) NOT NULL , 
     LANG_IS_BASE_LANG VARCHAR (5) NOT NULL , 
     LANG_LANG_ID NUMERIC (10) , 
     LANG_UC VARCHAR (30) NOT NULL , 
     LANG_DC DATETIME (8) NOT NULL , 
     LANG_UM VARCHAR (30) , 
     LANG_DM DATETIME (8) 
    )
GO 


ALTER TABLE LANGUAGES 
    ADD CONSTRAINT LANG_ISO2_CHK 
    CHECK ( [LANG_ISO_CODE2]=lower([LANG_ISO_CODE2]) ) 
GO


ALTER TABLE LANGUAGES 
    ADD CONSTRAINT LANG_ISO3_CHK 
    CHECK ( [LANG_ISO_CODE3]=lower([LANG_ISO_CODE3]) ) 
GO


ALTER TABLE LANGUAGES 
    ADD CONSTRAINT CK__LANGUAGES__LANG___5C6CB6D7 
    CHECK ( [LANG_IS_TEXT_LANG]='TRUE' OR [LANG_IS_TEXT_LANG]='FALSE' ) 
GO


ALTER TABLE LANGUAGES 
    ADD CONSTRAINT CK__LANGUAGES__LANG___5D60DB10 
    CHECK ( [LANG_IS_BASE_LANG]='TRUE' OR [LANG_IS_BASE_LANG]='FALSE' ) 
GO

ALTER TABLE LANGUAGES ADD CONSTRAINT LANG_PK PRIMARY KEY CLUSTERED (LANG_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE LANGUAGES ADD CONSTRAINT LANG_ISO_NAME_UN UNIQUE NONCLUSTERED (LANG_ISO_NAME)
GO
ALTER TABLE LANGUAGES ADD CONSTRAINT LANG_ISO_CODE2_UN UNIQUE NONCLUSTERED (LANG_ISO_CODE2)
GO
ALTER TABLE LANGUAGES ADD CONSTRAINT LANG_ISO_CODE3_UN UNIQUE NONCLUSTERED (LANG_ISO_CODE3)
GO

CREATE TABLE LINESEGMENTS 
    (
     LISE_ID NUMERIC (10) NOT NULL , 
     LISE_SEQ NUMERIC (4) NOT NULL , 
     LISE_RELR_ID NUMERIC (10) NOT NULL , 
     LISE_X NUMERIC (6) NOT NULL , 
     LISE_Y NUMERIC (6) NOT NULL , 
     LISE_LINETYPE VARCHAR (6) DEFAULT 'SOLID' , 
     LISE_ANGLE NUMERIC (12,11) , 
     LISE_UC VARCHAR (30) NOT NULL , 
     LISE_DC DATETIME (8) NOT NULL , 
     LISE_UM VARCHAR (30) , 
     LISE_DM DATETIME (8) 
    )
GO 


ALTER TABLE LINESEGMENTS 
    ADD CONSTRAINT LISE_CK_X 
    CHECK ( [LISE_X]>=(0) AND [LISE_X]<=(999999) ) 
GO


ALTER TABLE LINESEGMENTS 
    ADD CONSTRAINT LISE_CK_Y 
    CHECK ( [LISE_Y]>=(0) AND [LISE_Y]<=(999999) ) 
GO


ALTER TABLE LINESEGMENTS 
    ADD CONSTRAINT LISE_CK_BEDA_BEDA_SCHRIFTGROESSE 
    CHECK ( [LISE_LINETYPE]='SOLID' OR [LISE_LINETYPE]='DOTTED' OR [LISE_LINETYPE]='DASHED' OR [LISE_LINETYPE]='DADO' ) 
GO

ALTER TABLE LINESEGMENTS ADD CONSTRAINT LISE_PK PRIMARY KEY CLUSTERED (LISE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE LINESEGMENTS ADD CONSTRAINT LISE__UN UNIQUE NONCLUSTERED (LISE_RELR_ID, LISE_SEQ)
GO

CREATE TABLE MELT_DIATS 
    (
     MEDI_ID NUMERIC (10) NOT NULL , 
     MEDI_DIAT_ID NUMERIC (10) NOT NULL , 
     MEDI_MELT_ID NUMERIC (10) NOT NULL , 
     MEDI_UC VARCHAR (30) NOT NULL , 
     MEDI_DC DATETIME (8) NOT NULL , 
     MEDI_UM VARCHAR (30) , 
     MEDI_DM DATETIME (8) 
    )
GO

ALTER TABLE MELT_DIATS ADD CONSTRAINT MEDI_PK PRIMARY KEY CLUSTERED (MEDI_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE MELT_DIATS ADD CONSTRAINT MEDI__UN UNIQUE NONCLUSTERED (MEDI_DIAT_ID, MEDI_MELT_ID)
GO

CREATE TABLE MODE_DOCU 
    (
     MODO_ID NUMERIC (10) NOT NULL , 
     MODO_MODE_ID NUMERIC (10) NOT NULL , 
     MODO_DOCU_ID NUMERIC (10) NOT NULL 
    )
GO

ALTER TABLE MODE_DOCU ADD CONSTRAINT MODO_PKv2 PRIMARY KEY CLUSTERED (MODO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE MODE_DOCU ADD CONSTRAINT MODO_UK UNIQUE NONCLUSTERED (MODO_MODE_ID, MODO_DOCU_ID)
GO

CREATE TABLE MODE_ORGU 
    (
     MOOU_ID NUMERIC (10) NOT NULL , 
     MOOU_MODE_ID NUMERIC (10) NOT NULL , 
     MOOU_ORGU_ID NUMERIC (10) NOT NULL 
    )
GO

ALTER TABLE MODE_ORGU ADD CONSTRAINT MOOU_PK PRIMARY KEY CLUSTERED (MOOU_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE MODE_ORGU ADD CONSTRAINT MOOU_UK UNIQUE NONCLUSTERED (MOOU_MODE_ID, MOOU_ORGU_ID)
GO

CREATE TABLE MODELELEM_TYPE 
    (
     MELT_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     MELT_SHORTNAME VARCHAR (4) NOT NULL , 
     MELT_NAME VARCHAR (60) NOT NULL , 
     MELT_UC VARCHAR (30) NOT NULL , 
     MELT_DC DATETIME (8) NOT NULL , 
     MELT_UM VARCHAR (30) , 
     MELT_DM DATETIME (8) 
    )
GO 


ALTER TABLE MODELELEM_TYPE 
    ADD CONSTRAINT CK__MODELELEM__MELT___725BF7F6 
    CHECK ( [MELT_SHORTNAME]='TABL' OR [MELT_SHORTNAME]='SYNO' OR [MELT_SHORTNAME]='RELA' OR [MELT_SHORTNAME]='ORGU' OR [MELT_SHORTNAME]='KEYS' OR [MELT_SHORTNAME]='INTF' OR [MELT_SHORTNAME]='ENTI' OR [MELT_SHORTNAME]='DOMA' OR [MELT_SHORTNAME]='DOCU' OR [MELT_SHORTNAME]='DIAG' OR [MELT_SHORTNAME]='DGRM' OR [MELT_SHORTNAME]='DATY' OR [MELT_SHORTNAME]='COLU' OR [MELT_SHORTNAME]='BURU' OR [MELT_SHORTNAME]='ATTR' OR [MELT_SHORTNAME]='ARCS' ) 
GO

ALTER TABLE MODELELEM_TYPE ADD CONSTRAINT MELT_PK PRIMARY KEY CLUSTERED (MELT_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE MODELELEM_TYPE ADD CONSTRAINT MELT_UN UNIQUE NONCLUSTERED (MELT_SHORTNAME)
GO
ALTER TABLE MODELELEM_TYPE ADD CONSTRAINT MELT_UN2 UNIQUE NONCLUSTERED (MELT_NAME)
GO

CREATE TABLE MODELELEMENT 
    (
     MODE_ID NUMERIC (10) NOT NULL , 
     MODE_TYPE VARCHAR (4) NOT NULL , 
     MODE_MELT_ID NUMERIC (28) NOT NULL , 
     MODE_MIN_ZOOM_LEVEL NUMERIC (1) , 
     MODE_MAX_ZOOM_LEVEL NUMERIC (1) , 
     MODE_PUBL_STATUS VARCHAR (5) 
 )

ALTER TABLE MODELELEMENT 
    ADD CONSTRAINT CK__MODELELEM__MODE___7720AD13 
    CHECK ( [MODE_TYPE]='TABL' OR [MODE_TYPE]='SYNO' OR [MODE_TYPE]='RELA' OR [MODE_TYPE]='ORGU' OR [MODE_TYPE]='KEYS' OR [MODE_TYPE]='INTF' OR [MODE_TYPE]='ENTI' OR [MODE_TYPE]='DOMA' OR [MODE_TYPE]='DOCU' OR [MODE_TYPE]='DIAG' OR [MODE_TYPE]='DGRM' OR [MODE_TYPE]='DATY' OR [MODE_TYPE]='COLU' OR [MODE_TYPE]='BURU' OR [MODE_TYPE]='ATTR' OR [MODE_TYPE]='ARCS' ) 
GO

ALTER TABLE MODELELEMENT 
    ADD 
    CHECK ( MODE_PUBL_STATUS IN ('DRAFT', 'GTOP', 'PUBL') ) 
GO

ALTER TABLE MODELELEMENT 
    ADD 
    CHECK ( MODE_MIN_ZOOM_LEVEL BETWEEN 0 AND 4 ) 
GO


ALTER TABLE MODELELEMENT 
    ADD 
    CHECK ( MODE_MAX_ZOOM_LEVEL BETWEEN 0 AND 4 ) 
GO


ALTER TABLE MODELELEMENT 
    ADD 
    CHECK ( MODE_DEV_STATUS IN ('DEV', 'REL', 'TEST') ) 
GO

ALTER TABLE MODELELEMENT ADD CONSTRAINT MODELELEMENT_PK PRIMARY KEY CLUSTERED (MODE_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE MODELELEMENT ADD CONSTRAINT MODELELEMENT_MODE_ID_UN UNIQUE NONCLUSTERED (MODE_ID)
GO

CREATE TABLE MODELEMTYPE_PROPERTIES 
    (
     METP_ID NUMERIC (10) NOT NULL , 
     METP_MELT_ID NUMERIC (10) NOT NULL , 
     METP_UDPR_ID NUMERIC (10) NOT NULL , 
     METP_OPTIONAL VARCHAR (5) NOT NULL 
    )
GO 


ALTER TABLE MODELEMTYPE_PROPERTIES 
    ADD CONSTRAINT CK__MODELEMTY__METP___79FD19BE 
    CHECK ( [METP_OPTIONAL]='TRUE' OR [METP_OPTIONAL]='FALSE' ) 
GO

ALTER TABLE MODELEMTYPE_PROPERTIES ADD CONSTRAINT METP_PK PRIMARY KEY CLUSTERED (METP_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE MODELEMTYPE_PROPERTIES ADD CONSTRAINT METP_UN UNIQUE NONCLUSTERED (METP_MELT_ID, METP_UDPR_ID)
GO

CREATE TABLE ORGANISATIONALUNITS 
    (
     ORGU_ID NUMERIC (10) NOT NULL , 
     ORGU_NAME VARCHAR (60) NOT NULL , 
     ORGU_DESCR VARCHAR (4000) , 
     ORGU_MAIL VARCHAR (200) , 
     ORGU_TELEFON VARCHAR (30) , 
     ORGU_ADDRESS VARCHAR (4000) , 
     ORGU_ORGU_ID NUMERIC (28) , 
     ORGU_UC VARCHAR (30) NOT NULL , 
     ORGU_DC DATETIME (8) NOT NULL , 
     ORGU_UM VARCHAR (30) , 
     ORGU_DM DATETIME (8) 
    )
GO

ALTER TABLE ORGANISATIONALUNITS ADD CONSTRAINT ORGU_PK PRIMARY KEY CLUSTERED (ORGU_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ORGANISATIONALUNITS ADD CONSTRAINT ORGU_NAME_UN UNIQUE NONCLUSTERED (ORGU_NAME)
GO

CREATE TABLE PHYSICAL_UNIT 
    (
     PHYU_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     PHYU_SI_UNIT VARCHAR (10) , 
     PHYU_NAME VARCHAR (60) NOT NULL , 
     PHYU_DESCR VARCHAR (4000) , 
     PHYU_UC VARCHAR (30) NOT NULL , 
     PHYU_DC DATETIME (8) NOT NULL , 
     PHYU_UM VARCHAR (30) , 
     PHYU_DM DATETIME (8) 
    )
GO

ALTER TABLE PHYSICAL_UNIT ADD CONSTRAINT PHYU_PK PRIMARY KEY CLUSTERED (PHYU_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE PHYSICAL_UNIT ADD CONSTRAINT PHYU_UK_SI UNIQUE NONCLUSTERED (PHYU_SI_UNIT)
GO
ALTER TABLE PHYSICAL_UNIT ADD CONSTRAINT PHYU_UK_NAME UNIQUE NONCLUSTERED (PHYU_NAME)
GO

CREATE TABLE projects 
    (
     proj_id INTEGER NOT NULL , 
     proj_name VARCHAR (60) NOT NULL , 
     proj_curr_lang VARCHAR (2) , 
     proj_languages VARCHAR (60) , 
     proj_uc VARCHAR (30) NOT NULL , 
     proj_dc VARCHAR (30) NOT NULL , 
     proj_um VARCHAR (30) , 
     proj_dm VARCHAR (30) 
    )
GO

ALTER TABLE projects ADD CONSTRAINT proj_pk PRIMARY KEY CLUSTERED (proj_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE projects ADD CONSTRAINT proj_uk UNIQUE NONCLUSTERED (proj_name)
GO

CREATE TABLE RELATIONREPS 
    (
     RELR_ID NUMERIC (10) NOT NULL , 
     RELR_DIAG_ID NUMERIC (28) NOT NULL , 
     RELR_MODE_ID NUMERIC (28) NOT NULL , 
     RELR_LINEWIDTH NUMERIC (3,1) NOT NULL DEFAULT (1) , 
     RELR_LINECOLOR VARCHAR (6) DEFAULT '000000' , 
     RELR_LINEOPACITY NUMERIC (3) DEFAULT 100 , 
     RELR_STARTEDGE VARCHAR (1) , 
     RELR_STARTPOSITION NUMERIC (4,1) , 
     RELR_START_CONNECTOR VARCHAR (1) , 
     RELR_STARTTEXT_ANGLE NUMERIC (12,11) , 
     RELR_STARTTEXT_DISTANCE NUMERIC (4) , 
     RELR_STARTTEXT_X NUMERIC (6) , 
     RELR_STARTTEXT_Y NUMERIC (6) , 
     RELR_STARTTEXT_WIDTH NUMERIC (4) , 
     RELR_STARTTEXT_HEIGHT NUMERIC (4) , 
     RELR_ENDEDGE VARCHAR (1) , 
     RELR_ENDPOSITION NUMERIC (4,1) , 
     RELR_END_CONNECTOR VARCHAR (1) , 
     RELR_ENDTEXT_ANGLE NUMERIC (12,11) , 
     RELR_ENDTEXT_DISTANCE NUMERIC (4) , 
     RELR_ENDTEXT_X NUMERIC (6) , 
     RELR_ENDTEXT_Y NUMERIC (6) , 
     RELR_ENDTEXT_WIDTH NUMERIC (4) , 
     RELR_ENDTEXT_HEIGHT NUMERIC (4) , 
     RELR_FONTCOLOR VARCHAR (6) DEFAULT '000000' , 
     RELR_FONTSIZE NUMERIC (3) , 
     RELR_UC VARCHAR (30) NOT NULL , 
     RELR_DC DATETIME (8) NOT NULL , 
     RELR_UM VARCHAR (30) , 
     BEDA_DM DATETIME (8) 
    )
GO 


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___075714DC 
    CHECK ( datalength([RELR_LINECOLOR])=(6) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___093F5D4E 
    CHECK ( [RELR_LINEOPACITY]>=(0) AND [RELR_LINEOPACITY]<=(100) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0A338187 
    CHECK ( [RELR_STARTEDGE]='W' OR [RELR_STARTEDGE]='S' OR [RELR_STARTEDGE]='E' OR [RELR_STARTEDGE]='N' ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0B27A5C0 
    CHECK ( [RELR_STARTPOSITION]>=(0.0) AND [RELR_STARTPOSITION]<=(100.0) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0C1BC9F9 
    CHECK ( [RELR_START_CONNECTOR]='M' OR [RELR_START_CONNECTOR]='1' ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0D0FEE32 
    CHECK ( [RELR_STARTTEXT_ANGEL]>=(-179) AND [RELR_STARTTEXT_ANGEL]<=(180) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0E04126B 
    CHECK ( [RELR_STARTTEXT_DISTANCE]>=(1) AND [RELR_STARTTEXT_DISTANCE]<=(9999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0EF836A4 
    CHECK ( [RELR_STARTTEXT_X]>=(0) AND [RELR_STARTTEXT_X]<=(999999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___0FEC5ADD 
    CHECK ( [RELR_STARTTEXT_Y]>=(0) AND [RELR_STARTTEXT_Y]<=(999999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___10E07F16 
    CHECK ( [RELR_STARTTEXT_WIDTH]>=(1) AND [RELR_STARTTEXT_WIDTH]<=(9999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___11D4A34F 
    CHECK ( [RELR_STARTTEXT_HEIGHT]>=(1) AND [RELR_STARTTEXT_HEIGHT]<=(9999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___12C8C788 
    CHECK ( [RELR_ENDEDGE]='W' OR [RELR_ENDEDGE]='S' OR [RELR_ENDEDGE]='E' OR [RELR_ENDEDGE]='N' ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___13BCEBC1 
    CHECK ( [RELR_ENDPOSITION]>=(0.0) AND [RELR_ENDPOSITION]<=(100.0) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___14B10FFA 
    CHECK ( [RELR_END_CONNECTOR]='M' OR [RELR_END_CONNECTOR]='1' ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___15A53433 
    CHECK ( [RELR_ENDTEXT_ANGEL]>=(-179) AND [RELR_ENDTEXT_ANGEL]<=(180) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___1699586C 
    CHECK ( [RELR_ENDTEXT_DISTANCE]>=(1) AND [RELR_ENDTEXT_DISTANCE]<=(9999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___178D7CA5 
    CHECK ( [RELR_ENDTEXT_X]>=(0) AND [RELR_ENDTEXT_X]<=(999999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___1881A0DE 
    CHECK ( [RELR_ENDTEXT_Y]>=(0) AND [RELR_ENDTEXT_Y]<=(999999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___1975C517 
    CHECK ( [RELR_ENDTEXT_WIDTH]>=(1) AND [RELR_ENDTEXT_WIDTH]<=(9999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___1A69E950 
    CHECK ( [RELR_ENDTEXT_HEIGHT]>=(1) AND [RELR_ENDTEXT_HEIGHT]<=(9999) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___1C5231C2 
    CHECK ( datalength([RELR_FONTCOLOR])=(6) ) 
GO


ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT CK__RELATIONR__RELR___1D4655FB 
    CHECK ( [RELR_FONTSIZE]>=(1) AND [RELR_FONTSIZE]<=(999) ) 
GO

ALTER TABLE RELATIONREPS ADD CONSTRAINT RELR_PK PRIMARY KEY CLUSTERED (RELR_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE RELATIONREPS ADD CONSTRAINT RELR_UN UNIQUE NONCLUSTERED (RELR_DIAG_ID, RELR_MODE_ID)
GO

CREATE TABLE RELATIONS 
    (
     RELA_ID NUMERIC (10) NOT NULL , 
     RELA_NAME VARCHAR (60) NOT NULL , 
     RELA_TYPE VARCHAR (4) NOT NULL , 
     RELA_ENTI_ID_FROM NUMERIC (10) NOT NULL , 
     RELA_ARCS_ID_FROM NUMERIC (10) , 
     RELA_ASSOC_FROM_TO VARCHAR (4000) , 
     RELA_HIST_FROM_TO VARCHAR (5) NOT NULL , 
     RELA_MANDATORY_FROM_TO VARCHAR (5) NOT NULL , 
     RELA_MAPTYPE_FROM_TO CHAR (1) NOT NULL , 
     RELA_ENTI_ID_TO NUMERIC (10) NOT NULL , 
     RELA_ARCS_ID_TO NUMERIC (10) , 
     RELA_ASSOC_TO_FROM VARCHAR (4000) , 
     RELA_HIST_TO_FROM VARCHAR (5) NOT NULL , 
     RELA_MAPTYPE_TO_FROM CHAR (1) NOT NULL , 
     RELA_MANDATORY_TO_FROM VARCHAR (5) NOT NULL , 
     RELA_UC VARCHAR (30) NOT NULL , 
     RELA_DC DATETIME NOT NULL , 
     RELA_UM VARCHAR (30) , 
     RELA_DM DATETIME (8) 
    )
GO 


ALTER TABLE RELATIONS 
    ADD CONSTRAINT CK__RELATIONS__RELA___2116E6DF 
    CHECK ( [RELA_TYPE]='M:N' OR [RELA_TYPE]='M:1' OR [RELA_TYPE]='ISA' OR [RELA_TYPE]='1:1' ) 
GO


ALTER TABLE RELATIONS 
    ADD 
    CHECK ( RELA_HIST_FROM_TO IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE RELATIONS 
    ADD 
    CHECK ( RELA_MANDATORY_FROM_TO IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE RELATIONS 
    ADD 
    CHECK ( RELA_MAPTYPE_FROM_TO IN ('1', 'M') ) 
GO


ALTER TABLE RELATIONS 
    ADD 
    CHECK ( RELA_HIST_TO_FROM IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE RELATIONS 
    ADD 
    CHECK ( RELA_MAPTYPE_TO_FROM IN ('1', 'M') ) 
GO


ALTER TABLE RELATIONS 
    ADD 
    CHECK ( RELA_MANDATORY_TO_FROM IN ('FALSE', 'TRUE') ) 
GO

ALTER TABLE RELATIONS ADD CONSTRAINT RELATIONS_PK PRIMARY KEY CLUSTERED (RELA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE RELATIONS ADD CONSTRAINT RELATIONS_RELA_ID_UN UNIQUE NONCLUSTERED (RELA_ID)
GO
ALTER TABLE RELATIONS ADD CONSTRAINT RELA_UK_NAME UNIQUE NONCLUSTERED (RELA_NAME)
GO

ALTER TABLE RELATIONS ADD CONSTRAINT RELA_MAPTYPE_CHK CHECK ( [RELA_TYPE]='ISAR' AND [RELA_MAPTYPE_FROM_TO]='1' AND [RELA_MAPTYPE_TO_FROM]='1' AND ([RELA_MANDATORY_FROM_TO]='TRUE' OR [RELA_MANDATORY_TO_FROM]='TRUE') OR [RELA_TYPE]='ISAS' AND [RELA_MAPTYPE_FROM_TO]='1' AND [RELA_MAPTYPE_TO_FROM]='1' AND [RELA_MANDATORY_FROM_TO]='TRUE' AND [RELA_MANDATORY_TO_FROM]='TRUE' AND ([RELA_ARCS_ID_FROM] IS NOT NULL OR [RELA_ARCS_ID_TO] IS NOT NULL) OR [RELA_TYPE]='1:1' AND [RELA_MAPTYPE_FROM_TO]='1' AND [RELA_MAPTYPE_TO_FROM]='1' OR [RELA_TYPE]='M:1' AND ([RELA_MAPTYPE_FROM_TO]='1' AND [RELA_MAPTYPE_TO_FROM]='M' OR [RELA_MAPTYPE_FROM_TO]='M' AND [RELA_MAPTYPE_TO_FROM]='1') OR [RELA_TYPE]='M:N' AND [RELA_MAPTYPE_TO_FROM]='M' AND [RELA_MAPTYPE_FROM_TO]='M' ) 
GO

CREATE TABLE STORAGE_FORMATS 
    (
     STFO_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     STFO_NAME VARCHAR (60) NOT NULL , 
     STFO_DESCR VARCHAR (4000) , 
     STFO_UC VARCHAR (30) NOT NULL , 
     STFO_DC DATETIME (8) NOT NULL , 
     STFO_UM VARCHAR (30) , 
     STFO_DM DATETIME (8) 
    )
GO

ALTER TABLE STORAGE_FORMATS ADD CONSTRAINT STFO_PK PRIMARY KEY CLUSTERED (STFO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE STORAGE_FORMATS ADD CONSTRAINT STFO_UN UNIQUE NONCLUSTERED (STFO_NAME)
GO

CREATE TABLE SYNONYMS 
    (
     SYNO_ID NUMERIC (10) NOT NULL , 
     SYNO_NAME VARCHAR (60) NOT NULL , 
     SYNO_ENTI_ID NUMERIC (10) NOT NULL , 
     SYNO_UC VARCHAR (30) NOT NULL , 
     SYNO_DC DATETIME (8) NOT NULL , 
     SYNO_UM VARCHAR (30) , 
     SYNO_DM DATETIME (8) 
    )
GO

ALTER TABLE SYNONYMS ADD CONSTRAINT SYNONYMS_PK PRIMARY KEY CLUSTERED (SYNO_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE SYNONYMS ADD CONSTRAINT SYNO_ID_UN UNIQUE NONCLUSTERED (SYNO_ID)
GO

CREATE TABLE TABL_ENTI_MAP 
    (
     TEMA_ID NUMERIC (10) NOT NULL , 
     TEMA_TABL_ID NUMERIC (10) , 
     TEMA_ENTI_ID NUMERIC (10) , 
     TEMA_RELA_ID NUMERIC (10) 
    )
GO 
ALTER TABLE TABL_ENTI_MAP 
    ADD CONSTRAINT FKArc_6 CHECK ( 
        (  (TEMA_ENTI_ID IS NOT NULL) AND 
         (TEMA_RELA_ID IS NULL) ) OR 
        (  (TEMA_RELA_ID IS NOT NULL) AND 
         (TEMA_ENTI_ID IS NULL) )  ) 
;

ALTER TABLE TABL_ENTI_MAP ADD CONSTRAINT TEMA_PK PRIMARY KEY CLUSTERED (TEMA_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE TABL_ENTI_MAP ADD CONSTRAINT TEMA_UNENTI UNIQUE NONCLUSTERED (TEMA_TABL_ID, TEMA_ENTI_ID)
GO
ALTER TABLE TABL_ENTI_MAP ADD CONSTRAINT TEMA_UNRELA UNIQUE NONCLUSTERED (TEMA_TABL_ID, TEMA_RELA_ID)
GO

ALTER TABLE TABL_ENTI_MAP ADD CONSTRAINT FKArc_5 CHECK ( [TEMA_RELA_ID] IS NOT NULL AND [TEMA_ENTI_ID] IS NULL OR [TEMA_ENTI_ID] IS NOT NULL AND [TEMA_RELA_ID] IS NULL OR [TEMA_RELA_ID] IS NULL AND [TEMA_ENTI_ID] IS NULL ) 
GO

CREATE TABLE TABLES 
    (
     TABL_ID NUMERIC (10) NOT NULL , 
     TABL_NAME VARCHAR (60) NOT NULL , 
     TABL_DESCR VARCHAR (4000) , 
     TABL_INTF_ID NUMERIC (10) NOT NULL , 
     TABL_CREATE VARCHAR (5) NOT NULL DEFAULT 'FALSE' , 
     TABL_READ VARCHAR (5) NOT NULL DEFAULT 'TRUE' , 
     TABL_UPDATE VARCHAR (5) NOT NULL DEFAULT 'FALSE' , 
     TABL_DELETE VARCHAR (5) NOT NULL DEFAULT 'FALSE' , 
     TABL_UC VARCHAR (30) NOT NULL , 
     TABL_DC DATETIME (8) NOT NULL , 
     TABL_UM VARCHAR (30) , 
     TABL_DM DATETIME (8) 
    )
GO 


ALTER TABLE TABLES 
    ADD 
    CHECK ( TABL_CREATE IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE TABLES 
    ADD 
    CHECK ( TABL_READ IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE TABLES 
    ADD 
    CHECK ( TABL_UPDATE IN ('FALSE', 'TRUE') ) 
GO


ALTER TABLE TABLES 
    ADD 
    CHECK ( TABL_DELETE IN ('FALSE', 'TRUE') ) 
GO

ALTER TABLE TABLES ADD CONSTRAINT TABLES_PK PRIMARY KEY CLUSTERED (TABL_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE TABLES ADD CONSTRAINT TABL_UN UNIQUE NONCLUSTERED (TABL_NAME, TABL_INTF_ID)
GO

CREATE TABLE templatetable 
    (
     UC VARCHAR (60) , 
     DC DATETIME , 
     UM VARCHAR (60) , 
     DM DATETIME 
    )
GO

CREATE TABLE UDP_VALUES 
    (
     UDPV_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     UDPV_VALUE VARCHAR (max) , 
     UDPV_MODE_ID NUMERIC (10) NOT NULL , 
     UDPV_UDPR_ID NUMERIC (10) NOT NULL , 
     UDPV_UC VARCHAR (30) NOT NULL , 
     UDPV_DC DATETIME (8) NOT NULL , 
     UDPV_UM VARCHAR (30) , 
     UDPV_DM DATETIME (8) 
    )
GO

ALTER TABLE UDP_VALUES ADD CONSTRAINT UDPV_PK PRIMARY KEY CLUSTERED (UDPV_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE UDP_VALUES ADD CONSTRAINT UDPV_UN UNIQUE NONCLUSTERED (UDPV_MODE_ID, UDPV_UDPR_ID)
GO

CREATE TABLE USER_DEFINED_PROPERTIES 
    (
     UDPR_ID NUMERIC (10) NOT NULL IDENTITY NOT FOR REPLICATION , 
     UDPR_THEME VARCHAR (60) NOT NULL , 
     UDPR_GROUP VARCHAR (60) , 
     UDPR_NAME VARCHAR (60) NOT NULL , 
     UDPR_DESCR VARCHAR (4000) , 
     UDPR_DEFAULTVALUE VARCHAR (4000) , 
     UDPR_UC VARCHAR (30) NOT NULL , 
     UDPR_DC DATETIME (8) NOT NULL , 
     UDPR_UM VARCHAR (30) , 
     UDPR_DM DATETIME (8) 
    )
GO

ALTER TABLE USER_DEFINED_PROPERTIES ADD CONSTRAINT UDPR_PK PRIMARY KEY CLUSTERED (UDPR_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE USER_DEFINED_PROPERTIES ADD CONSTRAINT UDPR_UN UNIQUE NONCLUSTERED (UDPR_THEME, UDPR_NAME)
GO

ALTER TABLE ARCS 
    ADD CONSTRAINT ARCS_ENTITIES_FK FOREIGN KEY 
    ( 
     ARCS_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ARCS 
    ADD CONSTRAINT ARCS_MODE_FK FOREIGN KEY 
    ( 
     ARCS_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ATTRIBUTES 
    ADD CONSTRAINT ATTR_DOMA_FK FOREIGN KEY 
    ( 
     ATTR_DOMA_ID
    ) 
    REFERENCES DOMAINS 
    ( 
     DOMA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ATTRIBUTES 
    ADD CONSTRAINT ATTR_ENTI_FK FOREIGN KEY 
    ( 
     ATTR_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ATTRIBUTES 
    ADD CONSTRAINT ATTR_MODE_FK FOREIGN KEY 
    ( 
     ATTR_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BUSINESS_RULES 
    ADD CONSTRAINT BUSINESS_RULES_MODELELEMENT_FK FOREIGN KEY 
    ( 
     BURU_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BUSINESSRULE_ELEMENTS 
    ADD CONSTRAINT BUSINESSRULE_ELEMENTS_BUSINESS_RULES_FK FOREIGN KEY 
    ( 
     BURE_BURU_ID
    ) 
    REFERENCES BUSINESS_RULES 
    ( 
     BURU_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE BUSINESSRULE_ELEMENTS 
    ADD CONSTRAINT BUSINESSRULE_ELEMENTS_MODELELEMENT_FK FOREIGN KEY 
    ( 
     BURE_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE COLU_ATTR_MAP 
    ADD CONSTRAINT COAM_ATTR_FK FOREIGN KEY 
    ( 
     coam_attr_id
    ) 
    REFERENCES ATTRIBUTES 
    ( 
     ATTR_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE COLU_ATTR_MAP 
    ADD CONSTRAINT COAM_COLU_FK FOREIGN KEY 
    ( 
     coam_colu_id
    ) 
    REFERENCES COLUMNS 
    ( 
     COLU_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE COLUMNS 
    ADD CONSTRAINT COLU_DOMA_FK FOREIGN KEY 
    ( 
     COLU_DOMA_ID
    ) 
    REFERENCES DOMAINS 
    ( 
     DOMA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE COLUMNS 
    ADD CONSTRAINT COLU_MODE_FK FOREIGN KEY 
    ( 
     COLU_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE COLUMNS 
    ADD CONSTRAINT COLU_TABL_FK FOREIGN KEY 
    ( 
     COLU_TABL_ID
    ) 
    REFERENCES TABLES 
    ( 
     TABL_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DATATYPES 
    ADD CONSTRAINT DATY_MODE_FK FOREIGN KEY 
    ( 
     DATY_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DEFAULT_VALUES 
    ADD CONSTRAINT DEFAULT_VALUES_DOMAINS_FK FOREIGN KEY 
    ( 
     DEVA_DOMA_ID
    ) 
    REFERENCES DOMAINS 
    ( 
     DOMA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINGROUP_MEMBERS 
    ADD CONSTRAINT DGRM_MODE_FK FOREIGN KEY 
    ( 
     DGRM_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DIAGRAMS 
    ADD CONSTRAINT DIAG_DIAT_FK FOREIGN KEY 
    ( 
     DIAG_DIAT_ID
    ) 
    REFERENCES DIAGRAMTYPES 
    ( 
     DIAT_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DIAGRAMS 
    ADD CONSTRAINT DIAG_MODE_FK FOREIGN KEY 
    ( 
     DIAG_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOCUMENTS 
    ADD CONSTRAINT DOCU_DOCU_FK FOREIGN KEY 
    ( 
     DOCU_DOCU_ID
    ) 
    REFERENCES DOCUMENTS 
    ( 
     DOCU_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOCUMENTS 
    ADD CONSTRAINT DOCU_MODE_FK FOREIGN KEY 
    ( 
     DOCU_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOCUMENTS 
    ADD CONSTRAINT DOCU_STFO_FK FOREIGN KEY 
    ( 
     DOCU_STFO_ID
    ) 
    REFERENCES STORAGE_FORMATS 
    ( 
     STFO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINS 
    ADD CONSTRAINT DOMA_DATY_ID FOREIGN KEY 
    ( 
     DOMA_DATY_ID
    ) 
    REFERENCES DATATYPES 
    ( 
     DATY_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINS 
    ADD CONSTRAINT DOMA_MODE_FK FOREIGN KEY 
    ( 
     DOMA_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINS 
    ADD CONSTRAINT DOMA_PHYU_FK FOREIGN KEY 
    ( 
     DOMA_NUM_PHYU_ID
    ) 
    REFERENCES PHYSICAL_UNIT 
    ( 
     PHYU_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINS 
    ADD CONSTRAINT DOMA_STFO_FK FOREIGN KEY 
    ( 
     DOMA_BIN_STFO_ID
    ) 
    REFERENCES STORAGE_FORMATS 
    ( 
     STFO_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINGROUP_MEMBERS 
    ADD CONSTRAINT DOMAINGROUP_MEMBERS_DOMAINS_FK FOREIGN KEY 
    ( 
     DGRM_DOMA_ID_GROUP
    ) 
    REFERENCES DOMAINS 
    ( 
     DOMA_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DOMAINGROUP_MEMBERS 
    ADD CONSTRAINT DOMAINGROUP_MEMBERS_DOMAINS_FKv2 FOREIGN KEY 
    ( 
     DGRM_DOMA_ID_MEMBER
    ) 
    REFERENCES DOMAINS 
    ( 
     DOMA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT ELER_DIAG_FK FOREIGN KEY 
    ( 
     ELER_DIAG_ID
    ) 
    REFERENCES DIAGRAMS 
    ( 
     DIAG_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ELEMENTREPS 
    ADD CONSTRAINT ELER_MODE_FK FOREIGN KEY 
    ( 
     ELER_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT ELUI_ENCA_FK FOREIGN KEY 
    ( 
     ELUI_ENCA_ID
    ) 
    REFERENCES ENTITY_CATEGORIES 
    ( 
     ENCA_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ELEMENT_UI 
    ADD CONSTRAINT ELUI_MELT_FK FOREIGN KEY 
    ( 
     ELUI_MELT_ID
    ) 
    REFERENCES MODELELEM_TYPE 
    ( 
     MELT_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ENTITIES 
    ADD CONSTRAINT ENTI_ENCA_FK FOREIGN KEY 
    ( 
     ENTI_ENCA_ID
    ) 
    REFERENCES ENTITY_CATEGORIES 
    ( 
     ENCA_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ENTITIES 
    ADD CONSTRAINT ENTI_UNDERLAY_FK FOREIGN KEY 
    ( 
     ENTI_UNDERLAY_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ENTITIES 
    ADD CONSTRAINT ENTI_MODE_FK FOREIGN KEY 
    ( 
     ENTI_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EXAMPLE 
    ADD CONSTRAINT EXPL_ATTR_FK FOREIGN KEY 
    ( 
     EXPL_ATTR_ID
    ) 
    REFERENCES ATTRIBUTES 
    ( 
     ATTR_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EXAMPLE 
    ADD CONSTRAINT EXPL_ENTI_FK FOREIGN KEY 
    ( 
     EXPL_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EXAMPLE 
    ADD CONSTRAINT EXPL_MODE_FK FOREIGN KEY 
    ( 
     EXPL_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EXTERNAL_REFS 
    ADD CONSTRAINT EXTR_MODE_FK FOREIGN KEY 
    ( 
     EXTR_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE INTERFACES 
    ADD CONSTRAINT INFT_MODE_FK FOREIGN KEY 
    ( 
     INTF_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE KEY_ELEMENTS 
    ADD CONSTRAINT KELE_ATTR_FK FOREIGN KEY 
    ( 
     KELE_ATTR_ID
    ) 
    REFERENCES ATTRIBUTES 
    ( 
     ATTR_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE KEY_ELEMENTS 
    ADD CONSTRAINT KELE_KEYS_FK FOREIGN KEY 
    ( 
     KELE_KEYS_ID
    ) 
    REFERENCES KEYS 
    ( 
     KEYS_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE KEY_ELEMENTS 
    ADD CONSTRAINT KELE_RELA_FK FOREIGN KEY 
    ( 
     KELE_RELA_ID
    ) 
    REFERENCES RELATIONS 
    ( 
     RELA_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE KEYS 
    ADD CONSTRAINT KEYS_ENTI_FK FOREIGN KEY 
    ( 
     KEYS_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE LANGUAGES 
    ADD CONSTRAINT LANG_REPLACE_FK FOREIGN KEY 
    ( 
     LANG_LANG_ID
    ) 
    REFERENCES LANGUAGES 
    ( 
     LANG_ID 
    ) 
    ON DELETE SET NULL 
    ON UPDATE NO ACTION 
GO

ALTER TABLE LINESEGMENTS 
    ADD CONSTRAINT LISE_BEDA_FK FOREIGN KEY 
    ( 
     LISE_RELR_ID
    ) 
    REFERENCES RELATIONREPS 
    ( 
     RELR_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MELT_DIATS 
    ADD CONSTRAINT MEDI_DIAT_FK FOREIGN KEY 
    ( 
     MEDI_DIAT_ID
    ) 
    REFERENCES DIAGRAMTYPES 
    ( 
     DIAT_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODELEMTYPE_PROPERTIES 
    ADD CONSTRAINT METP_MELT_FK FOREIGN KEY 
    ( 
     METP_MELT_ID
    ) 
    REFERENCES MODELELEM_TYPE 
    ( 
     MELT_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODELEMTYPE_PROPERTIES 
    ADD CONSTRAINT METP_UDPR_FK FOREIGN KEY 
    ( 
     METP_UDPR_ID
    ) 
    REFERENCES USER_DEFINED_PROPERTIES 
    ( 
     UDPR_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODELELEMENT 
    ADD CONSTRAINT MODE_MELT_FK FOREIGN KEY 
    ( 
     MODE_MELT_ID
    ) 
    REFERENCES MODELELEM_TYPE 
    ( 
     MELT_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MELT_DIATS 
    ADD CONSTRAINT MODI_MELT_FK FOREIGN KEY 
    ( 
     MEDI_MELT_ID
    ) 
    REFERENCES MODELELEM_TYPE 
    ( 
     MELT_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODE_DOCU 
    ADD CONSTRAINT MODO_DOCU_FK FOREIGN KEY 
    ( 
     MODO_DOCU_ID
    ) 
    REFERENCES DOCUMENTS 
    ( 
     DOCU_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODE_DOCU 
    ADD CONSTRAINT MODO_MODE_FKv2 FOREIGN KEY 
    ( 
     MODO_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODE_ORGU 
    ADD CONSTRAINT MOOU_MODE_FK FOREIGN KEY 
    ( 
     MOOU_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MODE_ORGU 
    ADD CONSTRAINT MOOU_ORGU_FK FOREIGN KEY 
    ( 
     MOOU_ORGU_ID
    ) 
    REFERENCES ORGANISATIONALUNITS 
    ( 
     ORGU_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ORGANISATIONALUNITS 
    ADD CONSTRAINT ORGU_MODE_FK FOREIGN KEY 
    ( 
     ORGU_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ORGANISATIONALUNITS 
    ADD CONSTRAINT ORGU_ORGU_FK FOREIGN KEY 
    ( 
     ORGU_ORGU_ID
    ) 
    REFERENCES ORGANISATIONALUNITS 
    ( 
     ORGU_ID 
    ) 
    ON DELETE SET NULL 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONS 
    ADD CONSTRAINT RELA_ARCS_FROM_FK FOREIGN KEY 
    ( 
     RELA_ARCS_ID_FROM
    ) 
    REFERENCES ARCS 
    ( 
     ARCS_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONS 
    ADD CONSTRAINT RELA_ARCS_TO_FK FOREIGN KEY 
    ( 
     RELA_ARCS_ID_TO
    ) 
    REFERENCES ARCS 
    ( 
     ARCS_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT RELA_DIAG_FK FOREIGN KEY 
    ( 
     RELR_DIAG_ID
    ) 
    REFERENCES DIAGRAMS 
    ( 
     DIAG_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONS 
    ADD CONSTRAINT RELA_ENTI_FK_TO FOREIGN KEY 
    ( 
     RELA_ENTI_ID_TO
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONS 
    ADD CONSTRAINT RELA_ENTI_ID_FROM FOREIGN KEY 
    ( 
     RELA_ENTI_ID_FROM
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONS 
    ADD CONSTRAINT RELA_MODE_FK FOREIGN KEY 
    ( 
     RELA_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE RELATIONREPS 
    ADD CONSTRAINT RELR_MODE_FK FOREIGN KEY 
    ( 
     RELR_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE LANG_TEXTS 
    ADD CONSTRAINT SPTX_LANG_FK FOREIGN KEY 
    ( 
     LGTX_LANG_ID
    ) 
    REFERENCES LANGUAGES 
    ( 
     LANG_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE LANG_TEXTS 
    ADD CONSTRAINT SPTX_MODE_FK FOREIGN KEY 
    ( 
     LGTX_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SYNONYMS 
    ADD CONSTRAINT SYNO_ENTI_FK FOREIGN KEY 
    ( 
     SYNO_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE SYNONYMS 
    ADD CONSTRAINT SYNO_MODE_FK FOREIGN KEY 
    ( 
     SYNO_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TABLES 
    ADD CONSTRAINT TABL_INTF_FK FOREIGN KEY 
    ( 
     TABL_INTF_ID
    ) 
    REFERENCES INTERFACES 
    ( 
     INTF_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TABLES 
    ADD CONSTRAINT TABL_MODE_FK FOREIGN KEY 
    ( 
     TABL_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TABL_ENTI_MAP 
    ADD CONSTRAINT TEMA_ENTI_FK FOREIGN KEY 
    ( 
     TEMA_ENTI_ID
    ) 
    REFERENCES ENTITIES 
    ( 
     ENTI_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TABL_ENTI_MAP 
    ADD CONSTRAINT TEMA_RELA_FK FOREIGN KEY 
    ( 
     TEMA_RELA_ID
    ) 
    REFERENCES RELATIONS 
    ( 
     RELA_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE TABL_ENTI_MAP 
    ADD CONSTRAINT TEMA_TABL_FK FOREIGN KEY 
    ( 
     TEMA_TABL_ID
    ) 
    REFERENCES TABLES 
    ( 
     TABL_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UDP_VALUES 
    ADD CONSTRAINT UDPV_MODE_FK FOREIGN KEY 
    ( 
     UDPV_MODE_ID
    ) 
    REFERENCES MODELELEMENT 
    ( 
     MODE_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UDP_VALUES 
    ADD CONSTRAINT UDPV_UDPR_FK FOREIGN KEY 
    ( 
     UDPV_UDPR_ID
    ) 
    REFERENCES USER_DEFINED_PROPERTIES 
    ( 
     UDPR_ID 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

CREATE VIEW dbversion  AS
SELECT
    '1.8'         AS version,
    datetime()    AS installedtime
FROM 
GO

CREATE VIEW SUPERENTI (rela_type varchar(4),
        superenti_id integer,
        super_enti_name varchar(60),
        subenti_id integer,
        sub_enti_name varchar(60))
AS
    WITH rel AS(
        SELECT
            rela_type,
            CASE
                WHEN rela_mandatory_to_from = 'TRUE' THEN
                    rela_enti_id_from
                ELSE
                    rela_enti_id_to
            END  AS rela_superenti_id,
            CASE
                WHEN rela_mandatory_from_to = 'TRUE' THEN
                    rela_enti_id_from
                ELSE
                    rela_enti_id_to
            END  AS rela_subenti_id
        FROM
            relations
        WHERE
            rela_type = 'ISAR'
    )
    SELECT
        rela_type,
        superentity.enti_id      AS superenti_id,
        superentity.enti_name    AS super_enti_name,
        subentity.enti_id        AS subenti_id,
        subentity.enti_name      AS sub_enti_name
    FROM
             entities superentity
        JOIN arcs ON arcs_enti_id = superentity.enti_id
        JOIN relations ON((rela_arcs_id_from = arcs_id
                           AND rela_enti_id_from = superentity.enti_id)
                          OR(rela_arcs_id_to = arcs_id
                             AND rela_enti_id_to = superentity.enti_id))
                         AND rela_type = 'ISAS'
        LEFT JOIN entities subentity ON(subentity.enti_id = rela_enti_id_to
                                        AND rela_arcs_id_from = arcs_id)
                                       OR(subentity.enti_id = rela_enti_id_from
                                          AND rela_arcs_id_to = arcs_id)
    UNION ALL
    SELECT
        rela_type,
        superentity.enti_id      AS superenti_id,
        superentity.enti_name    AS super_enti_name,
        subentity.enti_id        AS subenti_id,
        subentity.enti_name      AS sub_enti_name
    FROM
             entities superentity
        JOIN rel ON rela_superenti_id = superentity.enti_id
        JOIN entities subentity ON subentity.enti_id = rela_subenti_id 
GO



-- Zusammenfassungsbericht für Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            43
-- CREATE INDEX                             0
-- ALTER TABLE                            253
-- CREATE VIEW                              2
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
