#!/bin/bash
#Autor: stb 
#MYDIR: Verzeichnis in meiner Umgebung für die gemeinsamen Dateien des Modelers
#		Der Pfad für das Standardverzeichnis für Systemtypen im ODM zeigt dorthin.
#		Inhalt: das aktuell verwendete Verzeichnis "Konfiguration"
#		Das Konfigurationsverzeichnis des akutell zu startenden Modells (IM-Verzeichnis des Mandanten) wird nach MYDIR kopiert
#		und nach dem Aussteigen aus dem Modeler wieder zurück ins IM-Verzeichnis des Mandanten
#BASEDIR: 	Basisverzeichnis in dem sich das Verezeichnis IM befindet, in dem sich das Modell befindet
#			dieses Verzeichnis ist ein gitHub Verzeichnis. Alles was da drin und darunter ist wird nach gitHub committed  
#IMNAME:	wird als Name dieser Startdatei gesetzt. 
#ODMVERSION: Version des Oracle Data Modelers (ist im Verzeichnisname der Installation enthalten.)
BASEDIR=$(dirname "$0")
IMDIR=$BASEDIR/IM
MYDIR=$HOME"/Documents/DataModeler"
IMNAME=`basename "$0"`
echo "*******************"
echo Modell: $IMNAME 
echo BASEDIR $BASEDIR
echo KonfigurationDir $MYDIR
echo "*******************"
rm  -v  "$MYDIR/Konfiguration/"*
cp  -v "$IMDIR/Konfiguration"/* "$MYDIR/Konfiguration/"
/Applications/OracleDataModeler.app/Contents/Resources/datamodeler/datamodeler/bin/datamodeler "$IMDIR/$IMNAME.dmd"
cp  -v "$MYDIR/Konfiguration/"* "$IMDIR/Konfiguration/"
exit 0