#!/bin/bash
#stb, foryouandyourcustomers.
#tests a sql script to create a new sqlite DB in the current directory

#CALL:  testscript n.m
#applies the version n.m (modelmode_sqlite_n.m.sql) to the last database script

#setup
#there exists 
# a file  LAST_modelmodel_sqlite.sql containing the DDL for the last version of the DB
# a file  modelmodel_sqlite.sql containing the new DDL for the DB
# a file  modelmodel_sqlite_n.m.sql for the parameter n.m containing the delta to the last 

#we need current directory of calling file in case it is started in finder with double click
MYDIR=$(dirname "$0")
#where are the database DDL files
DBDIR=$MYDIR/../../SSOT_db/dbstructure/sqlite
cd $MYDIR
if [ -z "$1" ]; then
	read -p "enter version [n.m] of upgradefile: " version
else
	version=$1
fi
#database ddl files to be testes
lastscript=$DBDIR/LAST_modelmodel_sqlite.sql
currentscript=$DBDIR/modelmodel_sqlite.sql
upgradescript=$DBDIR/modelmodel_sqlite_$version.sql

#locaL files for testing purposes
olddb=OLD_emptydb.db
oldschema=OLD_schema.sql
newdb=NEW_emptydb.db
newschema=NEW_schema.sql
schemadiff=schemadiff.txt
schemaupgradediff=schemaupgradediff.txt

#test wether old sqldb can be created
rm -f $olddb
sqlite3 $olddb <$lastscript
status=$?
if [[ $status -ne 0 ]]
then
	echo "********** creation of database for $lastscript failed **********"
	read  -p "press enter to close" 	
	exit $status
fi
echo "=> creation of database from $lastscript successful"

#test wether new sqldb can be created
rm -f $newdb
sqlite3 $newdb <$currentscript
status=$?
if [[ $status -ne 0 ]]
then
	echo "********** creation of database for $currentscript failed **********"
	read  -p "press enter to close" 	
	exit $status
fi
echo "=> creation of database from $currentscript successful"

rm -f $oldschema $newschema $schemadiff $schemaupgradediff
sqlite3 $olddb .schema >$oldschema
sqlite3 $newdb .schema >$newschema
diff $oldschema $newschema >schemadiff.txt
echo ====================================================== 
echo ==== check $schemadiff and verify differences =====
echo ====================================================== 


if test -f "$upgradescript"; then
	echo "=> apply upgrade sql $upgradescript"
else
	echo "******** upgradefile  $upgradescript  not found *******"
	read  -p "press enter to close" 	
	exit 1
fi
#apply diff file to old db
sqlite3 $olddb <$upgradescript
status=$?
if [[ $status -ne 0 ]]
then
	echo "********** upgrade sql $upgradescript failed **********"
	read  -p "press enter to close" 	
	exit $status
fi
echo "=> upgrade sql $upgradescript applied successful"

sqlite3 $olddb .schema >$oldschema
diff $oldschema $newschema >schemaupgradediff.txt
echo =============================================================
echo ==== check $schemaupgradediff and verify differences =====
echo =============================================================

rm -f $olddb $newdb $oldschema $newschema

read  -p "press enter to close" 

