#!/bin/bash
MYDIR=$(dirname "$0")

echo =========================  test crmTest ========================= 
$MYDIR/crmTest/fillallinone
echo =========================  test ModellModell ========================= 
$MYDIR/ModellModell/fillallinone
read -p "press enter to close"