-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-08-23 14:34:26 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2




CREATE TABLE arc(
    arc_id        NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    arc_name      VARCHAR2(60 CHAR)NOT NULL,
    arc_enti_id   NUMBER(10)NOT NULL,
    arc_uc        VARCHAR2(30 BYTE)NOT NULL,
    arc_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    arc_um        VARCHAR2(30 BYTE)NULL,
    arc_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'ARC';
ALTER TABLE arc
    ADD CONSTRAINT arc_pk PRIMARY KEY(arc_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'ARC';

ALTER TABLE arc
    ADD CONSTRAINT arc_uk UNIQUE(arc_enti_id,
                                 arc_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'BEZIEHUNG';
CREATE TABLE beziehung(
    bezi_id                        NUMBER(10)NOT NULL,
    bezi_isa_assoc                 VARCHAR2(5 CHAR)NOT NULL,
    bezi_enti_id_von               NUMBER(10)NOT NULL,
    bezi_uetx_id_assoc_von_zu      NUMBER(10)NULL,
    bezi_abbildtyp_von_zu          CHAR(1 CHAR)NOT NULL,
    bezi_pflicht_assoc_von_zu      VARCHAR2(5 CHAR)NOT NULL
        CHECK(bezi_pflicht_assoc_von_zu IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_hist_von_zu               VARCHAR2(5 CHAR)NOT NULL
        CHECK(bezi_hist_von_zu IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_enti_id_zu                NUMBER(10)NOT NULL,
    bezi_uetx_id_assoc_zu_von      NUMBER(10)NULL,
    bezi_abbildtyp_zu_von          CHAR(1 CHAR)NOT NULL,
    "BEZI_PFLICHT_ASSOC_ZU_VON "   VARCHAR2(5 CHAR)NOT NULL
        CHECK("BEZI_PFLICHT_ASSOC_ZU_VON " IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_hist_zu_von               VARCHAR2(5 CHAR)NOT NULL
        CHECK(bezi_hist_zu_von IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_arc_id                    NUMBER(10)NULL,
        bezi_uc                        VARCHAR2(30 CHAR)AS(user)VIRTUAL NOT NULL,
    bezi_dc                        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    bezi_um                        VARCHAR2(30 BYTE)NULL,
    bezi_dm                        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING CHECK CONSTRAINT ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_isa_ck2 CHECK((bezi_isa_assoc_ = 'TRUE'
                                       AND bezi_isa_abbildtyp_von_zu = '1'
                                       AND bezi_isa_abbildtyp_zu_von = '1'
                                       AND bezi_pflicht_assoc_von_zu = 'TRUE')
                                      OR(bezi_is_assoc = 'FALSE'
                                         AND bezi_uetx_id_assoc_zu_von IS NOT NULL
                                         AND bezi_uetx_id_assoc_zu_von IS NOT NULL))NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'BEZIEHUNG';

ALTER TABLE beziehung
    ADD CONSTRAINT bezi_pk PRIMARY KEY(bezi_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING FOREIGN KEY ON 'ARC';
ALTER TABLE arc
    ADD CONSTRAINT arc_enti_fk FOREIGN KEY(arc_enti_id)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_arc_fk FOREIGN KEY(bezi_arc_id)
        REFERENCES arc(arc_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_enti_fk_von FOREIGN KEY(bezi_enti_id_von)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_enti_fk_zu FOREIGN KEY(bezi_enti_id_zu)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

--  ERROR: Invalid View WERTEBEREICH_LOV

--  ERROR: Invalid View WERTEBEREICH_NUM

--  ERROR: Invalid View WERTEBEREICH_TEXT

--  ERROR: Invalid View WERTEBEREICH_ZPKT



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   4
-- WARNINGS                                 0
