-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-10-30 11:47:04 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



PROMPT CREATING TABLE 'BEZIEHUNG_DARST';
CREATE TABLE beziehung_darst(
    beda_id                  NUMBER(10)NOT NULL,
    beda_diag_id             NUMBER(10)NOT NULL,
    beda_mode_id             NUMBER(10)NOT NULL,
    beda_linienbreite        NUMBER(3,1)DEFAULT 1 NOT NULL,
    beda_liniefarbe          VARCHAR2(6 CHAR)DEFAULT '000000' NULL
        CHECK(length()= 6)NOT DEFERRABLE ENABLE VALIDATE,
    beda_liniedeckkraft      NUMBER(3)DEFAULT 100 NULL
        CHECK(beda_liniedeckkraft BETWEEN 0 AND 100)NOT DEFERRABLE ENABLE VALIDATE,
    beda_startkante          VARCHAR2(1 CHAR)NULL
        CHECK(beda_startkante IN(
            'N',
            'O',
            'S',
            'W'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    beda_startposition       NUMBER(4,1)NULL
        CHECK(beda_startposition BETWEEN 0.0 AND 100.0)NOT DEFERRABLE ENABLE VALIDATE,
    beda_starttext_winkel    NUMBER(3)NULL
        CHECK(beda_starttext_winkel BETWEEN - 179 AND 180)NOT DEFERRABLE ENABLE VALIDATE,
    beda_starttext_abstand   NUMBER(4)NULL
        CHECK(beda_starttext_abstand BETWEEN 1 AND 9999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_starttext_x         NUMBER(6)NULL
        CHECK(beda_starttext_x BETWEEN 0 AND 999999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_starttext_y         NUMBER(6)NULL
        CHECK(beda_starttext_y BETWEEN 0 AND 999999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_starttext_breite    NUMBER(4)NULL
        CHECK(beda_starttext_breite BETWEEN 1 AND 9999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_starttext_hoehe     NUMBER(4)NULL
        CHECK(beda_starttext_hoehe BETWEEN 1 AND 9999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endkante            VARCHAR2(1 CHAR)NULL
        CHECK(beda_endkante IN(
            'N',
            'O',
            'S',
            'W'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    beda_endposition         NUMBER(4,1)NULL
        CHECK(beda_endposition BETWEEN 0.0 AND 100.0)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endtext_winkel      NUMBER(3)NULL
        CHECK(beda_endtext_winkel BETWEEN - 179 AND 180)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endtext_abstand     NUMBER(4)NULL
        CHECK(beda_endtext_abstand BETWEEN 1 AND 9999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endtext_x           NUMBER(6)NULL
        CHECK(beda_endtext_x BETWEEN 0 AND 999999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endtext_y           NUMBER(6)NULL
        CHECK(beda_endtext_y BETWEEN 0 AND 999999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endtext_breite      NUMBER(4)NULL
        CHECK(beda_endtext_breite BETWEEN 1 AND 9999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_endtext_hoehe       NUMBER(4)NULL
        CHECK(beda_endtext_hoehe BETWEEN 1 AND 9999)NOT DEFERRABLE ENABLE VALIDATE,
    beda_schriftfarbe        VARCHAR2(6 CHAR)DEFAULT '000000' NULL
        CHECK(length()= 6)NOT DEFERRABLE ENABLE VALIDATE,
    beda_schriftgroesse      NUMBER(3)NULL
        CHECK(beda_schriftgroesse BETWEEN 1 AND 999)NOT DEFERRABLE ENABLE VALIDATE,
        beda_uc                  VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    beda_dc                  TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    beda_um                  VARCHAR2(30 BYTE)NULL,
    beda_dm                  TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'BEZIEHUNG_DARST';
ALTER TABLE beziehung_darst
    ADD CONSTRAINT beda_pk PRIMARY KEY(beda_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'DIAGRAMM';
CREATE TABLE diagramm(
    diag_id        NUMBER(10)NOT NULL,
    diag_name      VARCHAR2(60 CHAR)NOT NULL,
    diag_diat_id   NUMBER(10)NOT NULL,
        diag_uc        VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    diag_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    diag_um        VARCHAR2(30 BYTE)NULL,
    diag_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'DIAGRAMM';
ALTER TABLE diagramm
    ADD CONSTRAINT diag_pk PRIMARY KEY(diag_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'DIAGRAMM';

ALTER TABLE diagramm
    ADD CONSTRAINT diag__un UNIQUE(diag_name)NOT DEFERRABLE ENABLE VALIDATE;

CREATE SEQUENCE modm_seq START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE ORDER;

PROMPT CREATING TABLE 'DIAGRAMMTYP';

CREATE TABLE diagrammtyp(
    diat_id    NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    diat_bez   VARCHAR2(100 CHAR)NOT NULL,
        diat_uc    VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    diat_dc    TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    diat_um    VARCHAR2(30 BYTE)NULL,
    diat_dm    TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'DIAGRAMMTYP';
ALTER TABLE diagrammtyp
    ADD CONSTRAINT diat_pk PRIMARY KEY(diat_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'DIAGRAMMTYP';

ALTER TABLE diagrammtyp
    ADD CONSTRAINT diat__un UNIQUE(diat_bez)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'ELEMENTDARST';
CREATE TABLE elementdarst(
    eled_id               NUMBER(10)NOT NULL,
    eled_position_x       NUMBER(6)NULL,
    eled_position_y       NUMBER(6)NULL,
    eled_breite           NUMBER(4)NOT NULL,
    eled_hoehe            NUMBER(4)NOT NULL,
    eled_deckkraft        NUMBER(3)DEFAULT 100 NULL
        CHECK(eled_deckkraft BETWEEN 0 AND 100)NOT DEFERRABLE ENABLE VALIDATE,
    eled_farbe            VARCHAR2(6 CHAR)DEFAULT '000000' NOT NULL
        CHECK(length()= 6)NOT DEFERRABLE ENABLE VALIDATE,
    eled_randbreite       NUMBER(3,1)DEFAULT 1 NULL,
    eled_randdeckkraft    NUMBER(3)DEFAULT 100 NULL
        CHECK(eled_randdeckkraft BETWEEN 0 AND 100)NOT DEFERRABLE ENABLE VALIDATE,
    eled_randfarbe        VARCHAR2(6 CHAR)DEFAULT '000000' NULL
        CHECK(length()= 6)NOT DEFERRABLE ENABLE VALIDATE,
    eled_schriftgroesse   NUMBER(3)NULL
        CHECK(eled_schriftgroesse BETWEEN 1 AND 999)NOT DEFERRABLE ENABLE VALIDATE,
    eled_schriftfarbe     VARCHAR2(6 CHAR)DEFAULT '000000' NULL
        CHECK(length()= 6)NOT DEFERRABLE ENABLE VALIDATE,
    eled_mode_id          NUMBER(10)NOT NULL,
    eled_diag_id          NUMBER(10)NOT NULL,
        eled_uc               VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    eled_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    eled_um               VARCHAR2(30 BYTE)NULL,
    eled_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

COMMENT ON COLUMN elementdarst.eled_position_x IS
    'Vorgabewert einer Darstellung eines Elementtyps';

COMMENT ON COLUMN elementdarst.eled_position_y IS
    'Vorgabewert einer Darstellung eines Elementtyps';

COMMENT ON COLUMN elementdarst.eled_breite IS
    'Vorgabewert der Darstellung des Randes um das Element';

COMMENT ON COLUMN elementdarst.eled_hoehe IS
    'Vorgabewert der Darstellung des Randes um das Element';

COMMENT ON COLUMN elementdarst.eled_randbreite IS
    'Vorgabewert der Darstellung des Randes um das Element';

COMMENT ON COLUMN elementdarst.eled_schriftgroesse IS
    'Vorgabewert der Schriftgrösse des Elementsnamens';

PROMPT CREATING PRIMARY KEY ON 'ELEMENTDARST';
ALTER TABLE elementdarst
    ADD CONSTRAINT elemendarstellung_pk PRIMARY KEY(eled_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'LINIE_SEGMENT';
CREATE TABLE linie_segment(
    lise_id          NUMBER(10)NOT NULL,
    lise_rhfg        NUMBER(4)NOT NULL,
    lise_beda_id     NUMBER(10)NOT NULL,
    lise_x           NUMBER(6)NOT NULL
        CONSTRAINT ck_beda_beda_schriftfarbe CHECK(lise_x BETWEEN 0 AND 999999)NOT DEFERRABLE ENABLE VALIDATE,
    lise_y           NUMBER(6)NOT NULL
        CONSTRAINT ck_beda_beda_schriftfarbe CHECK(lise_y BETWEEN 0 AND 999999)NOT DEFERRABLE ENABLE VALIDATE,
    lise_linientyp   VARCHAR2(6 CHAR)DEFAULT 'SOLID' NULL
        CONSTRAINT ck_beda_beda_schriftgroesse CHECK(lise_linientyp IN(
            'DADO',
            'DASHED',
            'DOTTED',
            'SOLID'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    lise_konnektor   VARCHAR2(3 CHAR)NULL,
        lise_uc          VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    lise_dc          TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    lise_um          VARCHAR2(30 BYTE)NULL,
    lise_dm          TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'LINIE_SEGMENT';
ALTER TABLE linie_segment
    ADD CONSTRAINT lise_pk PRIMARY KEY(lise_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'LINIE_SEGMENT';

ALTER TABLE linie_segment
    ADD CONSTRAINT lise__un UNIQUE(lise_beda_id,
                                   lise_rhfg)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'MELT_DIAT';
CREATE TABLE melt_diat(
    medi_id        NUMBER(10)NOT NULL,
    medi_diat_id   NUMBER(10)NOT NULL,
    medi_melt_id   NUMBER(10)NOT NULL,
        medi_uc        VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    mdei_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    diat_um        VARCHAR2(30 BYTE)NULL,
    diat_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'MELT_DIAT';
ALTER TABLE melt_diat
    ADD CONSTRAINT medi_pk PRIMARY KEY(medi_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'MELT_DIAT';

ALTER TABLE melt_diat
    ADD CONSTRAINT medi__un UNIQUE(medi_diat_id,
                                   medi_melt_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG_DARST';
ALTER TABLE beziehung_darst
    ADD CONSTRAINT beda_diag_fk FOREIGN KEY(beda_diag_id)
        REFERENCES diagramm(diag_id);

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG_DARST';
ALTER TABLE beziehung_darst
    ADD CONSTRAINT beda_mode_fk FOREIGN KEY(beda_mode_id)
        REFERENCES modellelement(mode_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ELEMENTDARST';
ALTER TABLE elementdarst
    ADD CONSTRAINT eled_diag_fk FOREIGN KEY(eled_diag_id)
        REFERENCES diagramm(diag_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ELEMENTDARST';
ALTER TABLE elementdarst
    ADD CONSTRAINT eled_mode_fk FOREIGN KEY(eled_mode_id)
        REFERENCES modellelement(mode_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'LINIE_SEGMENT';
ALTER TABLE linie_segment
    ADD CONSTRAINT lise_beda_fk FOREIGN KEY(lise_beda_id)
        REFERENCES beziehung_darst(beda_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MELT_DIAT';
ALTER TABLE melt_diat
    ADD CONSTRAINT medi_diat_fk FOREIGN KEY(medi_diat_id)
        REFERENCES diagrammtyp(diat_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_attr_fk_ist FOREIGN KEY(mode_attr_id)
        REFERENCES attributes(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_bezi_fk_ist FOREIGN KEY(mode_bezi_id)
        REFERENCES beziehung(bezi_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_buru_fk_ist FOREIGN KEY(mode_buru_id)
        REFERENCES business_rule(buru_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_enti_fk_ist FOREIGN KEY(mode_enti_id)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_melt_fk FOREIGN KEY(mode_melt_id)
        REFERENCES modellelem_typ(melt_id);

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_orge_fk_verantw FOREIGN KEY(mode_orge_id)
        REFERENCES org_einh(orge_id);

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_syno_fk FOREIGN KEY(mode_syno_id)
        REFERENCES "SYNONYM"(syno_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_wrtb_fk_ist FOREIGN KEY(mode_wrtb_id)
        REFERENCES wertebereich(wrtb_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MELT_DIAT';
ALTER TABLE melt_diat
    ADD CONSTRAINT modi_melt_fk FOREIGN KEY(medi_melt_id)
        REFERENCES modellelem_typ(melt_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SPRACHTEXT';
ALTER TABLE sprachtext
    ADD CONSTRAINT sptx_mode_fk FOREIGN KEY(sptx_mode_id)
        REFERENCES modellelement(mode_id)
            ON DELETE CASCADE;

--  ERROR: Invalid View WERTEBEREICH_LOV

--  ERROR: Invalid View WERTEBEREICH_NUM

--  ERROR: Invalid View WERTEBEREICH_TEXT

--  ERROR: Invalid View WERTEBEREICH_ZPKT



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   4
-- WARNINGS                                 0
