-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-07-02 22:03:01 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



<<<<<<< Local Changes
=======
CREATE SEQUENCE modm_seq START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE ORDER;

PROMPT CREATING TABLE 'Ansprechpartner';

CREATE TABLE ansprechpartner(
    ansp_id             NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    ansp_orge_id        NUMBER(10)NOT NULL,
    ansp_name           unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
     NOT NULL,
    ansp_vorname        VARCHAR2(60 CHAR)NOT NULL,
    ansp_email          VARCHAR2(200 CHAR)NOT NULL,
    ansp_priv_tel_nr    VARCHAR2(30 CHAR)NULL,
    ansp_gesch_tel_nr   VARCHAR2(30 CHAR)NULL,
        ansp_uc             VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    ansp_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    ansp_um             VARCHAR2(30 BYTE)NULL,
    ansp_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'Ansprechpartner';
ALTER TABLE ansprechpartner
    ADD CONSTRAINT ansp_pk PRIMARY KEY(ansp_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'Ansprechpartner';

ALTER TABLE ansprechpartner
    ADD CONSTRAINT ansp_email_uk UNIQUE(ansp_email)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'ARC';
CREATE TABLE arc(
    arc_id        NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    arc_name      VARCHAR2(60 CHAR)NOT NULL,
    arc_enti_id   NUMBER(10)NOT NULL,
    arc_uc        VARCHAR2(30 BYTE)NOT NULL,
    arc_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    arc_um        VARCHAR2(30 BYTE)NULL,
    arc_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'ARC';
ALTER TABLE arc
    ADD CONSTRAINT arc_pk PRIMARY KEY(arc_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'ARC';

ALTER TABLE arc
    ADD CONSTRAINT arc_uk UNIQUE(arc_enti_id,
                                 arc_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'ATTR_BUSRULE';
CREATE TABLE attr_busrule(
    atbr_id        NUMBER(10)NOT NULL,
    atbr_buru_id   NUMBER(10)NOT NULL,
    atbr_attr_id   NUMBER(10)NOT NULL,
    atbr_uc        VARCHAR2(30 BYTE)NOT NULL,
    atbr_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    atbr_um        VARCHAR2(30 BYTE)NULL,
    atbr_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'ATTR_BUSRULE';
ALTER TABLE attr_busrule
    ADD CONSTRAINT atbr_pk PRIMARY KEY(atbr_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'ATTR_BUSRULE';

>>>>>>> External Changes
ALTER TABLE attr_busrule
    ADD CONSTRAINT atbr_uk UNIQUE(atbr_attr_id,
                                  atbr_buru_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'ATTRIBUT';
CREATE TABLE attribut(
    attr_id                NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    attr_enti_id           NUMBER(10)NOT NULL,
    attr_wrtb_id           NUMBER(10)NOT NULL,
    attr_tech_name         VARCHAR2(60 CHAR)NOT NULL,
    attr_uetx_id_anzname   NUMBER(10)NULL,
    attr_uetx_id_tooltip   NUMBER(10)NULL,
    attr_uetx_id_beschr    NUMBER(10)NULL,
    attr_business_rule     VARCHAR2(4000 CHAR)NULL,
    attr_anz_rhflg         NUMBER(4)NULL,
    attr_deskriptor        VARCHAR2(5 CHAR)NOT NULL
        CHECK(attr_deskriptor IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    attr_pflichtattr       VARCHAR2(5 CHAR)NOT NULL
        CHECK(attr_pflichtattr IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    attr_historisiert      VARCHAR2(5 CHAR)NOT NULL
        CHECK(attr_historisiert IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    attr_wiederholt        VARCHAR2(5 CHAR)NOT NULL
        CHECK(attr_wiederholt IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    attr_sprachabhaengig   VARCHAR2(5 CHAR)NOT NULL
        CHECK(attr_sprachabhaengig IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    attr_verschluesselt    VARCHAR2(5 CHAR)NOT NULL
        CHECK(attr_verschluesselt IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    attr_uc                VARCHAR2(30 BYTE)NOT NULL,
    attr_dc                TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    attr_um                VARCHAR2(30 BYTE)NULL,
    attr_dm                TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING INDEX 'ATTR_WRTB_FK';

CREATE INDEX attr_wrtb_fk ON
    attribut(
        attr_wrtb_id
    ASC);

PROMPT CREATING INDEX 'ATTR_ENTI_FK';

CREATE INDEX attr_enti_fk ON
    attribut(
        attr_enti_id
    ASC);

PROMPT CREATING PRIMARY KEY ON 'ATTRIBUT';
ALTER TABLE attribut
    ADD CONSTRAINT attr_pk PRIMARY KEY(attr_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'ATTRIBUT';

ALTER TABLE attribut
    ADD CONSTRAINT attr_uk UNIQUE(attr_enti_id,
                                  attr_tech_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'AUFGABENBEREICH';
CREATE TABLE aufgabenbereich(
    augb_id               NUMBER(10)NOT NULL,
    augb_uetx_id_name     NUMBER(10)NOT NULL,
    augb_uetx_id_beschr   NUMBER(10)NULL,
    augb_farbcode         VARCHAR2(6 CHAR)NULL
        CONSTRAINT augb_farbcode_chk CHECK(length(augb_farbcode)= 6)NOT DEFERRABLE ENABLE VALIDATE,
    augb_uc               VARCHAR2(30 BYTE)NOT NULL,
    augb_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    augb_um               VARCHAR2(30 BYTE)NULL,
    augb_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'AUFGABENBEREICH';
ALTER TABLE aufgabenbereich
    ADD CONSTRAINT augb_pk PRIMARY KEY(augb_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'AUFGABENBEREICH';

ALTER TABLE aufgabenbereich
    ADD CONSTRAINT augb_name_uk UNIQUE(augb_uetx_id_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'BETREUER';
CREATE TABLE betreuer(
    betr_id        NUMBER(10)NOT NULL,
    betr_mode_id   NUMBER NOT NULL,
    betr_ansp_id   NUMBER(10)NOT NULL,
        betr_uc        VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    betr_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    betr_um        VARCHAR2(30 BYTE)NULL,
    betr_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'BETREUER';
ALTER TABLE betreuer
    ADD CONSTRAINT betr_pk PRIMARY KEY(betr_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'BETREUER';

ALTER TABLE betreuer
    ADD CONSTRAINT betr__un UNIQUE(betr_mode_id,
                                   betr_ansp_id)NOT DEFERRABLE ENABLE VALIDATE;

<<<<<<< Local Changes
								   CREATE TABLE modellelement(
=======
PROMPT CREATING TABLE 'BEZIEHUNG';
CREATE TABLE beziehung(
    bezi_id                        NUMBER(10)NOT NULL,
    bezi_isa_assoc                 VARCHAR2(5 CHAR)NOT NULL,
    bezi_enti_id_von               NUMBER(10)NOT NULL,
    bezi_uetx_id_assoc_von_zu      NUMBER(10)NOT NULL,
    bezi_abbildtyp_von_zu          CHAR(1 CHAR)NOT NULL,
    bezi_pflicht_assoc_von_zu      VARCHAR2(5 CHAR)NOT NULL
        CHECK(bezi_pflicht_assoc_von_zu IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_hist_von_zu               VARCHAR2(5 CHAR)NOT NULL
        CHECK(bezi_hist_von_zu IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_enti_id_zu                NUMBER(10)NOT NULL,
    bezi_uetx_id_assoc_zu_von      NUMBER(10)NOT NULL,
    bezi_abbildtyp_zu_von          CHAR(1 CHAR)NOT NULL,
    "BEZI_PFLICHT_ASSOC_ZU_VON "   VARCHAR2(5 CHAR)NOT NULL
        CHECK("BEZI_PFLICHT_ASSOC_ZU_VON " IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_hist_zu_von               VARCHAR2(5 CHAR)NOT NULL
        CHECK(bezi_hist_zu_von IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    bezi_arc_id                    NUMBER(10)NULL,
        bezi_uc                        VARCHAR2(30 CHAR)AS(user)VIRTUAL NOT NULL,
    bezi_dc                        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    bezi_um                        VARCHAR2(30 BYTE)NULL,
    bezi_dm                        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING CHECK CONSTRAINT ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_isa_ck CHECK((bezi_isa_assoc_ = 'TRUE'
                                      AND bezi_isa_abbildtyp_von_zu = '1'
                                      AND bezi_isa_abbildtyp_zu_von = '1'
                                      AND bezi_pflicht_assoc_von_zu = 'TRUE')
                                     OR(bezi_is_assoc = 'FALSE'))NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'BEZIEHUNG';

ALTER TABLE beziehung
    ADD CONSTRAINT bezi_pk PRIMARY KEY(bezi_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'BUSINESS_RULE';
CREATE TABLE business_rule(
    buru_id               NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    buru_name             VARCHAR2(60 CHAR)NOT NULL,
    buru_regel            VARCHAR2(4000 CHAR)NOT NULL,
    buru_uetx_id_beschr   NUMBER(10)NULL,
    buru_uetx_id_fhlmld   NUMBER(10)NULL,
    buru_uc               VARCHAR2(30 BYTE)NOT NULL,
    buru_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    buru_um               VARCHAR2(30 BYTE)NULL,
    buru_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

COMMENT ON COLUMN business_rule.buru_regel IS
    'Beschreibung der Regel als Funktion, Regexp, SQL-Ausdruck etc.';

PROMPT CREATING PRIMARY KEY ON 'BUSINESS_RULE';
ALTER TABLE business_rule
    ADD CONSTRAINT buru_pk PRIMARY KEY(buru_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'BUSINESS_RULE';

ALTER TABLE business_rule
    ADD CONSTRAINT business_rule_name_un UNIQUE(buru_name)NOT DEFERRABLE ENABLE VALIDATE;

CREATE TABLE entitaet(
    enti_id                 NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    enti_augb_id            NUMBER(10)NULL,
    enti_tech_name          VARCHAR2(60 CHAR)NOT NULL,
    enti_uetx_id_name       NUMBER(10)NOT NULL,
    enti_uetx_id_beschr     NUMBER(10)NULL,
    enti_uetx_id_tooltip    NUMBER(10)NULL,
    enti_uetx_id_kurzname   NUMBER(10)NULL,
    enti_prefix             VARCHAR2(10 CHAR)NULL,
    enti_beispiele          VARCHAR2(4000 CHAR)NULL,
    enti_erw_tupel#         VARCHAR2(10 CHAR)NULL
        CHECK(enti_erw_tupel# IN(
            '1 Mio',
            '100',
            '10000',
            '>100 Mio'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    enti_uc                 VARCHAR2(30 BYTE)NOT NULL,
    enti_dc                 TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    enti_um                 VARCHAR2(30 BYTE)NULL,
    enti_dm                 TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'ENTITAET';
ALTER TABLE entitaet
    ADD CONSTRAINT enti_pk PRIMARY KEY(enti_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'ENTITAET';

ALTER TABLE entitaet
    ADD CONSTRAINT enti_tech_name_uk UNIQUE(enti_tech_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'MODELLELEMENT';
CREATE TABLE modellelement(
>>>>>>> External Changes
    mode_id        NUMBER DEFAULT modm_seq.NEXTVAL NOT NULL,
    mode_wrtb_id   NUMBER(10)NULL,
    mode_attr_id   NUMBER(10)NULL,
    mode_buru_id   NUMBER(10)NULL,
    mode_enti_id   NUMBER(10)NULL,
    mode_uc        VARCHAR2(30 BYTE)NOT NULL,
    mode_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    mode_um        VARCHAR2(30 BYTE)NULL,
    mode_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL,
    mode_orge_id   NUMBER(10)NOT NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING CHECK CONSTRAINT ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_ck_1 CHECK(
        CASE
            WHEN mode_enti_id IS NOT NULL THEN
                1
            ELSE
                0
        END
        +
        CASE
            WHEN mode_buru_id IS NOT NULL THEN
                1
            ELSE
                0
        END
        +
        CASE
            WHEN mode_attr_id IS NOT NULL THEN
                1
            ELSE
                0
        END
        +
        CASE
            WHEN mode_wrtb_id IS NOT NULL THEN
                1
            ELSE
                0
        END
    = 1)NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'MODELLELEMENT';

ALTER TABLE modellelement
    ADD CONSTRAINT mode_pk PRIMARY KEY(mode_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'MODELLELEMENT';

ALTER TABLE modellelement
    ADD CONSTRAINT mode_uk UNIQUE(mode_wrtb_id,
                                  mode_attr_id,
                                  mode_buru_id,
                                  mode_enti_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'ORG_EINH';
CREATE TABLE org_einh(
    orge_id        NUMBER(10)NOT NULL,
    orge_type      VARCHAR2(4)NOT NULL
        CONSTRAINT ch_inh_abte CHECK(orge_type IN(
            'ABTE',
            'FIRM'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    orge_name      VARCHAR2(60 CHAR)NOT NULL,
    orge_email     VARCHAR2(200 CHAR)NULL,
    orge_tel_nr    VARCHAR2(30 CHAR)NULL,
    orge_adresse   VARCHAR2(400 CHAR)NULL,
        orge_uc        VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    orge_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    orge_um        VARCHAR2(30 BYTE)NULL,
    orge_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'ORG_EINH';
ALTER TABLE org_einh
    ADD CONSTRAINT orge_pk PRIMARY KEY(orge_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'ORG_EINH';

ALTER TABLE org_einh
    ADD CONSTRAINT orge_uk UNIQUE(orge_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'PHYS_EINH_UMRECHUNG';
CREATE TABLE phys_einh_umrechung(
    ehur_faktor        NUMBER(20,10)NOT NULL,
    ehur_id            NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    ehur_pheh_id_von   NUMBER(10)NOT NULL,
    ehur_pheh_id_zu    NUMBER(10)NOT NULL,
    ehur_uc            VARCHAR2(30 BYTE)NOT NULL,
    ehur_dc            TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    ehur_um            VARCHAR2(30 BYTE)NULL,
    ehur_dm            TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'PHYS_EINH_UMRECHUNG';
ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_pk PRIMARY KEY(ehur_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'PHYS_EINH_UMRECHUNG';

ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_uk UNIQUE(ehur_pheh_id_von,
                                  ehur_pheh_id_zu)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'PHYS_EINHEIT';
CREATE TABLE phys_einheit(
    pheh_id               NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    pheh_si_einheit       VARCHAR2(10 CHAR)NOT NULL,
    pheh_uetx_id_name     NUMBER(10)NULL,
    pheh_uetx_id_beschr   NUMBER(10)NULL,
    pheh_uc               VARCHAR2(30 BYTE)NOT NULL,
    pheh_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    pheh_um               VARCHAR2(30 BYTE)NULL,
    pheh_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'PHYS_EINHEIT';
ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_pk PRIMARY KEY(pheh_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'PHYS_EINHEIT';

ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uk_si UNIQUE(pheh_si_einheit)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'PHYS_EINHEIT';

ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uk_name UNIQUE(pheh_uetx_id_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'SCHLUESSEL';
CREATE TABLE schluessel(
    schl_id        NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    schl_laufnr    NUMBER(4)NOT NULL,
    schl_enti_id   NUMBER(10)NOT NULL,
    schl_uc        VARCHAR2(30 BYTE)NOT NULL,
    schl_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    schl_um        VARCHAR2(30 BYTE)NULL,
    schl_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'SCHLUESSEL';
ALTER TABLE schluessel
    ADD CONSTRAINT schl_pk PRIMARY KEY(schl_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SCHLUESSEL';

ALTER TABLE schluessel
    ADD CONSTRAINT schl_uk UNIQUE(schl_enti_id,
                                  schl_laufnr)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'SCHLUESSELELEMENT';
CREATE TABLE schluesselelement(
    scel_id        NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    scel_schl_id   NUMBER(10)NOT NULL,
    scel_attr_id   NUMBER(10)NULL,
    scel_bezi_id   NUMBER(10)NULL,
    scel_uc        VARCHAR2(30 BYTE)NOT NULL,
    scel_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    scel_um        VARCHAR2(30 BYTE)NULL,
    scel_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING CHECK CONSTRAINT ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_element_ck CHECK((scel_attr_id IS NOT NULL
                                          AND scel_bezi_id IS NULL)
                                         OR(scel_attr_id IS NULL
                                            AND scel_bezi_id IS NOT NULL))NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'SCHLUESSELELEMENT';

ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_pk PRIMARY KEY(scel_id)NOT DEFERRABLE ENABLE VALIDATE;

--  ERROR: UK name length exceeds maximum allowed length(30) 
PROMPT CREATING UNIQUE KEY ON 'SCHLUESSELELEMENT';

ALTER TABLE schluesselelement
    ADD CONSTRAINT schl_schl_enti_id_schl_laufnr_un UNIQUE(scel_schl_id,
                                                           scel_attr_id,
                                                           scel_bezi_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'SPEICHERFORMAT';
CREATE TABLE speicherformat(
    spfo_id             NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    spfo_name           VARCHAR2(60 CHAR)NOT NULL,
    spfo_beschreibung   VARCHAR2(4000 CHAR)NULL,
    spfo_uc             VARCHAR2(30 BYTE)NOT NULL,
    spfo_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    spfo_um             VARCHAR2(30 BYTE)NULL,
    spfo_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'SPEICHERFORMAT';
ALTER TABLE speicherformat
    ADD CONSTRAINT spfo_pk PRIMARY KEY(spfo_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SPEICHERFORMAT';

ALTER TABLE speicherformat
    ADD CONSTRAINT spfo__un UNIQUE(spfo_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'SYNONYM';
CREATE TABLE "SYNONYM"(
    syno_id             NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    syno_tech_name      VARCHAR2(60 CHAR)NOT NULL,
    syno_uetx_id_name   NUMBER(10)NULL,
    syno_enti_id        NUMBER(10)NOT NULL,
    syno_uc             VARCHAR2(30 BYTE)NOT NULL,
    syno_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    syno_um             VARCHAR2(30 BYTE)NULL,
    syno_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'SYNONYM';
ALTER TABLE "SYNONYM"
    ADD CONSTRAINT syno_pk PRIMARY KEY(syno_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SYNONYM';

ALTER TABLE "SYNONYM"
    ADD CONSTRAINT syno_tech_name_uk UNIQUE(syno_enti_id,
                                            syno_tech_name)NOT DEFERRABLE ENABLE VALIDATE;

CREATE SEQUENCE infra_seq START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE ORDER;

PROMPT CREATING TABLE 'UEBERSETZ_TEXT';

CREATE TABLE uebersetz_text(
    uetx_originaltext   VARCHAR2(4000 CHAR)NOT NULL,
    uetx_id             NUMBER(10)DEFAULT infra_seq.NEXTVAL NOT NULL,
    uetx_spra_id        NUMBER(10)NOT NULL,
    uetx_wrtb_id        NUMBER(10)NULL,
    uetx_uc             VARCHAR2(30 BYTE)NOT NULL,
    uetx_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    uetx_um             VARCHAR2(30 BYTE)NULL,
    uetx_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING INDEX 'UETX_IDX_SPRA';

CREATE INDEX uetx_idx_spra ON
    uebersetz_text(
        uetx_spra_id
    ASC);

PROMPT CREATING INDEX 'UETX_IDX_TXT';

CREATE INDEX uetx_idx_txt ON
    uebersetz_text(
        uetx_wrtb_id
    ASC);

PROMPT CREATING PRIMARY KEY ON 'UEBERSETZ_TEXT';
ALTER TABLE uebersetz_text
    ADD CONSTRAINT uetx_pk PRIMARY KEY(uetx_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'VORGABEWERT';
CREATE TABLE vorgabewert(
    vgwt_id                NUMBER DEFAULT modm_seq.NEXTVAL NOT NULL,
    vgwt_wert              VARCHAR2(100 CHAR)NOT NULL,
    vgwt_sortrhfg          NUMBER(3)NULL,
    vgwt_wrtb_id           NUMBER(10)NOT NULL,
    vgwt_uetx_id_anzeige   NUMBER(10)NULL,
    vgwt_uetx_id_beschr    NUMBER(10)NULL,
    vgwt_uc                VARCHAR2(30 BYTE)NOT NULL,
    vgwt_dc                TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    vgwt_um                VARCHAR2(30 BYTE)NULL,
    vgwt_dm                TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_pk PRIMARY KEY(vgwt_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'VORGABEWERT';

ALTER TABLE vorgabewert
    ADD CONSTRAINT "  VGWT_UK" UNIQUE(vgwt_wrtb_id,
                                      vgwt_wert)NOT DEFERRABLE ENABLE VALIDATE;

CREATE TABLE wertebereich(
    wrtb_id                   NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    wrtb_business_rule        VARCHAR2(4000 CHAR)NULL,
    wrtb_uetx_id_name         NUMBER(10)NOT NULL,
    wrtb_uetx_id_beschr       NUMBER(10)NULL,
    wrtb_typ                  VARCHAR2(4 CHAR)NOT NULL
        CHECK(wrtb_typ IN(
            'BIN',
            'GRP',
            'LOV',
            'NUM',
            'TEXT',
            'ZPKT'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    wrtb_zpkt_minwert         TIMESTAMP NULL,
    wrtb_zpkt_maxwert         TIMESTAMP NULL,
    wrtb_zpkt_granularitaet   VARCHAR2(15 CHAR)NULL
        CHECK(wrtb_zpkt_granularitaet IN(
            'JAHR',
            'MILLISEKUNDE',
            'MINUTE',
            'MONAT',
            'QUARTAL',
            'SEKUNDE',
            'SEMESTER',
            'STUNDE',
            'TAG',
            'WOCHE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    wrtb_text_maxlng          NUMBER(4)NULL,
    wrtb_text_syntaxregel     VARCHAR2(4000 CHAR)NULL,
    wrtb_num_maxwert          NUMBER(30,10)NULL,
    wrtb_num_minwert          NUMBER(30,10)NULL,
    wrtb_num_vorkstellen      NUMBER(2)NULL,
    wrtb_num_nachkstellen     NUMBER(2)DEFAULT 0 NULL,
    wrtb_num_rundng_einh      NUMBER(7,3)NULL
        CHECK(wrtb_num_rundng_einh IN(
            0.001,
            0.01,
            0.05,
            0.1,
            0.25,
            0.5,
            1,
            10,
            100,
            1000
        ))NOT DEFERRABLE ENABLE VALIDATE,
    wrtb_num_pheh_id          NUMBER(10)NULL,
    wrtb_bin_inhalttyp        VARCHAR2(30 CHAR)NULL
        CHECK(wrtb_bin_inhalttyp IN(
            'BILD',
            'FILM',
            'GRAPH',
            'TEXT',
            'TON'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    wrtb_bin_spfo_id          NUMBER(10)NULL,
    wrtb_uc                   VARCHAR2(30 BYTE)NOT NULL,
    wrtb_dc                   TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    wrtb_um                   VARCHAR2(30 BYTE)NULL,
    wrtb_dm                   TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING INDEX 'WRTB_UETX_FK_NAME';

CREATE INDEX wrtb_uetx_fk_name ON
    wertebereich(
        wrtb_uetx_id_name
    ASC);

PROMPT CREATING CHECK CONSTRAINT ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_ck_zpkt CHECK((wrtb_typ = 'ZPKT'
                                       AND wrtb_zpkt_granularitaet IS NOT NULL
                                       AND wrtb_text_maxlng IS NULL
                                       AND wrtb_text_syntaxregel IS NULL
                                       AND wrtb_num_vorkstellen IS NULL
                                       AND wrtb_num_nachkstellen IS NULL
                                       AND wrtb_num_rundng_einh IS NULL
                                       AND wrtb_num_minwert IS NULL
                                       AND wrtb_num_maxwert IS NULL
                                       AND wrtb_num_pheh_id IS NULL
                                       AND wrtb_bin_spfo_id IS NULL
                                       AND wrtb_bin_inhalttyp IS NULL)
                                      OR(wrtb_typ <> 'ZPKT'
                                         AND wrtb_zpkt_granularitaet IS NULL
                                         AND wrtb_zpkt_maxwert IS NULL
                                         AND wrtb_zpkt_minwert IS NULL))NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING CHECK CONSTRAINT ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_ck_lov CHECK((wrtb_typ = 'LOV'
                                      AND wrtb_zpkt_granularitaet IS NULL
                                      AND wrtb_zpkt_maxwert IS NULL
                                      AND wrtb_zpkt_minwert IS NULL
                                      AND wrtb_text_maxlng IS NULL
                                      AND wrtb_text_syntaxregel IS NULL
                                      AND wrtb_num_vorkstellen IS NULL
                                      AND wrtb_num_nachkstellen IS NULL
                                      AND wrtb_num_rundng_einh IS NULL
                                      AND wrtb_num_minwert IS NULL
                                      AND wrtb_num_maxwert IS NULL
                                      AND wrtb_num_pheh_id IS NULL
                                      AND wrtb_bin_spfo_id IS NULL
                                      AND wrtb_bin_inhalttyp IS NULL)
                                     OR(wrtb_typ <> 'LOV'))NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING CHECK CONSTRAINT ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_ck_text CHECK((wrtb_typ = 'TEXT'
                                       AND wrtb_zpkt_granularitaet IS NULL
                                       AND wrtb_zpkt_maxwert IS NULL
                                       AND wrtb_zpkt_minwert IS NULL
                                       AND wrtb_num_vorkstellen IS NULL
                                       AND wrtb_num_nachkstellen IS NULL
                                       AND wrtb_num_rundng_einh IS NULL
                                       AND wrtb_num_minwert IS NULL
                                       AND wrtb_num_maxwert IS NULL
                                       AND wrtb_num_pheh_id IS NULL
                                       AND wrtb_bin_spfo_id IS NULL
                                       AND wrtb_bin_inhalttyp IS NULL)
                                      OR(wrtb_typ <> 'TEXT'))NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING CHECK CONSTRAINT ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_ck_num CHECK((wrtb_typ = 'NUM'
                                      AND wrtb_num_vorkstellen IS NOT NULL
                                      AND wrtb_num_nachkstellen IS NOT NULL
                                      AND wrtb_zpkt_granularitaet IS NULL
                                      AND wrtb_text_maxlng IS NULL
                                      AND wrtb_text_syntaxregel IS NULL)
                                     OR(wrtb_typ <> 'NUM'
                                        AND wrtb_num_vorkstellen IS NULL
                                        AND wrtb_num_nachkstellen IS NULL
                                        AND wrtb_num_rundng_einh IS NULL
                                        AND wrtb_num_minwert IS NULL
                                        AND wrtb_num_maxwert IS NULL
                                        AND wrtb_num_pheh_id IS NULL))NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING CHECK CONSTRAINT ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_ck_grp CHECK((wrtb_typ = 'GRP'
                                      AND wrtb_zpkt_granularitaet IS NULL
                                      AND wrtb_zpkt_maxwert IS NULL
                                      AND wrtb_zpkt_minwert IS NULL
                                      AND wrtb_text_maxlng IS NULL
                                      AND wrtb_text_syntaxregel IS NULL
                                      AND wrtb_num_vorkstellen IS NULL
                                      AND wrtb_num_nachkstellen IS NULL
                                      AND wrtb_num_rundng_einh IS NULL
                                      AND wrtb_num_minwert IS NULL
                                      AND wrtb_num_maxwert IS NULL
                                      AND wrtb_num_pheh_id IS NULL)
                                     OR(wrtb_typ <> 'GRP'))NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING CHECK CONSTRAINT ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_ck_bin CHECK((wrtb_typ = 'BIN'
                                      AND wrtb_bin_inhalttyp IS NOT NULL
                                      AND wrtb_zpkt_granularitaet IS NULL
                                      AND wrtb_zpkt_maxwert IS NULL
                                      AND wrtb_zpkt_minwert IS NULL
                                      AND wrtb_num_vorkstellen IS NULL
                                      AND wrtb_num_nachkstellen IS NULL
                                      AND wrtb_num_rundng_einh IS NULL
                                      AND wrtb_num_minwert IS NULL
                                      AND wrtb_num_maxwert IS NULL
                                      AND wrtb_num_pheh_id IS NULL)
                                     OR(wrtb_typ <> 'BIN'
                                        AND wrtb_bin_spfo_id IS NULL
                                        AND wrtb_bin_inhalttyp IS NULL))NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_pk PRIMARY KEY(wrtb_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'WERTEBEREICH';

ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_name_uk UNIQUE(wrtb_uetx_id_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'WERTEBEREICHGRUPPE';
CREATE TABLE wertebereichgruppe(
    wbgr_id               NUMBER(10)NOT NULL,
    wbgr_wrtb_id_gruppe   NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    wbgr_wrtb_id_member   NUMBER(10)NOT NULL,
    wbgr_uc               VARCHAR2(30 BYTE)NOT NULL,
    wbgr_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    wbgr_um               VARCHAR2(30 BYTE)NULL,
    wbgr_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'WERTEBEREICHGRUPPE';
ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_pk PRIMARY KEY(wbgr_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'WERTEBEREICHGRUPPE';

ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_wrtb_uk UNIQUE(wbgr_wrtb_id_member,
                                       wbgr_wrtb_id_gruppe)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING FOREIGN KEY ON 'Ansprechpartner';
ALTER TABLE ansprechpartner
    ADD CONSTRAINT ansp_orge_fk FOREIGN KEY(ansp_orge_id)
        REFERENCES org_einh(orge_id);

PROMPT CREATING FOREIGN KEY ON 'ARC';
ALTER TABLE arc
    ADD CONSTRAINT arc_enti_fk FOREIGN KEY(arc_enti_id)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ATTR_BUSRULE';
ALTER TABLE attr_busrule
    ADD CONSTRAINT atbr_attr_fk FOREIGN KEY(atbr_attr_id)
        REFERENCES attribut(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ATTR_BUSRULE';
ALTER TABLE attr_busrule
    ADD CONSTRAINT atbr_buru_fk FOREIGN KEY(atbr_buru_id)
        REFERENCES business_rule(buru_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ATTRIBUT';
ALTER TABLE attribut
    ADD CONSTRAINT attr_enti_fk FOREIGN KEY(attr_enti_id)
        REFERENCES entitaet(enti_id);

PROMPT CREATING FOREIGN KEY ON 'ATTRIBUT';
ALTER TABLE attribut
    ADD CONSTRAINT attr_uetx_fk_beschr FOREIGN KEY(attr_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'ATTRIBUT';
ALTER TABLE attribut
    ADD CONSTRAINT attr_uetx_fk_name FOREIGN KEY(attr_uetx_id_anzname)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'ATTRIBUT';
ALTER TABLE attribut
    ADD CONSTRAINT attr_uetx_fk_tooltip FOREIGN KEY(attr_uetx_id_tooltip)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'ATTRIBUT';
ALTER TABLE attribut
    ADD CONSTRAINT attr_wrtb_fk FOREIGN KEY(attr_wrtb_id)
        REFERENCES wertebereich(wrtb_id);

PROMPT CREATING FOREIGN KEY ON 'AUFGABENBEREICH';
ALTER TABLE aufgabenbereich
    ADD CONSTRAINT augb_uetx_fk_beschr FOREIGN KEY(augb_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'AUFGABENBEREICH';
ALTER TABLE aufgabenbereich
    ADD CONSTRAINT augb_uetx_fk_name FOREIGN KEY(augb_uetx_id_name)
        REFERENCES uebersetz_text(uetx_id);

PROMPT CREATING FOREIGN KEY ON 'BETREUER';
ALTER TABLE betreuer
    ADD CONSTRAINT betr_ansp_fk FOREIGN KEY(betr_ansp_id)
        REFERENCES ansprechpartner(ansp_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BETREUER';
ALTER TABLE betreuer
    ADD CONSTRAINT betr_mode_fk FOREIGN KEY(betr_mode_id)
        REFERENCES modellelement(mode_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_arc_fk FOREIGN KEY(bezi_arc_id)
        REFERENCES arc(arc_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_enti_fk_von FOREIGN KEY(bezi_enti_id_von)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BEZIEHUNG';
ALTER TABLE beziehung
    ADD CONSTRAINT bezi_enti_fk_zu FOREIGN KEY(bezi_enti_id_zu)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINH_UMRECHUNG';
ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_fk_von FOREIGN KEY(ehur_pheh_id_von)
        REFERENCES phys_einheit(pheh_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINH_UMRECHUNG';
ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_fk_zu FOREIGN KEY(ehur_pheh_id_zu)
        REFERENCES phys_einheit(pheh_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ENTITAET';
ALTER TABLE entitaet
    ADD CONSTRAINT enti_augb_fk FOREIGN KEY(enti_augb_id)
        REFERENCES aufgabenbereich(augb_id);

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_attr_fk_ist FOREIGN KEY(mode_attr_id)
        REFERENCES attribut(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_buru_fk_ist FOREIGN KEY(mode_buru_id)
        REFERENCES business_rule(buru_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_enti_fk_ist FOREIGN KEY(mode_enti_id)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_orge_fk_verantw FOREIGN KEY(mode_orge_id)
        REFERENCES org_einh(orge_id);

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_wrtb_fk_ist FOREIGN KEY(mode_wrtb_id)
        REFERENCES wertebereich(wrtb_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINHEIT';
ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uetx_fk_beschr FOREIGN KEY(pheh_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINHEIT';
ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uetx_fk_name FOREIGN KEY(pheh_uetx_id_name)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_attr_fk FOREIGN KEY(scel_attr_id)
        REFERENCES attribut(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_bezi_fk FOREIGN KEY(scel_bezi_id)
        REFERENCES beziehung(bezi_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_schl_fk FOREIGN KEY(scel_schl_id)
        REFERENCES schluessel(schl_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSEL';
ALTER TABLE schluessel
    ADD CONSTRAINT schl_enti_fk FOREIGN KEY(schl_enti_id)
        REFERENCES entitaet(enti_id);

PROMPT CREATING FOREIGN KEY ON 'SYNONYM';
ALTER TABLE "SYNONYM"
    ADD CONSTRAINT syno_enti_fk FOREIGN KEY(syno_enti_id)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SYNONYM';
ALTER TABLE "SYNONYM"
    ADD CONSTRAINT syno_uetx_fk_name FOREIGN KEY(syno_uetx_id_name)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'UEBERSETZ_TEXT';
ALTER TABLE uebersetz_text
    ADD CONSTRAINT uetx_spra_fk FOREIGN KEY(uetx_spra_id)
        REFERENCES sprache(spra_id);

PROMPT CREATING FOREIGN KEY ON 'UEBERSETZ_TEXT';
ALTER TABLE uebersetz_text
    ADD CONSTRAINT uetx_wrtb_fk FOREIGN KEY(uetx_wrtb_id)
        REFERENCES wertebereich(wrtb_id);

PROMPT CREATING FOREIGN KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_uetx_fk_anzeige FOREIGN KEY(vgwt_uetx_id_anzeige)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_uetx_fk_beschr FOREIGN KEY(vgwt_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_wrtb_fk FOREIGN KEY(vgwt_wrtb_id)
        REFERENCES wertebereich(wrtb_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICHGRUPPE';
ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_wrtb_fk_gruppe FOREIGN KEY(wbgr_wrtb_id_gruppe)
        REFERENCES wertebereich(wrtb_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICHGRUPPE';
ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_wrtb_fk_membecr FOREIGN KEY(wbgr_wrtb_id_member)
        REFERENCES wertebereich(wrtb_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_phys_einheit_fk FOREIGN KEY(wrtb_num_pheh_id)
        REFERENCES phys_einheit(pheh_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_spfo_fk FOREIGN KEY(wrtb_bin_spfo_id)
        REFERENCES speicherformat(spfo_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_uetx_fk_beschr FOREIGN KEY(wrtb_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_uetx_fk_name FOREIGN KEY(wrtb_uetx_id_name)
        REFERENCES uebersetz_text(uetx_id);

--  ERROR: Invalid View WERTEBEREICH_LOV 

PROMPT CREATING VIEW 'WERTEBEREICH_LOV';
CREATE OR REPLACE NOFORCE VIEW WERTEBEREICH_LOV  AS
SELECT
    wertebereich.wrtb_id,
    wertebereich.wrtb_business_rule,
    uetx_name.uetx_originaltext as WRTB_NAME,
    wertebereich.wrtb_uetx_id_name,
    uetx_beschr.uetx_originaltext as WRTB_BESCHR,
    wertebereich.wrtb_uetx_id_beschr
FROM
    wertebereich
    LEFT JOIN uebersetz_text uetx_name ON uetx_name.uetx_id = wertebereich.wrtb_uetx_id_name                              
    left JOIN uebersetz_text uetx_beschr ON uetx_beschr.uetx_id = wertebereich.wrtb_uetx_id_beschr 
WHERE wrtb_typ = 'LOV' 
;

--  ERROR: Invalid View WERTEBEREICH_NUM 

PROMPT CREATING VIEW 'WERTEBEREICH_NUM';
CREATE OR REPLACE NOFORCE VIEW WERTEBEREICH_NUM  AS
SELECT
    wertebereich.wrtb_id,
    wertebereich.wrtb_business_rule,
    uetx_name.uetx_originaltext as WRTB_NAME,
    wertebereich.wrtb_uetx_id_name,
    uetx_beschr.uetx_originaltext as WRTB_BESCHR,
    wertebereich.wrtb_uetx_id_beschr,
    wertebereich.wrtb_num_maxwert,
    wertebereich.wrtb_num_minwert,
    wertebereich.wrtb_num_vorkstellen,
    wertebereich.wrtb_num_nachkstellen,
    wertebereich.wrtb_num_rundng_einh,
    wertebereich.werb_num_pheh_id
FROM
    wertebereich
    LEFT JOIN uebersetz_text uetx_name ON uetx_name.uetx_id = wertebereich.wrtb_uetx_id_name                              
    left JOIN uebersetz_text uetx_beschr ON uetx_beschr.uetx_id = wertebereich.wrtb_uetx_id_beschr 
WHERE wrtb_typ = 'NUM' 
;

--  ERROR: Invalid View WERTEBEREICH_TEXT 

PROMPT CREATING VIEW 'WERTEBEREICH_TEXT';
CREATE OR REPLACE NOFORCE VIEW WERTEBEREICH_TEXT  AS
SELECT
    wertebereich.wrtb_id,
    wertebereich.wrtb_business_rule,
    uetx_name.uetx_originaltext as WRTB_NANE,
    wertebereich.wrtb_uetx_id_name,
    uetx_beschr.uetx_originaltext as WRTB_BESCHR,
    wertebereich.wrtb_uetx_id_beschr,
    wertebereich.wrtb_text_maxlng,
    wertebereich.werb_text_syntaxregel
FROM
    wertebereich
    LEFT JOIN uebersetz_text uetx_name ON uetx_name.uetx_id = wertebereich.wrtb_uetx_id_name                              
    left JOIN uebersetz_text uetx_beschr ON uetx_beschr.uetx_id = wertebereich.wrtb_uetx_id_beschr 
WHERE wrtb_typ = 'TEXT' 
;

--  ERROR: Invalid View WERTEBEREICH_ZPKT 

PROMPT CREATING VIEW 'WERTEBEREICH_ZPKT';
CREATE OR REPLACE NOFORCE VIEW WERTEBEREICH_ZPKT  AS
SELECT
    wertebereich.wrtb_id,
    wertebereich.wrtb_business_rule,
    uetx_name.uetx_originaltext as WRTB_NAME,
    wertebereich.wrtb_uetx_id_name,
    uetx_beschr.uetx_originaltext as WRTB_BESCHR,
    wertebereich.wrtb_uetx_id_beschr,
    wertebereich.wrtb_zpkt_maxwert,
    wertebereich.wrtb_zpkt_minwert,
    wertebereich.wrtb_zpkt_granularitaet
FROM
    wertebereich
    LEFT JOIN uebersetz_text uetx_name ON uetx_name.uetx_id = wertebereich.wrtb_uetx_id_name                              
    left JOIN uebersetz_text uetx_beschr ON uetx_beschr.uetx_id = wertebereich.wrtb_uetx_id_beschr 
WHERE wrtb_typ = 'ZPKT' 
;

CREATE OR REPLACE TRIGGER wbgr BEFORE
    INSERT ON wertebereichgruppe
    FOR EACH ROW
    WHEN(new.wbgr_id IS NULL)
BEGIN
    :new.wbgr_id := modm_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            21
-- CREATE INDEX                             5
-- ALTER TABLE                             93
-- CREATE VIEW                              4
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   6
-- WARNINGS                                 0
