-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-08-21 17:39:07 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



--  Position auf einem Element, an der die Linie andockt.
--  Relativ: Richtung und %-Längepostion auf der Kurve in diese Richtung


--  Irgend eine Komponente die mit Informations Technologie zu tun hat und
--  beschafft, betrieben und betreut  werden muss.
--  Jede IT-Komponente hat einen Hersteller. D.h. es handelt sich um konkrete
--  Produkte.
PROMPT CREATING TABLE 'DATATYPES';

CREATE TABLE datatypes(
    daty_id         NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    daty_name       VARCHAR2(60 CHAR)NOT NULL,
    daty_grundtyp   VARCHAR2(60 CHAR)NOT NULL
        CONSTRAINT ck_itko_itko_typ CHECK(daty_grundtyp IN(
            'BINARY',
            'NUMBER',
            'TEXT',
            'ZEIT'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    daty_odm_guid   VARCHAR2(40)NULL
        CONSTRAINT ck_itko_itko_typ CHECK(daty_odm_guid IN(
            'ANWEN',
            'DBMS',
            'SERV'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    daty_uc         VARCHAR2(30 BYTE)NOT NULL,
    daty_dc         TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    daty_um         VARCHAR2(30 BYTE)NULL,
    daty_dm         TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'DATATYPES';
ALTER TABLE datatypes
    ADD CONSTRAINT itko_pk PRIMARY KEY(daty_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'DATATYPES';

ALTER TABLE datatypes
    ADD CONSTRAINT daty_un UNIQUE(daty_name)NOT DEFERRABLE ENABLE VALIDATE;

--  Irgend eine Komponente die mit Informations Technologie zu tun hat und
--  beschafft, betrieben und betreut  werden muss.
--  Jede IT-Komponente hat einen Hersteller. D.h. es handelt sich um konkrete
--  Produkte.
PROMPT CREATING TABLE 'IT_KOMPONENTE';
CREATE TABLE it_komponente(
    itko_id             NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    itko_typ            VARCHAR2(5 CHAR)NOT NULL
        CONSTRAINT ck_itko_itko_typ CHECK(itko_typ IN(
            'ANWEN',
            'DBMS',
            'SERV'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    itko_anwend_typ     VARCHAR2(10 CHAR)NULL
        CONSTRAINT ck_itko_itko_anwend_typ CHECK(itko_anwend_typ IN(
            'EXTERN',
            'LOKAL',
            'ZENTRAL'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    itko_name           VARCHAR2(60 CHAR)NOT NULL, 
--  Anwendungsgebiet (ERP, PIM, FiBu etc.)
    itko_zweck          VARCHAR2(4000 CHAR)NULL,
    itko_zeichensatz    VARCHAR2(60 CHAR)NULL, 
--  Ist dies eine physische Maschine oder ein genutzte virtuelle?
    itko_ist_virtuell   VARCHAR2(5 CHAR)DEFAULT 'FALSE' NOT NULL
        CONSTRAINT ck_itko_itko_ist_virtuell CHECK(itko_ist_virtuell IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
        itko_uc             VARCHAR2(30 BYTE)AS(user)VIRTUAL NOT NULL,
    itko_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    itko_um             VARCHAR2(30 BYTE)NULL,
    itko_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

ALTER TABLE it_komponente
    ADD CONSTRAINT itko_exdep1 CHECK(itko_typ != 'ANWEN'
                                     OR(itko_zeichensatz IS NULL));

ALTER TABLE it_komponente
    ADD CONSTRAINT itko_exdep2 CHECK(itko_typ != 'DBMS'
                                     OR(itko_anwend_typ IS NULL));

ALTER TABLE it_komponente
    ADD CONSTRAINT itko_exdep3 CHECK(itko_typ != 'SERV'
                                     OR(itko_anwend_typ IS NULL
                                        AND itko_zeichensatz IS NULL));

COMMENT ON COLUMN it_komponente.itko_anwend_typ IS
    'Umgebungstyp der Anwendung';

PROMPT CREATING PRIMARY KEY ON 'IT_KOMPONENTE';
ALTER TABLE it_komponente
    ADD CONSTRAINT itko_pkv3 PRIMARY KEY(itko_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'IT_KOMPONENTE';

ALTER TABLE it_komponente
    ADD CONSTRAINT itko_itko_typ_itko_name_un UNIQUE(itko_typ,
                                                     itko_name)NOT DEFERRABLE ENABLE VALIDATE;

--  Wert, der für eine Aufzählungs-Domäne ein gültiger Wert ist.
--  Das Attribut "Wert" ist der physikalische (sprachunabhängige) Wert, der als
--  eigentliche Wert im konzeptionellen Modell gilt. 
PROMPT CREATING TABLE 'MODELLELEMENT';
CREATE TABLE modellelement(
    mode_id        NUMBER DEFAULT modm_seq.NEXTVAL NOT NULL,
    mode_wrtb_id   NUMBER(10)NULL,
    mode_attr_id   NUMBER(10)NULL,
    mode_buru_id   NUMBER(10)NULL,
    mode_enti_id   NUMBER(10)NULL,
    mode_uc        VARCHAR2(30 BYTE)NOT NULL,
    mode_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    mode_um        VARCHAR2(30 BYTE)NULL,
    mode_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL,
    mode_orge_id   NUMBER(10)NOT NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING CHECK CONSTRAINT ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_ck_1 CHECK(
        CASE
            WHEN mode_enti_id IS NOT NULL THEN
                1
            ELSE
                0
        END
        +
        CASE
            WHEN mode_buru_id IS NOT NULL THEN
                1
            ELSE
                0
        END
        +
        CASE
            WHEN mode_attr_id IS NOT NULL THEN
                1
            ELSE
                0
        END
        +
        CASE
            WHEN mode_wrtb_id IS NOT NULL THEN
                1
            ELSE
                0
        END
    = 1)NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'MODELLELEMENT';

ALTER TABLE modellelement
    ADD CONSTRAINT mode_pk PRIMARY KEY(mode_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'MODELLELEMENT';

ALTER TABLE modellelement
    ADD CONSTRAINT mode_uk UNIQUE(mode_wrtb_id,
                                  mode_attr_id,
                                  mode_buru_id,
                                  mode_enti_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'PHYS_EINH_UMRECHUNG';
CREATE TABLE phys_einh_umrechung(
    ehur_faktor        NUMBER(20,10)NOT NULL,
    ehur_id            NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    ehur_pheh_id_von   NUMBER(10)NOT NULL,
    ehur_pheh_id_zu    NUMBER(10)NOT NULL,
    ehur_uc            VARCHAR2(30 BYTE)NOT NULL,
    ehur_dc            TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    ehur_um            VARCHAR2(30 BYTE)NULL,
    ehur_dm            TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'PHYS_EINH_UMRECHUNG';
ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_pk PRIMARY KEY(ehur_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'PHYS_EINH_UMRECHUNG';

ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_uk UNIQUE(ehur_pheh_id_von,
                                  ehur_pheh_id_zu)NOT DEFERRABLE ENABLE VALIDATE;

--  Physikalische Messeinheit .
--  Siehe dazu z.B.
--  https://de.wikipedia.org/wiki/Liste_physikalischer_Größen#SI-Basisgrößen_und
--  -einheiten
PROMPT CREATING TABLE 'PHYS_EINHEIT';
CREATE TABLE phys_einheit(
    pheh_id               NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL, 
--  Einheit gemäss SI-Vorgabe
    pheh_si_einheit       VARCHAR2(10 CHAR)NOT NULL,
    pheh_uetx_id_name     NUMBER(10)NULL,
    pheh_uetx_id_beschr   NUMBER(10)NULL,
    pheh_uc               VARCHAR2(30 BYTE)NOT NULL,
    pheh_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    pheh_um               VARCHAR2(30 BYTE)NULL,
    pheh_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'PHYS_EINHEIT';
ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_pk PRIMARY KEY(pheh_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'PHYS_EINHEIT';

ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uk_name UNIQUE(pheh_uetx_id_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'PHYS_EINHEIT';

ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uk_si UNIQUE(pheh_si_einheit)NOT DEFERRABLE ENABLE VALIDATE;

--  Gruppe von identifizierenden Beziehungen und oder Attributen einer Entität.
--  Jede Kombination von Werten in einem Schlüssel ist für die Entität
--  einmalig. 
--  D.h. sie identifiziert genau 1 Eintrag in der Entität.
--  Die Laufnummer ist ein Hilfsmittel. Genau genommen ist für einen Schlüssel
--  nur eindeutig
--  Entität + Menge aller Schlüsselelemente.
PROMPT CREATING TABLE 'SCHLUESSEL';
CREATE TABLE schluessel(
    schl_id        NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL, 
--  Schlüssel einer Entität müssen durch ein Merkmal unterscheidbar werden.
    schl_laufnr    NUMBER(4)NOT NULL,
    schl_enti_id   NUMBER(10)NOT NULL,
    schl_uc        VARCHAR2(30 BYTE)NOT NULL,
    schl_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    schl_um        VARCHAR2(30 BYTE)NULL,
    schl_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'SCHLUESSEL';
ALTER TABLE schluessel
    ADD CONSTRAINT schl_pk PRIMARY KEY(schl_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SCHLUESSEL';

ALTER TABLE schluessel
    ADD CONSTRAINT schl_uk UNIQUE(schl_enti_id,
                                  schl_laufnr)NOT DEFERRABLE ENABLE VALIDATE;

--  Gruppe von identifizierenden Beziehungen und oder Attributen einer Entität.
--  Jede Kombination von Werten in einem Schlüssel ist für die Entität
--  einmalig. 
--  D.h. sie identifiziert genau 1 Eintrag in der Entität.
--  Die Laufnummer ist ein Hilfsmittel. Genau genommen ist für einen Schlüssel
--  nur eindeutig
--  Entität + Menge aller Schlüsselelemente.
PROMPT CREATING TABLE 'SCHLUESSELELEMENT';
CREATE TABLE schluesselelement(
    scel_id        NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    scel_schl_id   NUMBER(10)NOT NULL, 
--  Schlüssel einer Entität müssen durch ein Merkmal unterscheidbar werden.
    scel_attr_id   NUMBER(10)NULL, 
--  Schlüssel einer Entität müssen durch ein Merkmal unterscheidbar werden.
    scel_bezi_id   NUMBER(10)NULL,
    scel_uc        VARCHAR2(30 BYTE)NOT NULL,
    scel_dc        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    scel_um        VARCHAR2(30 BYTE)NULL,
    scel_dm        TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING CHECK CONSTRAINT ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_element_ck CHECK((scel_attr_id IS NOT NULL
                                          AND scel_bezi_id IS NULL)
                                         OR(scel_attr_id IS NULL
                                            AND scel_bezi_id IS NOT NULL))NOT DEFERRABLE ENABLE VALIDATE;
PROMPT CREATING PRIMARY KEY ON 'SCHLUESSELELEMENT';

ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_pk PRIMARY KEY(scel_id)NOT DEFERRABLE ENABLE VALIDATE;

--  ERROR: UK name length exceeds maximum allowed length(30) 
PROMPT CREATING UNIQUE KEY ON 'SCHLUESSELELEMENT';

ALTER TABLE schluesselelement
    ADD CONSTRAINT schl_schl_enti_id_schl_laufnr_un UNIQUE(scel_schl_id,
                                                           scel_attr_id,
                                                           scel_bezi_id)NOT DEFERRABLE ENABLE VALIDATE;

--  Eine definierte Schnittstelle zwischen 2 IT-Systemen.
--  Synchron heisst, dass die Daten immer in kurzer Zeit (ms - einige Sekunden)
--   nachgeführt und aktuell sind.
--  Manuell bedeutet, dass eine Person die Daten von einem Werkzeuge in ein
--  anderes überträgt (copy-paste, abschreiben).
--  online bedeutet, dass die Anwendungen direkt auf die Datenbasis (Datei, DB)
--  einer anderen Anwendung zugreift. Z.B. via DB-Link, Service. 
PROMPT CREATING TABLE 'SCHNITTSTELLE';
CREATE TABLE schnittstelle(
    schn_id              NUMBER(10)NOT NULL,
    schn_itko_id         NUMBER(10)NOT NULL, 
--  Daten werden manuell übertragen (copy-paste, filetransfer)
    schn_manuell         VARCHAR2(5 CHAR)NOT NULL
        CHECK(schn_manuell IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE, 
--  Daten werden sofort übertragen oder in Paketen die irgendwann übertragen
--  werden.
    schn_synchron        VARCHAR2(5 CHAR)NOT NULL
        CHECK(schn_synchron IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE, 
--  Nein bedeutet Daten gehen nur von "von" zu "nach"
    schn_bidirektional   VARCHAR2(5 CHAR)NOT NULL
        CHECK(schn_bidirektional IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE, 
--  Daten über eine onlineschnittstelle direkt genutzt. Z.B. SQL via DB-Link
    schn_online          VARCHAR2(5 CHAR)NOT NULL
        CHECK(schn_online IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    schn_ausl_period     NUMBER(5)NULL,
    schn_uc              VARCHAR2(30 BYTE)NOT NULL,
    schn_dc              TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    schn_um              VARCHAR2(30 BYTE)NULL,
    schn_dm              TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

COMMENT ON COLUMN schnittstelle.schn_ausl_period IS
    'Periodizität mit der die Schnittstelle bedient/abgeholt wird. Standardvorgabe für alle Attribute einer Schnittstelle.';

PROMPT CREATING PRIMARY KEY ON 'SCHNITTSTELLE';
ALTER TABLE schnittstelle
    ADD CONSTRAINT schn_pk PRIMARY KEY(schn_id)NOT DEFERRABLE ENABLE VALIDATE;

--  Format für die Speicherung binär verkodeter Werte.
--  Beispiele:
--  GIF
--  TIFF
--  JPEG
--  DOC
--  DOCX
--  SVG
--  PDF
PROMPT CREATING TABLE 'SPEICHERFORMAT';
CREATE TABLE speicherformat(
    spfo_id             NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    spfo_name           VARCHAR2(60 CHAR)NOT NULL,
    spfo_beschreibung   VARCHAR2(4000 CHAR)NULL,
    spfo_uc             VARCHAR2(30 BYTE)NOT NULL,
    spfo_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    spfo_um             VARCHAR2(30 BYTE)NULL,
    spfo_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'SPEICHERFORMAT';
ALTER TABLE speicherformat
    ADD CONSTRAINT spfo_pk PRIMARY KEY(spfo_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SPEICHERFORMAT';

ALTER TABLE speicherformat
    ADD CONSTRAINT spfo__un UNIQUE(spfo_name)NOT DEFERRABLE ENABLE VALIDATE;

--  Wert, der für eine Aufzählungs-Domäne ein gültiger Wert ist.
--  Das Attribut "Wert" ist der physikalische (sprachunabhängige) Wert, der als
--  eigentliche Wert im konzeptionellen Modell gilt. 
PROMPT CREATING TABLE 'VORGABEWERT';
CREATE TABLE vorgabewert(
    vgwt_id                NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL, 
--  Ein Wert den ein Attribut annehmen kann.
    vgwt_wert              VARCHAR2(100 CHAR)NOT NULL, 
--  Zahl nach der die Werte in einer Anzeige aufsteigend sortiert werden. Leer
--  -> Wert kommt an den Schluss der Liste in zufälliger Reihenfolge
    vgwt_sortrhfg          NUMBER(3)NULL,
    vgwt_wrtb_id           NUMBER(10)NOT NULL,
    vgwt_uetx_id_anzeige   NUMBER(10)NULL,
    vgwt_uetx_id_beschr    NUMBER(10)NULL,
    vgwt_uc                VARCHAR2(30 BYTE)NOT NULL,
    vgwt_dc                TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    vgwt_um                VARCHAR2(30 BYTE)NULL,
    vgwt_dm                TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_pk PRIMARY KEY(vgwt_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'VORGABEWERT';

ALTER TABLE vorgabewert
    ADD CONSTRAINT "  VGWT_UK" UNIQUE(vgwt_wrtb_id,
                                      vgwt_wert)NOT DEFERRABLE ENABLE VALIDATE;

--  Es gibt Attribute, die aus mehreren Bestandteilen bestehen, aber für eine
--  Entität wie ein Attribut angesehen werden (können).
--  Die Bestandteile dieser Attributgruppe treten immer gemeinsam auf.
--  Dass ein Attribut Teilwerte enthält, für die man sich separat interessiert,
--  verletzt im Grundsatz die 1. Normalform. Wenn aber die Elemente einer
--  Attributgruppe selber Attribute sind und die Gruppe als Platzhalter von
--  mehreren Attributen verstanden werden kann, ist diese Verletzung auflösbar.
--  Beispiele:
--  Telefon-Nr: bestehend aus Landesvorwahl und Rufnummer
--  Koordinaten bestehend aus X und Y-Koordinate (bzw. Westliche länge und
--  nördliche Breite)
--  Hotelzimmer-Nr bestehend aus Stockwerk und ZimmerNr (ACHTUNG: nicht 1.
--  Stelle = Stockwerk, sondern 1 Feld Stockwerk und 1 Feld ZimmerNr)
--  Flugkennung bestehend aus Fluggesellschaft kürzel und Flugnummer (LX 247)
PROMPT CREATING TABLE 'WERTEBEREICHGRUPPE';
CREATE TABLE wertebereichgruppe(
    wbgr_id               NUMBER(10)NOT NULL,
    wbgr_wrtb_id_gruppe   NUMBER(10)DEFAULT modm_seq.NEXTVAL NOT NULL,
    wbgr_wrtb_id_member   NUMBER(10)NOT NULL,
    wbgr_uc               VARCHAR2(30 BYTE)NOT NULL,
    wbgr_dc               TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    wbgr_um               VARCHAR2(30 BYTE)NULL,
    wbgr_dm               TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING PRIMARY KEY ON 'WERTEBEREICHGRUPPE';
ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_pk PRIMARY KEY(wbgr_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'WERTEBEREICHGRUPPE';

ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_wrtb_uk UNIQUE(wbgr_wrtb_id_member,
                                       wbgr_wrtb_id_gruppe)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING FOREIGN KEY ON 'ANSPRECHPARTNER';
ALTER TABLE ansprechpartner
    ADD CONSTRAINT ansp_orge_fk FOREIGN KEY(ansp_orge_id)
        REFERENCES org_einh(orge_id);

PROMPT CREATING FOREIGN KEY ON 'ATTR_TRANSF';
ALTER TABLE attr_transf
    ADD CONSTRAINT attf_attr_fk FOREIGN KEY(attf_attr_id)
        REFERENCES attributes(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'ATTR_TRANSF';
ALTER TABLE attr_transf
    ADD CONSTRAINT attf_scha_fk FOREIGN KEY(attf_scha_id)
        REFERENCES schnittstelle_attr(scha_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BETREUER';
ALTER TABLE betreuer
    ADD CONSTRAINT betr_ansp_fk FOREIGN KEY(betr_ansp_id)
        REFERENCES ansprechpartner(ansp_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'BETREUER';
ALTER TABLE betreuer
    ADD CONSTRAINT betr_mode_fk FOREIGN KEY(betr_mode_id)
        REFERENCES modellelement(mode_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINH_UMRECHUNG';
ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_fk_von FOREIGN KEY(ehur_pheh_id_von)
        REFERENCES phys_einheit(pheh_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINH_UMRECHUNG';
ALTER TABLE phys_einh_umrechung
    ADD CONSTRAINT ehur_fk_zu FOREIGN KEY(ehur_pheh_id_zu)
        REFERENCES phys_einheit(pheh_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_attr_fk_ist FOREIGN KEY(mode_attr_id)
        REFERENCES attributes(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_buru_fk_ist FOREIGN KEY(mode_buru_id)
        REFERENCES business_rule(buru_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_enti_fk_ist FOREIGN KEY(mode_enti_id)
        REFERENCES entitaet(enti_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_orge_fk_verantw FOREIGN KEY(mode_orge_id)
        REFERENCES org_einh(orge_id);

PROMPT CREATING FOREIGN KEY ON 'MODELLELEMENT';
ALTER TABLE modellelement
    ADD CONSTRAINT mode_wrtb_fk_ist FOREIGN KEY(mode_wrtb_id)
        REFERENCES wertebereich(wrtb_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINHEIT';
ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uetx_fk_beschr FOREIGN KEY(pheh_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'PHYS_EINHEIT';
ALTER TABLE phys_einheit
    ADD CONSTRAINT pheh_uetx_fk_name FOREIGN KEY(pheh_uetx_id_name)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_attr_fk FOREIGN KEY(scel_attr_id)
        REFERENCES attributes(attr_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_bezi_fk FOREIGN KEY(scel_bezi_id)
        REFERENCES beziehung(bezi_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSELELEMENT';
ALTER TABLE schluesselelement
    ADD CONSTRAINT scel_schl_fk FOREIGN KEY(scel_schl_id)
        REFERENCES schluessel(schl_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'SCHNITTSTELLE_ATTR';
ALTER TABLE schnittstelle_attr
    ADD CONSTRAINT scha_daty_fk FOREIGN KEY(scha_daty_id)
        REFERENCES datatypes(daty_id);

PROMPT CREATING FOREIGN KEY ON 'SCHNITTSTELLE_ATTR';
ALTER TABLE schnittstelle_attr
    ADD CONSTRAINT scha_schn_fk FOREIGN KEY(scha_schn_id)
        REFERENCES schnittstelle(schn_id);

PROMPT CREATING FOREIGN KEY ON 'SCHLUESSEL';
ALTER TABLE schluessel
    ADD CONSTRAINT schl_enti_fk FOREIGN KEY(schl_enti_id)
        REFERENCES entitaet(enti_id);

PROMPT CREATING FOREIGN KEY ON 'SCHNITTSTELLE';
ALTER TABLE schnittstelle
    ADD CONSTRAINT schn_itko_fk FOREIGN KEY(schn_itko_id)
        REFERENCES it_komponente(itko_id);

PROMPT CREATING FOREIGN KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_uetx_fk_anzeige FOREIGN KEY(vgwt_uetx_id_anzeige)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_uetx_fk_beschr FOREIGN KEY(vgwt_uetx_id_beschr)
        REFERENCES uebersetz_text(uetx_id)
            ON DELETE SET NULL;

PROMPT CREATING FOREIGN KEY ON 'VORGABEWERT';
ALTER TABLE vorgabewert
    ADD CONSTRAINT vgwt_wrtb_fk FOREIGN KEY(vgwt_wrtb_id)
        REFERENCES wertebereich(wrtb_id)
            ON DELETE CASCADE;

PROMPT CREATING FOREIGN KEY ON 'VGWERT_TRANSFORMATION';
ALTER TABLE vgwert_transformation
    ADD CONSTRAINT vwtr_schn_fk FOREIGN KEY(vwtr_schn_id)
        REFERENCES schnittstelle(schn_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICHGRUPPE';
ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_wrtb_fk_gruppe FOREIGN KEY(wbgr_wrtb_id_gruppe)
        REFERENCES wertebereich(wrtb_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICHGRUPPE';
ALTER TABLE wertebereichgruppe
    ADD CONSTRAINT wbgr_wrtb_fk_membecr FOREIGN KEY(wbgr_wrtb_id_member)
        REFERENCES wertebereich(wrtb_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_phys_einheit_fk FOREIGN KEY(wrtb_num_pheh_id)
        REFERENCES phys_einheit(pheh_id);

PROMPT CREATING FOREIGN KEY ON 'WERTEBEREICH';
ALTER TABLE wertebereich
    ADD CONSTRAINT wrtb_spfo_fk FOREIGN KEY(wrtb_bin_spfo_id)
        REFERENCES speicherformat(spfo_id);

CREATE OR REPLACE TRIGGER wbgr BEFORE
    INSERT ON wertebereichgruppe
    FOR EACH ROW
    WHEN(new.wbgr_id IS NULL)
BEGIN
    :new.wbgr_id := modm_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             56
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   1
-- CREATE STRUCTURED TYPE                   7
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0
