-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-07-02 18:20:40 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE TABLE speicherformat(
    spfo_id             integer primary key autoincrement,
    spfo_name           varchar(60) NOT NULL,
    spfo_beschreibung   varchar(4000),
    spfo_uc             varchar(30),
    spfo_dc             varchar(30),
    spfo_um             varchar(30),
    spfo_dm             varchar(30),
	constraint spfo_uk (spfo_name)
);
CREATE TABLE sprache(
    spra_id                integer primary key autoincrement,
    spra_iso_name          varchar(60) NOT NULL,
    spra_iso_code2         CHAR(2) NOT NULL,
    spra_iso_code3         CHAR(3) NOT NULL,
    spra_ist_textsprache   varchar(5) NOT NULL,
    spra_ist_modellsprache   varchar(5) NOT NULL,
    spra_spra_id           integer,
    spra_uc                varchar(30) NOT NULL,
    spra_dc                varchar(30) NOT NULL,
    spra_um                varchar(30) ,
    spra_dm                varchar(30),
    constraint spra_txt_bool CHECK(spra_ist_textsprache IN(
        'FALSE',
        'TRUE'
    )),
    constraint spra_mod_bool CHECK(spra_ist_modellsprache IN(
        'FALSE',
        'TRUE'
    )),
    constraint spra_iso3_low CHECK(spra_iso_code3 = lower(spra_iso_code3)),
    constraint spra_iso2_low CHECK(spra_iso_code2 = lower(spra_iso_code2)),
	constraint spra_iso_uk unique (spra_iso_name),
	constraint spra_iso2_uk unique (spra_iso_code2),
	constraint spra_iso3_uk unique (spra_iso_code3)
);


CREATE TABLE sprachtext(
    sptx_id           integer primary key autoincrement,
	sptx_attrname	  varchar(30) NOT NULL,
    sptx_text         varchar(4000) NOT NULL,
    sptx_spra_id      integer,
    sptx_mode_id      integer NOT NULL,
    sptx_uc           varchar(30) NOT NULL,
    sptx_dc           varchar(30) NOT NULL,
    sptx_um           varchar(30) ,
    sptx_dm           varchar(30),
	constraint sptx_attrnameUC check(sptx_attrname = upper(sptx_attrname)),
	constraint sptx_uk unique (sptx_attrname,sptx_spra_id,sptx_mode_id),
    CONSTRAINT sptx_mode_fk FOREIGN KEY(sptx_mode_id)
									   REFERENCES modellelement(mode_id),
	CONSTRAINT sptx_spra_fk FOREIGN KEY(sptx_spra_id)
									   REFERENCES sprache(spra_id)	
);

