-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-07-02 18:20:40 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE TABLE speicherformat(
    spfo_id             integer primary key autoincrement,
    spfo_name           varchar(60) unique NOT NULL,
    spfo_beschreibung   varchar(4000),
    spfo_uc             varchar(30),
    spfo_dc             TEXT,
    spfo_um             varchar(30),
    spfo_dm             TEXT
)
;
CREATE TABLE sprache(
    spra_iso_name          varchar(60)NULL,
    spra_uetx_id_name      integer
    spra_iso_code2         CHAR(2)NOT NULL
        CHECK(spra_iso_code2 = lower(spra_iso_code2))NOT DEFERRABLE ENABLE VALIDATE,
    spra_iso_code3         CHAR(3)NOT NULL
        CHECK(spra_iso_code3 = lower(spra_iso_code3))NOT DEFERRABLE ENABLE VALIDATE,
    spra_ist_textsprache   varchar(5)NOT NULL
        CHECK(spra_ist_textsprache IN(
            'FALSE',
            'TRUE'
        ))NOT DEFERRABLE ENABLE VALIDATE,
    spra_id                integer
    spra_spra_id           integer
    spra_uc                varchar(30 BYTE)NOT NULL,
    spra_dc                TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    spra_um                varchar(30 BYTE)NULL,
    spra_dm                TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING INDEX 'SPRA__IDX';

CREATE INDEX spra__idx ON
    sprache(
        spra_spra_id
    ASC);

PROMPT CREATING PRIMARY KEY ON 'SPRACHE';
ALTER TABLE sprache
    ADD CONSTRAINT spra_pk PRIMARY KEY(spra_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SPRACHE';

ALTER TABLE sprache
    ADD CONSTRAINT spra_iso_name_un UNIQUE(spra_iso_name)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SPRACHE';

ALTER TABLE sprache
    ADD CONSTRAINT spra_iso_code2_un UNIQUE(spra_iso_code2)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SPRACHE';

ALTER TABLE sprache
    ADD CONSTRAINT spra_iso_code3_un UNIQUE(spra_iso_code3)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'SPRACHTEXT';
CREATE TABLE sprachtext(
    sptx_text         varchar(4000)NOT NULL,
    sptx_gueltig_ab   TIMESTAMP NOT NULL,
    sptx_id           integer
    sptx_spra_id      integer
    sptx_uetx_id      integer
    sptx_uc           varchar(30 BYTE)NOT NULL,
    sptx_dc           TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    sptx_um           varchar(30 BYTE)NULL,
    sptx_dm           TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING INDEX 'SPTX__IDX';

CREATE INDEX sptx__idx ON
    sprachtext(
        sptx_spra_id
    ASC);

PROMPT CREATING INDEX 'SPTX__IDXv1';

CREATE INDEX sptx__idxv1 ON
    sprachtext(
        sptx_uetx_id
    ASC);

PROMPT CREATING PRIMARY KEY ON 'SPRACHTEXT';
ALTER TABLE sprachtext
    ADD CONSTRAINT sptx_pk PRIMARY KEY(sptx_id)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING UNIQUE KEY ON 'SPRACHTEXT';

ALTER TABLE sprachtext
    ADD CONSTRAINT sptx_glt_ab_uk UNIQUE(sptx_spra_id,
                                         sptx_uetx_id,
                                         sptx_gueltig_ab)NOT DEFERRABLE ENABLE VALIDATE;

PROMPT CREATING TABLE 'UEBERSETZ_TEXT';
CREATE TABLE uebersetz_text(
    uetx_originaltext   varchar(4000)NOT NULL,
    uetx_id             integer
    uetx_spra_id        integer
    uetx_wrtb_id        integer
    uetx_uc             varchar(30 BYTE)NOT NULL,
    uetx_dc             TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    uetx_um             varchar(30 BYTE)NULL,
    uetx_dm             TIMESTAMP WITH LOCAL TIME ZONE NULL
)
ORGANIZATION HEAP NOCOMPRESS
    NOCACHE
        NOPARALLEL
    NOROWDEPENDENCIES DISABLE ROW MOVEMENT;

PROMPT CREATING INDEX 'UETX_IDX_SPRA';

CREATE INDEX uetx_idx_spra ON
    uebersetz_text(
        uetx_spra_id
    ASC);

PROMPT CREATING INDEX 'UETX_IDX_TXT';

CREATE INDEX uetx_idx_txt ON
    uebersetz_text(
        uetx_wrtb_id
    ASC);

PROMPT CREATING PRIMARY KEY ON 'UEBERSETZ_TEXT';
ALTER TABLE uebersetz_text
    ADD CONSTRAINT uetx_pk PRIMARY KEY(uetx_id)NOT DEFERRABLE ENABLE VALIDATE;

CREATE TABLE wertebereich(
    wrtb_id                   integer primary key autoincrement ,
    wrtb_business_rule        varchar(4000),
    wrtb_name         varchar(60) not null unique,
    wrtb_beschr        varchar(4000)integer,
    wrtb_typ                  varchar(4) NOT NULL
        CHECK(wrtb_typ IN(
            'BIN',
            'GRP',
            'LOV',
            'NUM',
            'TEXT',
            'ZPKT'
        )),
    wrtb_zpkt_minwert         text,
    wrtb_zpkt_maxwert         text,
    wrtb_zpkt_granularitaet   varchar(15)
        CHECK(wrtb_zpkt_granularitaet IN(
            'JAHR',
            'MILLISEKUNDE',
            'MINUTE',
            'MONAT',
            'QUARTAL',
            'SEKUNDE',
            'SEMESTER',
            'STUNDE',
            'TAG',
            'WOCHE'
        )),
    wrtb_text_maxlng          integer,
    wrtb_text_syntaxregel     varchar(4000),
    wrtb_num_maxwert          integer,
    wrtb_num_minwert          integer,
    wrtb_num_vorkstellen      integer,
    wrtb_num_nachkstellen     integer,
    wrtb_num_rundng_einh      integer,
        CHECK(wrtb_num_rundng_einh IN(
            0.001,
            0.01,
            0.05,
            0.1,
            0.25,
            0.5,
            1,
            10,
            100,
            1000
        )),
    wrtb_bin_inhalttyp        varchar(30)
        CHECK(wrtb_bin_inhalttyp IN(
            'BILD',
            'FILM',
            'GRAPH',
            'TEXT',
            'TON'
        )),
    wrtb_bin_spfo_id          integer,
   FOREIGN KEY(wrtb_bin_spfo_id) REFERENCES speicherformat(spfo_id)
   );
