-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-07-02 18:20:40 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE TABLE speicherformat(
    spfo_id             integer primary key autoincrement,
    spfo_name           varchar(60) NOT NULL,
    spfo_beschreibung   varchar(4000),
    spfo_uc             varchar(30),
    spfo_dc             varchar(30),
    spfo_um             varchar(30),
    spfo_dm             varchar(30),
	constraint spfo_uk (spfo_name)
);

CREATE TABLE sprachen(
    spra_id                integer primary key autoincrement,
    spra_iso_name          varchar(60) NOT NULL,
    spra_iso_code2         CHAR(2) NOT NULL,
    spra_iso_code3         CHAR(3) NOT NULL,
    spra_ist_textsprache   varchar(5) NOT NULL,
    spra_ist_modellsprache   varchar(5) NOT NULL,
    spra_spra_id           integer,
    spra_uc                varchar(30) NOT NULL,
    spra_dc                varchar(30) NOT NULL,
    spra_um                varchar(30) ,
    spra_dm                varchar(30),
    constraint spra_txt_bool CHECK(spra_ist_textsprache IN(
        'FALSE',
        'TRUE'
    )),
    constraint spra_mod_bool CHECK(spra_ist_modellsprache IN(
        'FALSE',
        'TRUE'
    )),
    constraint spra_iso3_low CHECK(spra_iso_code3 = lower(spra_iso_code3)),
    constraint spra_iso2_low CHECK(spra_iso_code2 = lower(spra_iso_code2)),
	constraint spra_iso_uk unique (spra_iso_name),
	constraint spra_iso2_uk unique (spra_iso_code2),
	constraint spra_iso3_uk unique (spra_iso_code3)
);


CREATE TABLE sprachtexte(
    sptx_id           integer primary key autoincrement,
	sptx_attrname	  varchar(30) NOT NULL,
    sptx_text         varchar(4000) ,
    sptx_spra_id      integer,
    sptx_mode_id      integer NOT NULL,
    sptx_uc           varchar(30) NOT NULL,
    sptx_dc           varchar(30) NOT NULL,
    sptx_um           varchar(30) ,
    sptx_dm           varchar(30),
	constraint sptx_attrnameUC check(sptx_attrname = upper(sptx_attrname)),
	constraint sptx_uk unique (sptx_attrname,sptx_spra_id,sptx_mode_id),
    CONSTRAINT sptx_mode_fk FOREIGN KEY(sptx_mode_id)
									   REFERENCES modellelement(mode_id),
	CONSTRAINT sptx_spra_fk FOREIGN KEY(sptx_spra_id)
									   REFERENCES sprachen(spra_id)	
);

CREATE TABLE diagrammtypen(
    diat_id    integer primary key autoincrement,
    diat_bez   varchar(100) NOT NULL,
     diat_uc varchar(30) NOT NULL,
    diat_dc    varchar(30) NOT NULL,
    diat_um    varchar(30) ,
    diat_dm    varchar(30),
	CONSTRAINT diat_un UNIQUE(diat_bez)
)
;
CREATE TABLE diagramme(
    diag_id      integer primary key autoincrement,
    diag_name      varchar(60) NOT NULL,
    diag_diat_id   integer NOT NULL,
    diag_odm_guid       varchar(36),
    diag_legendx       integer,
    diag_legendy       integer,
     diag_uc    varchar(30) NOT NULL,
    diag_dc        varchar(30) NOT NULL,
    diag_um        varchar(30) ,
    diag_dm        varchar(30),
	CONSTRAINT diag__un UNIQUE(diag_name),
	CONSTRAINT diag_diat_fk FOREIGN KEY(diag_diat_id)
									   REFERENCES diagrammtypen(diat_id)
);

CREATE TABLE melt_diat(
    medi_id        integer primary key autoincrement,
    medi_diat_id   integer NOT NULL,
    medi_melt_id   integer NOT NULL,
    medi_uc    varchar(30) NOT NULL,
    medi_dc        varchar(30) NOT NULL,
    medi_um        varchar(30) ,
    medi_dm        varchar(30),
	CONSTRAINT medi__un UNIQUE(medi_diat_id,
	                                   medi_melt_id),
    CONSTRAINT medi_diat_fk FOREIGN KEY(medi_diat_id)			           
					REFERENCES diagrammtpyen(diat_id)
								    ON DELETE CASCADE,
	CONSTRAINT modi_melt_fk FOREIGN KEY(medi_melt_id)
		REFERENCES modellelem_typ(melt_id)
		     ON DELETE CASCADE
)
;

CREATE TABLE elementdarst(
    eled_id               integer primary key autoincrement,
    eled_position_x       integer NULL,
    eled_position_y       integer NULL,
    eled_breite           integer NOT NULL,
    eled_hoehe            integer NOT NULL,
    eled_deckkraft        integer NULL
        CHECK(eled_deckkraft BETWEEN 0 AND 100),
    eled_farbe            varchar(6)  NOT NULL
        CHECK(length(eled_farbe)= 6),
    eled_randbreite       integer NULL,
    eled_randdeckkraft    integer NULL
        CHECK(eled_randdeckkraft BETWEEN 0 AND 100),
    eled_randfarbe        varchar(6)  NULL
        CHECK(length(eled_randfarbe)= 6),
    eled_schriftgroesse   integer NULL
        CHECK(eled_schriftgroesse BETWEEN 1 AND 999),
    eled_schriftfarbe     varchar(6) NULL
        CHECK(length(eled_schriftfarbe)= 6),
    eled_mode_id          integer NOT NULL,
    eled_diag_id          integer NOT NULL,
    eled_uc           varchar(30) NOT NULL,
    eled_dc               varchar(30) NOT NULL,
    eled_um               varchar(30) ,
    eled_dm               varchar(30),
	CONSTRAINT eled_un UNIQUE(eled_diag_id,eled_mode_id),
    CONSTRAINT eled_diag_fk FOREIGN KEY(eled_diag_id)
        REFERENCES diagramme(diag_id)
            ON DELETE CASCADE,
	CONSTRAINT eled_mode_fk FOREIGN KEY(eled_mode_id)
			        REFERENCES modellelement(mode_id)
			            ON DELETE CASCADE
);
CREATE TABLE beziehung_darst(
    beda_id                  integer primary key autoincrement,
    beda_diag_id             integer NOT NULL,
    beda_mode_id             integer NOT NULL,
    beda_linienbreite        integer DEFAULT 1 NOT NULL,
    beda_liniefarbe          varchar(6) NULL
        CHECK(length(beda_liniefarbe)= 6),
    beda_liniedeckkraft      integer NULL
        CHECK(beda_liniedeckkraft BETWEEN 0 AND 100),
    beda_startkante          varchar(1) NULL
        CHECK(beda_startkante IN(
            'N',
            'O',
            'S',
            'W'
        )),
    beda_startposition       integer NULL
        CHECK(beda_startposition BETWEEN 0.0 AND 100.0),
    beda_starttext_winkel    integer NULL
        CHECK(beda_starttext_winkel BETWEEN - 179 AND 180),
    beda_starttext_abstand   integer NULL
        CHECK(beda_starttext_abstand BETWEEN 1 AND 9999),
    beda_starttext_x         integer NULL
        CHECK(beda_starttext_x BETWEEN 0 AND 999999),
    beda_starttext_y         integer NULL
        CHECK(beda_starttext_y BETWEEN 0 AND 999999),
    beda_starttext_breite    integer NULL
        CHECK(beda_starttext_breite BETWEEN 1 AND 9999),
    beda_starttext_hoehe     integer NULL
        CHECK(beda_starttext_hoehe BETWEEN 1 AND 9999),
    beda_endkante            varchar(1) NULL
        CHECK(beda_endkante IN(
            'N',
            'O',
            'S',
            'W'
        )),
    beda_endposition         integer NULL
        CHECK(beda_endposition BETWEEN 0.0 AND 100.0),
    beda_endtext_winkel      integer NULL
        CHECK(beda_endtext_winkel BETWEEN - 179 AND 180),
    beda_endtext_abstand     integer NULL
        CHECK(beda_endtext_abstand BETWEEN 1 AND 9999),
    beda_endtext_x           integer NULL
        CHECK(beda_endtext_x BETWEEN 0 AND 999999),
    beda_endtext_y           integer NULL
        CHECK(beda_endtext_y BETWEEN 0 AND 999999),
    beda_endtext_breite      integer NULL
        CHECK(beda_endtext_breite BETWEEN 1 AND 9999),
    beda_endtext_hoehe       integer NULL
        CHECK(beda_endtext_hoehe BETWEEN 1 AND 9999),
    beda_schriftfarbe        varchar(6) DEFAULT '000000' NULL
        CHECK(length(beda_schriftfarbe)= 6),
    beda_schriftgroesse      integer NULL
        CHECK(beda_schriftgroesse BETWEEN 1 AND 999),
        beda_uc              varchar(30) NOT NULL,
    beda_dc                  varchar(30) NOT NULL,
    beda_um                  varchar(30) ,
    beda_dm                  varchar(30),
	CONSTRAINT beda_un UNIQUE(beda_diag_id,beda_mode_id),
    CONSTRAINT beda_diag_fk FOREIGN KEY(beda_diag_id)
        REFERENCES diagramme(diag_id),
	CONSTRAINT beda_mode_fk FOREIGN KEY(beda_mode_id)
        REFERENCES modellelement(mode_id)
            ON DELETE CASCADE
);

CREATE TABLE linie_segment(
    lise_id          integer primary key autoincrement,
    lise_rhfg        integer NOT NULL,
    lise_beda_id     integer NOT NULL,
    lise_x           integer NOT NULL
        CONSTRAINT ck_beda_beda_schriftfarbe CHECK(lise_x BETWEEN 0 AND 999999) ,
    lise_y           integer NOT NULL
        CONSTRAINT ck_beda_beda_schriftfarbe CHECK(lise_y BETWEEN 0 AND 999999) ,
    lise_linientyp   VARCHAR2(6)NULL
        CONSTRAINT ck_beda_beda_dado CHECK(lise_linientyp IN(
            'DADO',
            'DASHED',
            'DOTTED',
            'SOLID'
        )),
    lise_konnektor   VARCHAR2(3)NULL
    CHECK(lise_konnektor IN(
        '1:1',
        'ISA',
        'M:1',
        'M:N')),
    lise_uc       varchar(30) NOT NULL,
    lise_dc           varchar(30) NOT NULL,
    lise_um           varchar(30) ,
    lise_dm           varchar(30),
	CONSTRAINT lise__un UNIQUE(lise_beda_id,lise_rhfg),
	CONSTRAINT lise_beda_fk FOREIGN KEY(lise_beda_id)
	        REFERENCES beziehung_darst(beda_id)
	            ON DELETE CASCADE
)
;

CREATE TABLE projekt(
    proj_id            integer primary key autoincrement,
    proj_name          VARCHAR(60) NOT NULL,
    proj_uc            VARCHAR(30) NOT NULL,
    proj_dc            VARCHAR(30) NOT NULL,
    proj_sprachen      VARCHAR(60),
    proj_akt_sprache   VARCHAR2(2),
	CONSTRAINT proj__un UNIQUE(proj_name);
)
;
