name: Packaging
# Build model2drawio distribution from Jupyter Notebook

on: [push]

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          # Using 3.10 as the default for github -> faster
          python-version: "3.10"

      - name: Install GNU gettext
        # msgfmt is required by some unittests
        run: sudo apt install -y gettext python3-invoke

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build deployment package. This bootstraps translation
        run: |
          inv verify

      # Run smoke test
      - name: Smoke-test generator
        run: |
          python dist/generator.py --version

      # Unpack the archive and run the generator
      - name: Verify package
        run: |
          mkdir tmp
          cd tmp
          unzip '../dist/model2diagram-*.zip'
          echo "Create SPOD from ODM and generate output"
          rm -f ../pythonWork/pythonSource/testenvironment/testmodels/riddle/DB/riddle.db
          python generator.py --all --languages=en -m ../pythonWork/pythonSource/testenvironment/testmodels/riddle/IM

      - name: Upload packed deployment to github
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: dist/model2diagram-*.zip
          draft: false
          overwrite: true
          tags: true
