name: Quality
# Quality assurance on every push to GitHub.
# Includes SSOT generation for all IM's in fyyccim-refmodels.

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    #    strategy:
    #      max-parallel: 5
    #      matrix: ''

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        # Using 3.9 as the default for github conda image -> faster
        python-version: 3.9

    - name: Install GNU gettext
      # msgfmt is required by some unittests
      run: sudo apt install gettext

    - name: Overview of toolcache
      run: find /opt/hostedtoolcache -type d -maxdepth 2
      continue-on-error: true

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Show current conda environment configuration
      run: |
        conda env list
        conda env export --name base

    - name: Install dependencies
      run: |
        conda env update --file conda-base-environment.yaml --name base

    - name: Unittests with pytest
      run: |
        conda install pytest flake8 coverage
        inv but
        pytest -m "not integration"

    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=120 --count --max-complexity=10 --statistics --exit-zero
    #        # stop the build if there are Python syntax errors or undefined names
    #        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build deployment package
      run: |
        inv package

    - name: Test run generator
      run: |
        inv generator --version

    - name: Integration test run with riddle model located within same git repo
      run: |
        # eventually skip this?
        echo "Update SPOD"
        python dist/generator.py --languages 'en' --model pythonWork/pythonSource/testenvironment/testmodels/riddle/IM --all
        rm pythonWork/pythonSource/testenvironment/testmodels/riddle/DB/riddle.db
        echo "Create SPOD from scratch"
        python dist/generator.py --languages 'en' --model pythonWork/pythonSource/testenvironment/testmodels/riddle/IM --all
        sqlite3 pythonWork/pythonSource/testenvironment/testmodels/riddle/DB/riddle.db "select count(*) from entities"
        echo "Update SPOD"
        python dist/generator.py --languages 'en' --model pythonWork/pythonSource/testenvironment/testmodels/riddle/IM --all

    # Integration test prerequisites
    - name: Clone reference model repository using fycops token
      uses: actions/checkout@v2
      with:
        repository: foryouandyourcustomers/fyyccim-refmodels
        token: ${{ secrets.FYAYC_GITHUB_TOKEN }}
        path: testdata/fyyccim-refmodels

    - name: Integration test run with raetsel-3lang model
      run: |
        rm -f testdata/fyyccim-refmodels/raetsel-3lang/DB/*
        python dist/generator.py --languages=de,en,fr --model testdata/fyyccim-refmodels/raetsel-3lang/IM --all

    - name: Integration test run with CRM model
      run: |
        rm -f testdata/fyyccim-refmodels/CRM/DB/*
        python dist/generator.py --profile --languages=de,en,fr --model testdata/fyyccim-refmodels/CRM/IM --all

    - name: Integration test run with PIM model
      run: |
        rm -f testdata/fyyccim-refmodels/PIM/DB/*
        python dist/generator.py --languages 'en' --model testdata/fyyccim-refmodels/PIM/IM --all

    - name: Integration test run with Health model
      run: |
        rm -f testdata/fyyccim-refmodels/Health/DB/*
        python dist/generator.py --languages 'en' --model testdata/fyyccim-refmodels/Health/IM --all

    - name: Integration test run with BOEB model
      run: |
        git -C testdata/fyyccim-refmodels fetch -v
        git -C testdata/fyyccim-refmodels checkout -f BOEB-IM
        python dist/generator.py --languages 'en' --model testdata/fyyccim-refmodels/BOEB/IM --all

    - name: Integration test run with raetse-3lang 1.5 schema DB -> upgrade
      run: |
        git -C testdata/fyyccim-refmodels checkout -f master
        cp testdata/db-schema-versions/raetsel-3lang-1.5.db testdata/fyyccim-refmodels/raetsel-3lang/DB/raetsel-3lang.db
        python dist/generator.py --languages=de,en,fr --model testdata/fyyccim-refmodels/raetsel-3lang/IM --all

    - name: Integration test run with raetse-3lang 1.6 schema DB -> upgrade
      run: |
        git -C testdata/fyyccim-refmodels checkout -f master
        cp testdata/db-schema-versions/raetsel-3lang-1.6.db testdata/fyyccim-refmodels/raetsel-3lang/DB/raetsel-3lang.db
        python dist/generator.py --languages=de,en,fr --model testdata/fyyccim-refmodels/raetsel-3lang/IM --all

    # Integration test requires testdata/fyyccim-refmodels to be checked out
    # and SPOD generated (*.json files)
    - name: Execute integration tests
      run: |
        pytest -m "integration"

    - name: Clone ktlu-im repository using fycops token
      uses: actions/checkout@v2
      with:
        repository: foryouandyourcustomers/ktlu-im
        token: ${{ secrets.FYAYC_GITHUB_TOKEN }}
        path: testdata/ktlu-im

    - name: Generate Kanton Luzern model (lawa)
      run: |
        python dist/generator.py --languages=de --model testdata/ktlu-im/IM --all

    - name: Clone Bossard repository using fycops token
      uses: actions/checkout@v2
      with:
        repository: foryouandyourcustomers/Bossard-IM
        token: ${{ secrets.FYAYC_GITHUB_TOKEN }}
        path: testdata/Bossard-IM

    - name: Generate Boassard model
      run: |
        python dist/generator.py --languages=de --model testdata/Bossard-IM/IM --all

    - name: Clone Sika repository using fycops token
      uses: actions/checkout@v2
      with:
        repository: foryouandyourcustomers/Sika-IM
        token: ${{ secrets.FYAYC_GITHUB_TOKEN }}
        path: testdata/Sika-IM

    - name: Generate Sika model
      run: |
        python dist/generator.py --languages=de --model testdata/Sika-IM/IM --all

    - name: Create coverage report
      run: |
        echo "Measuring code coverage by running all tests"  
        coverage run -m pytest
        echo "Creating coverage report"
        coverage report -m
